Repository grokability/snipe-it, pull requests merged in 2020-12, with the labels that each got.

#8801 Forward-port of the old LDAP sync system
  app/Console/Commands/LdapSync.php
  app/Console/Commands/LdapSyncNg.php
  app/Http/Controllers/Api/SettingsController.php
  app/Models/Ldap.php
  app/Services/LdapAd.php
Labels: backend

#8846 Fixes #8472 (again) - LDAP sync was assigning a bad default location
  app/Console/Commands/LdapSync.php
Labels: backend, ldap

#8863 Fixes #8853 - allow saml to be more easily debugged
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/SamlController.php
Labels: backend

#8867 use supported package for slack
  composer.json
  config/version.php
Labels: backend

#8915 Localization digit separator feature.
  app/Http/Controllers/SettingsController.php
  app/Presenters/AssetPresenter.php
  database/migrations/2020_12_14_233815_add_digit_separator_to_settings.php
  resources/macros/macros.php
  resources/views/partials/bootstrap-table.blade.php
  resources/views/settings/localization.blade.php
Labels: backend, frontend

#8916 corrected background color for bulk checkout listable items in all da…
  public/css/build/AdminLTE.css
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/build/signature-pad.min.css
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/css/dist/skins/skin-black.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-blue.css
  public/css/dist/skins/skin-contrast.css
  public/css/dist/skins/skin-contrast.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-green.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-orange.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-purple.css
  public/css/dist/skins/skin-red-dark.css
  public/css/dist/skins/skin-red-dark.min.css
  public/css/dist/skins/skin-red.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/css/dist/skins/skin-yellow.css
  public/js/build/app.js
  public/js/build/vendor.js
  public/js/dist/all.js
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
  resources/assets/less/skins/skin-black-dark.less
  resources/assets/less/skins/skin-blue-dark.less
  resources/assets/less/skins/skin-green-dark.less
  resources/assets/less/skins/skin-orange-dark.less
  resources/assets/less/skins/skin-purple-dark.less
  resources/assets/less/skins/skin-red-dark.less
  resources/assets/less/skins/skin-yellow-dark.less
Labels: frontend

#8927 Fixed #8926, #8252 - introduce circular reference check for location parent_id - rebased from #8253
  app/Http/Controllers/LocationsController.php
  app/Models/Location.php
  app/Providers/ValidationServiceProvider.php
  resources/lang/en/validation.php
Labels: backend
