Repository grokability/snipe-it, pull requests merged in 2021-05, with the labels that each got.

#9534 Fixed #9531 - highlight search box when filled, add clear button
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/css/dist/skins/skin-black.css
  public/css/dist/skins/skin-black.min.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-blue.css
  public/css/dist/skins/skin-blue.min.css
  public/css/dist/skins/skin-contrast.css
  public/css/dist/skins/skin-contrast.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-green.css
  public/css/dist/skins/skin-green.min.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-orange.css
  public/css/dist/skins/skin-orange.min.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-purple.css
  public/css/dist/skins/skin-purple.min.css
  public/css/dist/skins/skin-red-dark.css
  public/css/dist/skins/skin-red-dark.min.css
  public/css/dist/skins/skin-red.css
  public/css/dist/skins/skin-red.min.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/css/dist/skins/skin-yellow.css
  public/css/dist/skins/skin-yellow.min.css
  public/mix-manifest.json
  resources/assets/less/skins/skin-black-dark.less
  resources/assets/less/skins/skin-black.less
  resources/assets/less/skins/skin-blue-dark.less
  resources/assets/less/skins/skin-blue.less
  resources/assets/less/skins/skin-contrast.less
  resources/assets/less/skins/skin-green-dark.less
  resources/assets/less/skins/skin-green.less
  resources/assets/less/skins/skin-orange-dark.less
  resources/assets/less/skins/skin-orange.less
  resources/assets/less/skins/skin-purple-dark.less
  resources/assets/less/skins/skin-purple.less
  resources/assets/less/skins/skin-red-dark.less
  resources/assets/less/skins/skin-red.less
  resources/assets/less/skins/skin-yellow-dark.less
  resources/assets/less/skins/skin-yellow.less
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend

#9525 Fixed #7674: Deletes file from assets folder, not just the database reference.
  app/Http/Controllers/Assets/AssetFilesController.php
Labels: backend

#9512 Fixed #9422: pivot ID was being used as a user_id
  app/Http/Controllers/Api/AccessoriesController.php
Labels: backend

#9535 Fixes an issue that causes Custom Reports to sometimes duplicate items. [ch14587]
  app/Http/Controllers/ReportsController.php
Labels: backend

#9543 Fix CSP Always being Enabled unless in debug mode.
  app/Http/Middleware/SecurityHeaders.php
Labels: backend

#9552 Manually re-add support for Label Logos in Labels
  resources/views/hardware/labels.blade.php
Labels: backend, frontend

#9559 Feature #3088 Print labels from asset detail page
  resources/views/hardware/view.blade.php
Labels: backend, frontend

#9571 Fixes an issue with the Settings Seeder and the artisan snipe:demo-settings command that not copies example logos for demo purposes. [ch16422]
  app/Console/Commands/ResetDemoSettings.php
  database/seeds/SettingsSeeder.php
Labels: backend

#9457 [WIP] Initial rough stabs at the Backup Migrator. It kinda-sorta works?
  app/Console/Commands/RestoreFromBackup.php
Labels: backend

#9563 Fix incorrect case of ldap sync status string
  resources/views/users/ldap.blade.php
Labels: backend, frontend

#9584 Fix LicenseSeatsController method documentation
  app/Http/Controllers/Api/LicenseSeatsController.php
Labels: backend, legal

#9619 Several improvements to the snipeit:restore Artisan command
  app/Console/Commands/RestoreFromBackup.php
Labels: backend

#9630 Fixed #9607: Sessions expire for SAML/RemoteUser/LDAP
  app/Http/Controllers/Auth/LoginController.php
Labels: backend

#9632 Fixes an issue that allows duplicate asset tags when the Asset is created via API.
  app/Models/Asset.php
Labels: backend

#9640 Fixes an issue when tried to upload a file to an user without actually selecting a file. [ch16471]
  app/Http/Controllers/Users/UserFilesController.php
  resources/views/modals/upload-file.blade.php
Labels: backend, frontend
