Repository grokability/snipe-it, pull requests merged in 2021-04, with the labels that each got.

#9387 Fixes typo that doesn't accepts 'textarea' as custom field type element.
  app/Models/CustomField.php
Labels: backend

#9318 Fixed #7211, #9197, #7864, [ch15504] - Added additional LDAP fields to sync
  app/Console/Commands/LdapSync.php
  app/Http/Controllers/SettingsController.php
  app/Models/Ldap.php
  database/migrations/2021_03_18_184102_adds_several_ldap_fields.php
  resources/lang/en/admin/settings/general.php
  resources/views/settings/ldap.blade.php
Labels: backend, frontend

#9199 Fixes/cli importer issue
  app/Importer/AssetImporter.php
  app/Models/Asset.php
Labels: backend

#9344 Barcode DPI
  app/Http/Controllers/Assets/AssetsController.php
Labels: :clock10: waiting on OP, backend

#6772 Extend #6229 to include superuser permission check
  app/Models/User.php
Labels: :clock10: waiting on OP

#6909 VAGRANT: Fix Ubuntu Development VMs
  .gitignore
  Vagrantfile
  ansible/ubuntu/apachevirtualhost.conf.j2
  ansible/ubuntu/vagrant_playbook.yml
Labels: :clock10: waiting on OP

#6802 Print all assets & users checked out to Location
  app/Http/Controllers/LocationsController.php
  resources/lang/en/admin/locations/table.php
  resources/views/locations/print.blade.php
  resources/views/locations/view.blade.php
  resources/views/users/print.blade.php
  routes/web.php
Labels: 😬 probably fine but...

#9264 Added #5977: Add permission to view files attached to licenses
  app/Policies/LicensePolicy.php
  config/permissions.php
  resources/views/licenses/view.blade.php
Labels: backend, frontend

#9181 Auditing feature improvement Better mobile [ch14328]
  resources/views/hardware/quickscan.blade.php
Labels: backend, frontend

#9327 Fixed #9179: Add option to force TLS connection
  .env.example
  app/Providers/AppServiceProvider.php
Labels: backend

#9171 Allow NPM packages to build for production
  package-lock.json
  package.json
  public/css/build/signature-pad.min.css
  public/css/dist/signature-pad.min.css
  public/mix-manifest.json
  resources/views/account/accept-asset.blade.php
  webpack.mix.js
Labels: backend, frontend

#8894 The return early pattern applied to improve readability.
  app/Helpers/Helper.php
Labels: backend

#9401 Fixed [ch16210] - fixes docker builds on develop
  Dockerfile
Labels: backend, legal

#9423 Fixes an issue with CSS when the 'skin' value in settings table is empty.
  resources/views/layouts/default.blade.php
Labels: backend, frontend

#9429 Fixes cloning a user that's managed via LDAP throws a password error. [ch15711]
  resources/views/users/edit.blade.php
Labels: backend, frontend

#9424 FIxes Sum of purchase cost of components not taking quantity into account in Asset View > Components tab
  resources/views/hardware/view.blade.php
Labels: backend, frontend

#9426 Update print.blade.php
  resources/views/users/print.blade.php
Labels: backend, frontend

#8325 enable use custom file based saml certificate/private key
  app/Http/Controllers/SettingsController.php
  app/Http/Requests/SettingsSamlRequest.php
  app/Services/Saml.php
  database/migrations/2020_08_11_200712_add_saml_key_rollover.php
  resources/views/settings/saml.blade.php
Labels: :clock10: waiting on OP, saml

#9443 Fixes #9415 Cannot set regex for Custom Field via API.
  app/Http/Controllers/Api/CustomFieldsController.php
  app/Models/CustomField.php
Labels: backend

#9456 Fixed #9447 change route parameter name in locations view
  resources/views/locations/view.blade.php
Labels: backend, frontend

#9445 fix css when not running from webroot directory
  resources/views/layouts/default.blade.php
Labels: backend, frontend

#9356 Fixed #9355: include Accessories and Consumables on the location reports
  resources/views/locations/view.blade.php
Labels: backend, frontend

#9321 (Maybe?) Fixes the problem where we always need LDAP enabled
  app/Http/Controllers/Auth/LoginController.php
  app/Providers/LdapServiceProvider.php
Labels: backend

#9331 Added #9313: Add new fpm-alpine docker image and docker secrets support
  Dockerfile.fpm-alpine
  docker/docker-entrypoint.sh
  docker/docker-secrets.env
Labels: backend, docker

#9350 Fixed #9424: import history adds asset model to assigned user and respects checkin date
  app/Http/Controllers/Assets/AssetsController.php
  resources/views/hardware/history.blade.php
Labels: :clock10: waiting on OP, backend, frontend

#7441 fix ldap ad authentication filter query mechanism
  app/Models/Ldap.php
Labels: ldap

#9466 Fixes #9463 - re-enable LDAP Logins via deferred LdapAd provider
  app/Http/Controllers/Auth/LoginController.php
Labels: backend

#9464 Allow setting the Monolog channel with the LOG_CHANNEL environment variable.
  config/logging.php
Labels: backend, config, frontend

#9467 Features: improved UI for importer
  public/js/build/app.js
  public/js/dist/all.js
  public/mix-manifest.json
  resources/assets/js/components/importer/importer-file.vue
  resources/views/importer/import.blade.php
  resources/views/settings/backups.blade.php
Labels: backend, frontend

#9486 Added user locale to REST API GET /api/users response;
  app/Http/Controllers/Api/ImportController.php
  app/Http/Controllers/Api/UsersController.php
  app/Http/Transformers/UsersTransformer.php
Labels: backend
