Repository grokability/snipe-it, pull requests merged in 2021-10, with the labels that each got.

#10164 Force revalidation headers when user logs out
  app/Http/Kernel.php
  app/Http/Middleware/PreventBackHistory.php
Labels: backend

#10166 Fix default values for custom fields for models rebased
  app/Http/Livewire/CustomFieldSetDefaultValuesForModel.php
  app/Http/Livewire/CustomFieldsForFieldset.php
  composer.lock
  public/vendor/livewire/livewire.js
  public/vendor/livewire/livewire.js.map
  public/vendor/livewire/manifest.json
  resources/assets/js/components/forms/asset-models/fieldset-default-values.vue
  resources/assets/js/vue.js
  resources/views/livewire/custom-field-set-default-values-for-model.blade.php
  resources/views/livewire/custom-fields-for-fieldset.blade.php
  resources/views/models/edit.blade.php
  routes/web/fields.php
Labels: frontend, backend

#10167 Set headers in a different manner in the middleware [sc-17520]
  app/Http/Middleware/PreventBackHistory.php
Labels: backend

#10171 Fixed SVG XSS vuln
  app/Http/Controllers/Assets/AssetFilesController.php
  app/Http/Controllers/Licenses/LicenseFilesController.php
  app/Http/Controllers/Users/UserFilesController.php
  package-lock.json
  public/js/build/app.js
  public/js/dist/all.js
  public/mix-manifest.json
  resources/assets/js/snipeit.js
  resources/views/modals/upload-file.blade.php
Labels: frontend, backend, legal

#10172 Fixed models preview - Use Storage:: facade
  resources/views/models/edit.blade.php
Labels: frontend, backend
