Repository grokability/snipe-it, pull requests merged in 2021-07, with the labels that each got.

#9778 Fixes #9730. Remove an else statement that doesn't allow to continue the importer flow.
  app/Importer/UserImporter.php
  resources/assets/js/components/importer/importer-file.vue
  resources/assets/js/components/importer/importer.vue
Labels: backend, frontend

#9808 Fixes [ch15453] Maintenance/History columns not remembered.
  resources/views/hardware/view.blade.php
Labels: backend, frontend

#9809 The custom settings section of SAML sometimes has bad linefeeds
  resources/views/settings/saml.blade.php
Labels: backend, frontend

#9767 Added #9594 : Feature api image uploads and remove
  app/Http/Controllers/Api/AccessoriesController.php
  app/Http/Controllers/Api/AssetModelsController.php
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Api/CategoriesController.php
  app/Http/Controllers/Api/CompaniesController.php
  app/Http/Controllers/Api/ComponentsController.php
  app/Http/Controllers/Api/ConsumablesController.php
  app/Http/Controllers/Api/DepartmentsController.php
  app/Http/Controllers/Api/LocationsController.php
  app/Http/Controllers/Api/ManufacturersController.php
  app/Http/Controllers/Api/SuppliersController.php
  app/Http/Controllers/Api/UsersController.php
  app/Http/Requests/ImageUploadRequest.php
  app/Http/Traits/ConvertsBase64ToFiles.php
Labels: backend

#9825 Fixed #9767 : Feature/api image uploads legacy image_source property support
  app/Http/Controllers/Api/AssetsController.php
Labels: backend

#9829 Make non linked striped text the same for [ch16602]
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/js/build/app.js
  public/js/dist/all.js
  public/mix-manifest.json
  resources/assets/less/skins/skin-blue-dark.less
  resources/assets/less/skins/skin-green-dark.less
  resources/assets/less/skins/skin-orange-dark.less
  resources/assets/less/skins/skin-purple-dark.less
  resources/assets/less/skins/skin-yellow-dark.less
Labels: frontend

#9856 Fixes: Model Number is not on the Accessory import dropdown of mappable fields [ch15413]
  app/Importer/AccessoryImporter.php
  resources/assets/js/components/importer/importer-file.vue
Labels: backend, frontend

#9861 Fixes #9853 Consumables/Accessories not correctly displayed via Locations
  app/Http/Controllers/Api/AccessoriesController.php
  app/Http/Controllers/Api/ConsumablesController.php
Labels: backend

#9852 adds newer versions of devices for demo
  composer.lock
  database/factories/AssetFactory.php
  database/factories/AssetModelFactory.php
  package-lock.json
  public/img/demo/models/iphone11.jpeg
  public/img/demo/models/iphone12.jpeg
  public/vendor/livewire/livewire.js
  public/vendor/livewire/livewire.js.map
  public/vendor/livewire/manifest.json
Labels: backend, frontend

#9837 Update demo photos of iPhones to be more [ch16531]
  database/factories/AssetModelFactory.php
  database/seeds/AssetModelSeeder.php
  public/img/demo/models/iphone11.jpeg
  public/img/demo/models/iphone12.jpeg
  public/img/demo/models/iphone6.jpg
  public/img/demo/models/iphone7.jpg
Labels: backend

#9824 Added #9594: Feature/api image uploads for v6
  app/Http/Controllers/Api/AccessoriesController.php
  app/Http/Controllers/Api/AssetModelsController.php
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Api/CategoriesController.php
  app/Http/Controllers/Api/CompaniesController.php
  app/Http/Controllers/Api/ComponentsController.php
  app/Http/Controllers/Api/ConsumablesController.php
  app/Http/Controllers/Api/DepartmentsController.php
  app/Http/Controllers/Api/LocationsController.php
  app/Http/Controllers/Api/ManufacturersController.php
  app/Http/Controllers/Api/SuppliersController.php
  app/Http/Controllers/Api/UsersController.php
  app/Http/Requests/ImageUploadRequest.php
  app/Http/Traits/ConvertsBase64ToFiles.php
Labels: backend

#9709 add CompanyableTrait
  app/Models/Asset.php
Labels: backend

#9797 Fixed #9671: wrap OR queries in sub-condition in checkedout search
  app/Http/Controllers/Api/AccessoriesController.php
Labels: backend

#9881 Fixes Integrity constraint violation when emailing password reset.
  app/Http/Controllers/Auth/ForgotPasswordController.php
Labels: backend
