Repository grokability/snipe-it, pull requests merged in 2021-02, with the labels that each got.

#9073 fixed an issue with links colors
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/mix-manifest.json
  resources/assets/less/skins/skin-black-dark.less
Labels: frontend

#9078 Fixes: UserImporter error. [ch15613]
  app/Importer/UserImporter.php
Labels: backend

#9079 Modified how we do Select2 dynamic drop-down menus to be more secure
  app/Http/Controllers/Api/AssetModelsController.php
  app/Http/Controllers/Api/UsersController.php
  app/Http/Transformers/SelectlistTransformer.php
  package-lock.json
  public/js/build/app.js
  public/js/dist/all.js
  public/mix-manifest.json
  resources/assets/js/snipeit.js
  resources/assets/js/snipeit_modals.js
Labels: backend, frontend

#9080 Fix to issue where Select2 model lists were double-HTML-escaped
  app/Http/Controllers/Api/AssetModelsController.php
Labels: backend

#8876 Fixed #8518 - Asset Tag not correctly incremented
  resources/views/hardware/edit.blade.php
Labels: backend, frontend

#9133 Fixes #8918 The validation rules on Manufacturer Model 'name' attribute are malformed.
  app/Http/Controllers/ManufacturersController.php
  app/Models/Manufacturer.php
Labels: backend

#9112 Added feature: Checkbox Custom Fields as list of values.
  app/Http/Controllers/Assets/AssetsController.php
  resources/views/custom_fields/fields/edit.blade.php
  resources/views/models/custom_fields_form.blade.php
Labels: backend, frontend

#9145 Color of asset selection in bulk checkout [ch15525]
  public/css/dist/skins/skin-black.css
  public/css/dist/skins/skin-blue.css
  public/css/dist/skins/skin-green.css
  public/css/dist/skins/skin-orange.css
  public/css/dist/skins/skin-purple.css
  public/css/dist/skins/skin-red.css
  public/css/dist/skins/skin-yellow.css
  public/mix-manifest.json
  resources/assets/less/ekko-lightbox.less
  resources/assets/less/skins/skin-black.less
  resources/assets/less/skins/skin-blue.less
  resources/assets/less/skins/skin-green.less
  resources/assets/less/skins/skin-orange.less
  resources/assets/less/skins/skin-purple.less
  resources/assets/less/skins/skin-red.less
  resources/assets/less/skins/skin-yellow.less
Labels: frontend

#9137 Fixed #9115: Duplicate column name 'provider'
  database/migrations/2021_02_05_172502_add_provider_to_oauth_table.php
Labels: backend

#9088 Fixes #8837 Importer issue when running from CLI.
  app/Importer/AssetImporter.php
  app/Models/Asset.php
Labels: backend

#9168 Add variable declaration for $result
  app/Models/CustomField.php
Labels: backend

#9187 Fixes #9046, #9182 - Added saml custom setting retrieveParametersFromServer to allow fixing SLO issues with Azure AD
  app/Http/Controllers/Auth/SamlController.php
  app/Services/Saml.php
Labels: backend

#9092 [FIX] Lite test email won't use the mail component
  resources/views/notifications/Test.blade.php
  resources/views/vendor/mail/markdown/message.blade.php
Labels: backend, frontend

#9195 Develop to master
  app/Http/Controllers/Auth/SamlController.php
  app/Services/Saml.php
  resources/views/notifications/Test.blade.php
  resources/views/vendor/mail/markdown/message.blade.php
Labels: backend, frontend

#9102 Audit dark mode theme skins and check for [ch15847]
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-red-dark.css
  public/css/dist/skins/skin-red-dark.min.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/mix-manifest.json
  resources/assets/less/skins/skin-black-dark.less
  resources/assets/less/skins/skin-blue-dark.less
  resources/assets/less/skins/skin-green-dark.less
  resources/assets/less/skins/skin-orange-dark.less
  resources/assets/less/skins/skin-purple-dark.less
  resources/assets/less/skins/skin-red-dark.less
  resources/assets/less/skins/skin-yellow-dark.less
Labels: frontend

#9210 Fixes #9036 Issue when offset is greater than the number of locations.
  app/Http/Controllers/Api/LocationsController.php
Labels: backend

#9170 Fixes a couple blade templates for relative URLs
  resources/views/account/accept-asset.blade.php
  resources/views/vendor/passport/authorize.blade.php
Labels: backend, frontend
