Repository grokability/snipe-it, pull requests merged in 2021-01, with the labels that each got.

#8973 Fix for default parameters in JS functions IE
  resources/views/partials/bootstrap-table.blade.php
Labels: backend, frontend

#8993 Bug/ch15603/read only text field in saml screen dark
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-red-dark.css
  public/css/dist/skins/skin-red-dark.min.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/mix-manifest.json
  resources/assets/less/skins/skin-black-dark.less
  resources/assets/less/skins/skin-blue-dark.less
  resources/assets/less/skins/skin-green-dark.less
  resources/assets/less/skins/skin-orange-dark.less
  resources/assets/less/skins/skin-purple-dark.less
  resources/assets/less/skins/skin-red-dark.less
  resources/assets/less/skins/skin-yellow-dark.less
Labels: frontend

#9034 fixed color schema on dark mode skins for links
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-red-dark.css
  public/css/dist/skins/skin-red-dark.min.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/mix-manifest.json
  resources/assets/less/skins/skin-black-dark.less
  resources/assets/less/skins/skin-blue-dark.less
  resources/assets/less/skins/skin-green-dark.less
  resources/assets/less/skins/skin-orange-dark.less
  resources/assets/less/skins/skin-purple-dark.less
  resources/assets/less/skins/skin-red-dark.less
  resources/assets/less/skins/skin-yellow-dark.less
Labels: frontend

#9029 Fixed non-superadmin gate permissions for kits
  app/Policies/PredefinedKitPolicy.php
  app/Providers/AuthServiceProvider.php
Labels: backend

#9048 Use the correct env variables in config/auth.php file.
  app/Http/Controllers/Auth/LoginController.php
  config/auth.php
Labels: backend

#8989 Add 'Last Audit Date/Next Audit Date' filter to custom report
  app/Http/Controllers/ReportsController.php
  resources/views/reports/custom.blade.php
Labels: backend, frontend

#8938 Added today as default Date for checkout Form.
  resources/views/hardware/checkout.blade.php
Labels: backend, frontend

#8936 Add migration for ldap_server URL's to ensure they are valid
  database/migrations/2020_12_21_210105_fix_bad_ldap_server_url_for_v5.php
Labels: backend

#8923 Optimize target type + ID index for more realistic use cases
  database/migrations/2020_12_18_090026_swap_target_type_index_order.php
Labels: backend

#8978 Added #8931: add health controller without session
  app/Http/Controllers/HealthController.php
  app/Http/Kernel.php
  app/Http/Middleware/CheckForSetup.php
  app/Http/Middleware/NoSessionStore.php
  app/Http/Middleware/VerifyCsrfToken.php
  routes/web.php
Labels: backend

#8887 Fix for #8890: The last audit is not recorded correctly. (12/24hours ambiguity fix)
  app/Http/Controllers/Api/AssetsController.php
Labels: backend

#9051 Added better visual cues for login
  resources/lang/en/auth/general.php
  resources/lang/en/general.php
  resources/views/auth/login.blade.php
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/reset.blade.php
  resources/views/layouts/basic.blade.php
Labels: auth, backend, frontend

#9052 Added termination date, depreciation in license column selection [ch14505]
  app/Http/Controllers/Api/LicensesController.php
  app/Http/Transformers/LicensesTransformer.php
  app/Models/License.php
  app/Presenters/LicensePresenter.php
  resources/views/licenses/view.blade.php
Labels: backend, frontend

#9055 Fixes #9041 - Instead of return a JSON response, redirect back to the previous screen. [ch15737]
  app/Http/Controllers/Users/UserFilesController.php
Labels: backend

#9053 Fixes #8834 - Added support for radio buttons in Custom Fields.
  app/Models/CustomField.php
  resources/views/custom_fields/fields/edit.blade.php
  resources/views/models/custom_fields_form.blade.php
Labels: backend, frontend

#9058 Fix issue where users with edit permission cannot invoke LDAP sync
  app/Http/Controllers/Users/LDAPImportController.php
Labels: backend

#9059 Depreciation detail view fixes [ch15776]
  app/Http/Controllers/Api/AssetModelsController.php
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Api/DepreciationsController.php
  app/Http/Controllers/Api/LicensesController.php
  app/Presenters/AssetModelPresenter.php
  app/Presenters/DepreciationPresenter.php
  resources/views/depreciations/index.blade.php
  resources/views/depreciations/view.blade.php
  resources/views/models/bulk-edit.blade.php
  resources/views/models/index.blade.php
Labels: backend, frontend, legal
