Repository grokability/snipe-it, pull requests merged in 2021-06, with the labels that each got.

#9685 WIP #9668: API changes to allow Datatables to function correctly [develop-v6]
  app/Exceptions/Handler.php
  app/Http/Kernel.php
  app/Providers/RouteServiceProvider.php
  routes/api.php
Labels: backend

#9683 Fixed #9682: Add indexes for company_id
  database/migrations/2021_06_07_155436_add_company_id_indexes.php
Labels: backend

#9679 Fixed #8486: Add index for asset serial number
  database/migrations/2021_06_07_155421_add_serial_number_indexes.php
Labels: backend

#9699 Basic fixes to at least get the dashboard up
  routes/api.php
  routes/web.php
Labels: backend

#9702 Finished fixing the web routes file
  routes/api.php
  routes/web.php
Labels: backend

#9704 Get it so that we can re-build assets.
  .nvmrc
  package-lock.json
  package.json
  public/css/build/AdminLTE.css
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/css/dist/signature-pad.min.css
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/css/dist/skins/skin-black.css
  public/css/dist/skins/skin-black.min.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-blue.css
  public/css/dist/skins/skin-blue.min.css
  public/css/dist/skins/skin-contrast.css
  public/css/dist/skins/skin-contrast.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-green.css
  public/css/dist/skins/skin-green.min.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-orange.css
  public/css/dist/skins/skin-orange.min.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-purple.css
  public/css/dist/skins/skin-purple.min.css
  public/css/dist/skins/skin-red-dark.css
  public/css/dist/skins/skin-red-dark.min.css
  public/css/dist/skins/skin-red.css
  public/css/dist/skins/skin-red.min.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/css/dist/skins/skin-yellow.css
  public/css/dist/skins/skin-yellow.min.css
  public/js/build/app.js
  public/js/build/vendor.js
  public/js/dist/all.js
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
  webpack.mix.js
Labels: frontend

#9737 Develop v6 integration
  public/js/build/app.js
  public/js/build/vendor.js
  public/js/dist/all.js
  public/mix-manifest.json
  resources/assets/js/bootstrap.js
  resources/assets/js/components/select2.vue
  resources/assets/js/snipeit.js
  resources/assets/js/vue.js
  resources/views/layouts/default.blade.php
  routes/api.php
  routes/web/hardware.php
  routes/web/kits.php
  routes/web/licenses.php
  webpack.mix.js
Labels: backend, frontend, legal

#9720 Update company-select.blade.php
  resources/views/partials/forms/edit/company-select.blade.php
Labels: backend, frontend

#9717 Added #9716: Allow to bulk update accessories min_amt
  app/Models/Accessory.php
Labels: backend

#9695 Update print.blade.php
  resources/views/users/print.blade.php
Labels: backend, frontend

#9681 Fixed #9680: Use Eloquent’s `withCount` method to count Statuslabel assets
  app/Http/Controllers/Api/StatuslabelsController.php
Labels: backend

#9676 Fixes #9666 Asset checkin via api doesn't send notification.
  app/Http/Controllers/Api/AssetsController.php
Labels: backend

#9738 corrected a link color in the dark mode yellow skin
  package-lock.json
  public/css/build/AdminLTE.css
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/css/dist/signature-pad.min.css
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/css/dist/skins/skin-black.css
  public/css/dist/skins/skin-black.min.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-blue.css
  public/css/dist/skins/skin-blue.min.css
  public/css/dist/skins/skin-contrast.css
  public/css/dist/skins/skin-contrast.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-green.css
  public/css/dist/skins/skin-green.min.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-orange.css
  public/css/dist/skins/skin-orange.min.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-purple.css
  public/css/dist/skins/skin-purple.min.css
  public/css/dist/skins/skin-red-dark.css
  public/css/dist/skins/skin-red-dark.min.css
  public/css/dist/skins/skin-red.css
  public/css/dist/skins/skin-red.min.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/css/dist/skins/skin-yellow.css
  public/css/dist/skins/skin-yellow.min.css
  public/css/skins/dist/skin-black-dark.css
  public/js/build/app.js
  public/js/build/vendor.js
  public/js/dist/all.js
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
  resources/assets/less/skins/skin-yellow-dark.less
Labels: frontend

#9741 Removed Ziggy.baseUrl references for meta references that already had baseUrl
  public/js/build/app.js
  public/js/dist/all.js
  public/mix-manifest.json
  resources/assets/js/snipeit.js
  resources/assets/js/snipeit_modals.js
  resources/views/layouts/default.blade.php
Labels: backend, frontend

#9761 Added #9745 - adds searchable, sortable notes to statuslabels index
  app/Http/Controllers/Api/StatuslabelsController.php
  app/Models/Statuslabel.php
  resources/views/statuslabels/index.blade.php
Labels: backend, frontend

#9764 Regenerate assets after repairing Vue integration
  public/css/build/AdminLTE.css
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/css/dist/signature-pad.min.css
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/css/dist/skins/skin-black.css
  public/css/dist/skins/skin-black.min.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-blue.css
  public/css/dist/skins/skin-blue.min.css
  public/css/dist/skins/skin-contrast.css
  public/css/dist/skins/skin-contrast.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-green.css
  public/css/dist/skins/skin-green.min.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-orange.css
  public/css/dist/skins/skin-orange.min.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-purple.css
  public/css/dist/skins/skin-purple.min.css
  public/css/dist/skins/skin-red-dark.css
  public/css/dist/skins/skin-red-dark.min.css
  public/css/dist/skins/skin-red.css
  public/css/dist/skins/skin-red.min.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/css/dist/skins/skin-yellow.css
  public/css/dist/skins/skin-yellow.min.css
  public/js/build/app.js
  public/js/build/vendor.js
  public/js/dist/all.js
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
  resources/assets/js/vue.js
Labels: frontend

#9766 Livewire integration for Snipe-IT v6
  app/Exceptions/Handler.php
  app/Http/Livewire/CustomFieldSetDefaultValuesForModel.php
  app/Http/Livewire/CustomFieldsForFieldset.php
  composer.json
  composer.lock
  public/vendor/livewire/livewire.js
  public/vendor/livewire/livewire.js.map
  public/vendor/livewire/manifest.json
  resources/views/layouts/basic.blade.php
  resources/views/layouts/default.blade.php
  resources/views/livewire/custom-field-set-default-values-for-model.blade.php
  resources/views/livewire/custom-fields-for-fieldset.blade.php
  resources/views/models/edit.blade.php
Labels: backend, frontend

#9774 Better debugging output, and remove non-PHP-7.3-compatible option
  app/Console/Commands/RestoreFromBackup.php
Labels: backend
