Repository grokability/snipe-it, pull requests merged in 2021-12, with the labels that each got.

#9902 Fixed #5676: Sum cost by quantity
  app/Presenters/AccessoryPresenter.php
  app/Presenters/ComponentPresenter.php
  app/Presenters/ConsumablePresenter.php
  app/Presenters/LicensePresenter.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend, legal

#10394 Adds stricter validation for slack hooks
  app/Http/Controllers/Api/SettingsController.php
  app/Http/Controllers/SettingsController.php
  app/Models/Setting.php
  resources/lang/en/validation.php
  resources/views/settings/slack.blade.php
Labels: frontend, backend

#10393 Fixed #10365: Snipe-IT has a wrong total purchase cost when reaches m…
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#10239 adds info on how to nullify reorder alerts for consumables, component…
  resources/lang/en/general.php
Labels: backend

#10406 security fix
  app/Http/Controllers/AssetModelsController.php
Labels: backend

#10414 Added model number to accessory report
  resources/views/reports/accessories.blade.php
Labels: frontend, backend

#10416 Yank assetlog from eager-load clause in API query for develop
  app/Http/Controllers/Api/AssetsController.php
Labels: backend

#10415 Remove 'actionlog' from the ::with() clause in the asset query API
  app/Http/Controllers/Api/AssetsController.php
Labels: backend

#10422 Adds an automatic build for Alpine Linux based Image
  .github/workflows/docker-alpine.yml
Labels: config

#10423 Automatic Building of Docker Images and Pushing to DockerHub
  .github/workflows/docker.yml
Labels: config

#10426 Added escape to assigned_to API response
  app/Http/Transformers/AssetsTransformer.php
Labels: backend

#10418 Fixes bulk edit message counts more users than the actual selected users number
  app/Http/Controllers/Users/BulkUsersController.php
Labels: backend

#10432 Add title column to custom reports
  app/Http/Controllers/ReportsController.php
  resources/views/reports/custom.blade.php
Labels: frontend, backend

#10433 Add title column to custom reports on master branch
  app/Http/Controllers/ReportsController.php
  resources/views/reports/custom.blade.php
Labels: frontend, backend

#10434 Fix route to checkout components from the details page
  resources/views/components/view.blade.php
  routes/web/components.php
Labels: frontend, backend

#10439 Update SettingsController.php to save Slack Settings
  app/Http/Controllers/SettingsController.php
Labels: backend

#10421 Create new user account from asset form - additional fields
  resources/views/modals/user.blade.php
Labels: frontend, backend

#10460 Fixes Duplicate department in user import
  resources/assets/js/components/importer/importer-file.vue
Labels: frontend

#10463 Fixed #10461: Groups management page did not paginate correctly
  app/Http/Transformers/GroupsTransformer.php
Labels: backend

#10468 Fixed #10467 - Safari only font-awesome bug
  public/css/build/AdminLTE.css
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/css/dist/signature-pad.css
  public/css/dist/signature-pad.min.css
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/css/dist/skins/skin-black.css
  public/css/dist/skins/skin-black.min.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-blue.css
  public/css/dist/skins/skin-blue.min.css
  public/css/dist/skins/skin-contrast.css
  public/css/dist/skins/skin-contrast.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-green.css
  public/css/dist/skins/skin-green.min.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-orange.css
  public/css/dist/skins/skin-orange.min.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-purple.css
  public/css/dist/skins/skin-purple.min.css
  public/css/dist/skins/skin-red-dark.css
  public/css/dist/skins/skin-red-dark.min.css
  public/css/dist/skins/skin-red.css
  public/css/dist/skins/skin-red.min.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/css/dist/skins/skin-yellow.css
  public/css/dist/skins/skin-yellow.min.css
  public/js/build/app.js
  public/js/build/vendor.js
  public/js/dist/all.js
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
  resources/assets/less/overrides.less
Labels: frontend

#10470 Fixed #10469 - increased size of supplier address field
  app/Models/Supplier.php
  database/migrations/2021_12_27_151849_change_supplier_address_length.php
Labels: backend

#10475 Fixed assets_count doesnt exist as a column on kits
  app/Http/Controllers/Api/PredefinedKitsController.php
Labels: backend

#10476 Fixed missing index for fieldsets
  app/Http/Controllers/CustomFieldsetsController.php
Labels: backend

#10478 Added allow list to modal view options
  app/Http/Controllers/ModalController.php
Labels: backend

#10479 Fixed auto asset tag phrasing
  resources/lang/en/admin/settings/general.php
  resources/views/settings/asset_tags.blade.php
Labels: frontend, backend
