Repository grokability/snipe-it, pull requests merged in 2021-11, with the labels that each got.

#10258 Fixed #8828: Can't search by checked out user in advanced search
  app/Models/Asset.php
Labels: backend

#10283 Fixes/remove get logout route
  resources/views/layouts/default.blade.php
  routes/web.php
Labels: frontend, backend

#10279 Turn custom fields required/optional/remove into POST requests
  resources/views/custom_fields/fieldsets/view.blade.php
  routes/web/fields.php
Labels: frontend, backend

#10286 Escape asset_tag attribute at controller level for bulk checkout
  app/Http/Controllers/Api/AssetsController.php
Labels: backend

#10296 Tweak Restore command to _also_ run via webserver via Artisan::call()
  app/Console/Commands/RestoreFromBackup.php
Labels: backend

#10298 Cleaned up the output and added some better checks for errors
  app/Console/Commands/RestoreFromBackup.php
Labels: backend

#10302 Typo in upgrade.php
  upgrade.php
Labels: backend

#10303 Added the current_value string to correspondig 'en' language directory
  resources/lang/en/admin/hardware/table.php
Labels: backend

#10297 v6 Feature - Added backup restore from GUI
  app/Console/Commands/RestoreFromBackup.php
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/SettingsController.php
  app/Http/Requests/AssetFileRequest.php
  app/Http/Requests/ImageUploadRequest.php
  package-lock.json
  public/css/build/overrides.css
  public/css/dist/all.css
  public/js/build/app.js
  public/js/dist/all.js
  public/js/snipeit.js
  public/mix-manifest.json
  resources/assets/js/snipeit.js
  resources/lang/en/general.php
  resources/views/layouts/default.blade.php
  resources/views/licenses/view.blade.php
  resources/views/settings/backups.blade.php
  routes/web.php
Labels: frontend, backend, legal

#10315 Escape custom field values in API response
  app/Http/Transformers/AssetsTransformer.php
Labels: backend

#10316 v6 bug - Error when editing model with no custom
  app/Http/Livewire/CustomFieldSetDefaultValuesForModel.php
  resources/views/livewire/custom-field-set-default-values-for-model.blade.php
Labels: frontend, backend

#10333 Fixed v6 bug 500 server error when trying to checkin
  routes/web/components.php
Labels: backend

#10334 Added text-right to presenters for money values
  app/Presenters/AccessoryPresenter.php
  app/Presenters/AssetAuditPresenter.php
  app/Presenters/AssetMaintenancesPresenter.php
  app/Presenters/AssetPresenter.php
  app/Presenters/ComponentPresenter.php
  app/Presenters/ConsumablePresenter.php
  app/Presenters/DepreciationReportPresenter.php
  app/Presenters/LicensePresenter.php
Labels: backend, legal

#10349 Update upgrade.php with newer requires
  upgrade.php
Labels: backend

#10355 Fixes Default Values - Date not applying for master branch
  resources/views/models/custom_fields_form.blade.php
Labels: frontend, backend

#10360 Removed escaping on input save for asset checkout on creation
  app/Http/Controllers/Assets/AssetsController.php
Labels: backend

#10356 fix modal-title html tag unpaired.
  resources/views/categories/edit.blade.php
  resources/views/layouts/default.blade.php
  resources/views/modals/category.blade.php
  resources/views/modals/kit-accessory.blade.php
  resources/views/modals/kit-consumable.blade.php
  resources/views/modals/kit-license.blade.php
  resources/views/modals/kit-model.blade.php
  resources/views/modals/location.blade.php
  resources/views/modals/manufacturer.blade.php
  resources/views/modals/model.blade.php
  resources/views/modals/statuslabel.blade.php
  resources/views/modals/supplier.blade.php
  resources/views/modals/upload-file.blade.php
Labels: frontend, backend

#10354 Fixes Default Values - Date not applying
  resources/views/models/custom_fields_form.blade.php
Labels: frontend, backend

#10350 Apply trim() function when storing Custom Fields names
  app/Http/Controllers/CustomFieldsController.php
Labels: backend

#10345 Fixed #10344 and #9135: don't prepand fields with a whitespace in text based export formats
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#10361 Escape notes in transformCheckedOutAccessory
  app/Http/Transformers/AccessoriesTransformer.php
Labels: backend, :closed_lock_with_key: security
