Repository grokability/snipe-it, pull requests merged in 2021-09, with the labels that each got.

#10034 Fixed [ch15359] ajaxify the depreciation report
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Transformers/DepreciationReportTransformer.php
  app/Presenters/DepreciationReportPresenter.php
  resources/views/reports/depreciation.blade.php
  routes/api.php
Labels: frontend, backend

#10043 Use the new Issues form
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: config

#10048 Fix to PR #10009. The asset search now works as intended for normal users
  app/Models/Asset.php
  app/Models/User.php
Labels: backend

#10053 Fix Accepted Assets still showing on Unaccepted Asset Report
  app/Listeners/CheckoutableListener.php
Labels: backend

#10031 Fixed #10026: Checkout date not saved in asset history
  app/Http/Transformers/ActionlogsTransformer.php
  resources/views/reports/activity.blade.php
Labels: frontend, backend

#10059 Convert value of column 'checkout type' in CSV file to lowercase
  app/Importer/ItemImporter.php
Labels: backend

#10063 Fixed #10062: Added Support for Heroku Deployments
  Procfile
  README.md
  app.json
  heroku/startup.php
Labels: backend

#10069 Fixed #9973 - add use_default_eula to category endpoint
  app/Http/Transformers/CategoriesTransformer.php
  app/Presenters/CategoryPresenter.php
  resources/lang/en/admin/categories/general.php
Labels: backend

#10070 Fixed #9969 - added color, show_in_nav, and default_label to status l…
  app/Http/Controllers/Api/StatuslabelsController.php
Labels: backend

#10079 Fixes #10015. Archived Assets Showing Under Locations/'Print All Assigned' Feature
  resources/views/locations/print.blade.php
Labels: frontend, backend

#10086 Fixed extraneous asset search in depreciation report
  app/Http/Controllers/ReportsController.php
Labels: backend

#10104 Fixes pave command to persist api keys and first few test users
  app/Console/Commands/PaveIt.php
Labels: backend

#10112 Improved category_type with strtolower() to make it case insensitive
  app/Http/Controllers/Api/CategoriesController.php
Labels: backend

#10111 Added restore functionality to user API
  app/Http/Controllers/Api/UsersController.php
  routes/api.php
Labels: backend

#10114 Fixes sorting on non-asset relations in API
  app/Http/Controllers/Api/AccessoriesController.php
  app/Http/Controllers/Api/ComponentsController.php
  app/Http/Controllers/Api/ConsumablesController.php
  app/Models/Accessory.php
Labels: backend

#10115 Added totals to depreciation report footer
  app/Http/Transformers/DepreciationReportTransformer.php
  app/Presenters/DepreciationReportPresenter.php
  resources/views/reports/depreciation.blade.php
Labels: frontend, backend

#10122 Fixes API Issue when checking out a component
  app/Http/Controllers/Api/ComponentsController.php
Labels: backend

#10124 Added assigned components to assets API
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Api/UsersController.php
  app/Http/Transformers/AssetsTransformer.php
  app/Models/Asset.php
Labels: backend

#10123 Fixed #9928: update expected field name for response list
  resources/assets/js/snipeit.js
Labels: frontend

#10125 Added userpics from thispersondoesnotexist.com
  database/seeders/AssetModelSeeder.php
  database/seeders/UserSeeder.php
  public/img/demo/avatars/1.jpg
  public/img/demo/avatars/10.jpg
  public/img/demo/avatars/11.jpg
  public/img/demo/avatars/12.jpg
  public/img/demo/avatars/13.jpg
  public/img/demo/avatars/14.jpg
  public/img/demo/avatars/15.jpg
  public/img/demo/avatars/16.jpg
  public/img/demo/avatars/17.jpg
  public/img/demo/avatars/18.jpg
  public/img/demo/avatars/19.jpg
  public/img/demo/avatars/2.jpg
  public/img/demo/avatars/20.jpg
  public/img/demo/avatars/3.jpg
  public/img/demo/avatars/4.jpg
  public/img/demo/avatars/5.jpg
  public/img/demo/avatars/6.jpg
  public/img/demo/avatars/7.jpg
  public/img/demo/avatars/8.jpg
  public/img/demo/avatars/9.jpg
Labels: backend

#10128 Fixes route not defined exception on components and consumables
  routes/web/components.php
  routes/web/consumables.php
Labels: backend

#10103 Fixed issue when creating a status label via API - default_label and show_in_nav being not nullable
  app/Http/Controllers/Api/StatuslabelsController.php
  database/migrations/2016_08_23_145619_add_show_in_nav_to_status_labels.php
  database/migrations/2018_03_06_054937_add_default_flag_on_statuslabels.php
  database/migrations/2021_09_20_183216_change_default_label_to_nullable.php
Labels: backend

#10135 Rename license migration to resolve fatal error running migrations
  database/migrations/2013_11_25_013244_recreate_licenses_table.php
Labels: backend

#10141 Fixed #9789 and Fixed #10088 and Fixed [fd23442] - Fix currency problems especially with European currency format
  app/Helpers/Helper.php
  app/Http/Controllers/Accessories/AccessoriesController.php
  app/Http/Controllers/Api/AssetMaintenancesController.php
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/AssetMaintenancesController.php
  app/Http/Controllers/Assets/AssetsController.php
  app/Http/Controllers/Assets/BulkAssetsController.php
  app/Http/Controllers/Components/ComponentsController.php
  app/Http/Controllers/Consumables/ConsumablesController.php
  app/Http/Controllers/Licenses/LicensesController.php
  app/Http/Controllers/ReportsController.php
  app/Http/Transformers/LicensesTransformer.php
  config/app.php
  resources/views/asset_maintenances/view.blade.php
  resources/views/hardware/qr-view.blade.php
  resources/views/hardware/view.blade.php
  resources/views/partials/bootstrap-table.blade.php
  resources/views/suppliers/view.blade.php
  resources/views/users/view.blade.php
Labels: frontend, backend, legal

#10150 Fixes New department error importing users.
  app/Importer/UserImporter.php
Labels: backend
