Repository grokability/snipe-it, pull requests merged in 2022-05, with the labels that each got.

#11000 Fixes Activity Report Download all action fails creating the CSV report.
  app/Http/Controllers/ReportsController.php
Labels: backend

#11001 Fixes Activity Report Download all action fails creating the CSV report for develop.
  app/Http/Controllers/ReportsController.php
Labels: backend

#11016 Update feature_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: config

#11018 Update BS tables and table export to latest
  package-lock.json
  package.json
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
  webpack.mix.js
Labels: frontend

#11002 Fixes QueryException Integrity constraint violation: Column 'order' cannot be null
  app/Http/Controllers/CustomFieldsetsController.php
Labels: backend

#11003 Fixes QueryException Integrity constraint violation: Column 'order' cannot be null for develop
  app/Http/Controllers/CustomFieldsetsController.php
Labels: backend

#10941 [Fix] changes the query for the accept signature on print blade
  resources/views/users/print.blade.php
Labels: frontend, backend

#11022 Use full app_url in favicon paths
  resources/views/layouts/default.blade.php
Labels: frontend, backend

#11023 Fixed #10890 - Use translation strings in assigned printout instead of hardcoded English
  resources/lang/en/general.php
  resources/views/users/print.blade.php
Labels: frontend, backend

#11025 Fixed #10890 - Missed a few hard coded english strings
  resources/lang/en/general.php
  resources/views/users/print.blade.php
Labels: frontend, backend

#11027 Fixed #11026 - add bulk edit to other asset views
  app/Http/Controllers/Assets/BulkAssetsController.php
  app/Presenters/AssetAuditPresenter.php
  resources/lang/am/admin/hardware/message.php
  resources/lang/en/admin/hardware/message.php
  resources/views/categories/view.blade.php
  resources/views/hardware/audit-due.blade.php
  resources/views/hardware/bulk.blade.php
  resources/views/hardware/index.blade.php
  resources/views/locations/view.blade.php
  resources/views/manufacturers/view.blade.php
  resources/views/models/view.blade.php
  resources/views/partials/asset-bulk-actions.blade.php
  resources/views/users/view.blade.php
Labels: frontend, backend

#11039 Added license seat ID to the UI
  app/Presenters/LicensePresenter.php
Labels: backend, legal

#11040 Remove extraneous `{` in migration
  database/migrations/2015_09_21_235926_create_custom_field_custom_fieldset.php
Labels: backend

#11048 Fixed validation for purchase cost allowed to be negative
  app/Models/Accessory.php
  app/Models/Asset.php
  app/Models/Component.php
  app/Models/Consumable.php
  app/Models/License.php
  resources/lang/en/validation.php
Labels: backend, legal

#11055 Update Livewire assets, and make Composer auto-update Livewire assets
  composer.json
  public/vendor/livewire/livewire.js
  public/vendor/livewire/livewire.js.map
  public/vendor/livewire/manifest.json
Labels: frontend

#11050 Make sure to decrypt Textareas as well as input type=text
  resources/views/models/custom_fields_form.blade.php
Labels: frontend, backend

#11058 Fixed kit checkout permissions if admin is not superadmin
  app/Http/Controllers/Kits/CheckoutKitController.php
  app/Policies/SnipePermissionsPolicy.php
  config/permissions.php
Labels: backend

#11063 Sets maxlength of user fields to 191
  app/Models/User.php
  resources/views/users/edit.blade.php
Labels: frontend, backend

#11066 Switch the barcode backend to SVG, and fix the two-factor middleware
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Middleware/CheckForTwoFactor.php
  config/google2fa.php
Labels: backend

#11067 Fix cancel button in two-factor sign-in screen
  resources/views/auth/two_factor.blade.php
Labels: frontend, backend

#11065 Fixed #11014 - double encoding for custom fields
  app/Http/Controllers/Assets/AssetsController.php
Labels: backend

#11070 Added missing use statement
  app/Http/Controllers/Api/SettingsController.php
Labels: backend

#11073 Fixed #11052 - add file sizes to upload displays
  app/Helpers/Helper.php
  resources/lang/en/general.php
  resources/views/hardware/view.blade.php
  resources/views/licenses/view.blade.php
  resources/views/users/view.blade.php
Labels: frontend, backend, legal

#11076 Fixes #10706 - Fix saml slo for logout
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/SamlController.php
  routes/web.php
Labels: backend

#11077 Fix route for people file deletion
  resources/views/users/view.blade.php
Labels: frontend, backend

#11079 Fixed missing backups help string
  resources/lang/en/admin/settings/general.php
Labels: backend

#11078 Adds encrypted status to custom fields overview
  resources/views/custom_fields/index.blade.php
Labels: frontend, backend

#11080 Removed sr-only class for now - not sure why it’s interfering with the upload button
  resources/views/settings/backups.blade.php
Labels: frontend, backend

#11088 Only set manager ID when the lookup succeeds.
  app/Console/Commands/LdapSync.php
Labels: backend

#11107 Fixed #11104 - bulk-user reset-password links returning 500
  app/Http/Controllers/Users/BulkUsersController.php
Labels: backend

#11108 Pass the password along directly instead of retrieving it from the In…
  app/Http/Controllers/Auth/LoginController.php
  app/Models/Ldap.php
Labels: backend

#11111 Fixed #11100 for individual users
  app/Http/Controllers/Users/UsersController.php
Labels: backend

#11113 Fixed #11112 - use correct formatter for locations on dashboard
  resources/views/dashboard.blade.php
Labels: frontend, backend

#11114 We inadvertently used the wrong label for one of the headers
  resources/views/settings/backups.blade.php
Labels: frontend, backend

#11115 Update constraints to allow up to 8.2
  composer.json
  composer.lock
  public/vendor/livewire/livewire.js
  public/vendor/livewire/livewire.js.map
  public/vendor/livewire/manifest.json
Labels: frontend

#11127 Fixed #11126: don't entitise custom CSS on the labels view
  resources/views/hardware/labels.blade.php
Labels: frontend, backend

#11133 Fixes #11096 Backup created_at time is incorrect
  app/Http/Controllers/SettingsController.php
Labels: backend

#11136 Fixed #11124 - updated maintenance page
  resources/lang/en/general.php
  resources/views/errors/503.blade.php
Labels: frontend, backend

#11137 Delete vendor/symfony/translation/TranslatorInterface.php in upgrader
  upgrade.php
Labels: backend

#11138 Bumped packages
  package-lock.json
  package.json
  public/css/build/AdminLTE.css
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/css/dist/signature-pad.css
  public/css/dist/signature-pad.min.css
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/css/dist/skins/skin-black.css
  public/css/dist/skins/skin-black.min.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-blue.css
  public/css/dist/skins/skin-blue.min.css
  public/css/dist/skins/skin-contrast.css
  public/css/dist/skins/skin-contrast.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-green.css
  public/css/dist/skins/skin-green.min.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-orange.css
  public/css/dist/skins/skin-orange.min.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-purple.css
  public/css/dist/skins/skin-purple.min.css
  public/css/dist/skins/skin-red-dark.css
  public/css/dist/skins/skin-red-dark.min.css
  public/css/dist/skins/skin-red.css
  public/css/dist/skins/skin-red.min.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/css/dist/skins/skin-yellow.css
  public/css/dist/skins/skin-yellow.min.css
  public/js/build/app.js
  public/js/build/vendor.js
  public/js/dist/all.js
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
Labels: frontend

#11139 Reduce saml debugging
  app/Http/Controllers/Auth/LoginController.php
  app/Services/Saml.php
Labels: backend

#11140 Fixed #11120 - custom fields not showing when textarea is present as field type
  resources/views/models/custom_fields_form.blade.php
Labels: frontend, backend

#11142 Fixed #11141 - accessories endpoint missing from API
  routes/api.php
Labels: backend

#11144 Added spinner onClick for file upload button on backups
  resources/views/settings/backups.blade.php
Labels: frontend, backend

#11147 FixesArgument 1 passed to App\Http\Requests\ItemImportRequest::import() must be an instance of App\Models\Import, null given
  app/Http/Controllers/Api/ImportController.php
Labels: backend

#11153 updated less files for license details to adhere to dark skin themes
  resources/assets/less/skins/skin-black-dark.less
  resources/assets/less/skins/skin-blue-dark.less
  resources/assets/less/skins/skin-green-dark.less
  resources/assets/less/skins/skin-orange-dark.less
  resources/assets/less/skins/skin-purple-dark.less
  resources/assets/less/skins/skin-red-dark.less
  resources/assets/less/skins/skin-yellow-dark.less
Labels: frontend

#11154 Fixes Username required on import process
  app/Importer/UserImporter.php
Labels: backend

#11156 Fixes error 500 on Unaccepted Assets Report
  app/Http/Controllers/ReportsController.php
Labels: backend

#11158 Run migrations after restore
  app/Http/Controllers/SettingsController.php
Labels: backend

#11152 fixes inconsistencies with links styling
  resources/assets/less/skins/skin-black.less
  resources/assets/less/skins/skin-blue.less
  resources/assets/less/skins/skin-green.less
  resources/assets/less/skins/skin-orange.less
  resources/assets/less/skins/skin-purple.less
  resources/assets/less/skins/skin-red.less
  resources/assets/less/skins/skin-yellow.less
Labels: frontend

#11160 Fixed: #11098 - Smartly overwrite fields with default values for custom fields
  resources/views/hardware/edit.blade.php
Labels: frontend, backend

#11161 Small fixes for asset tag regeneration script
  app/Console/Commands/RegenerateAssetTags.php
Labels: backend

#11167 Fixes #9019 Import page returns error 500
  app/Models/Setting.php
Labels: backend

#11171 Fixes Checkout date missing in asset delivery mail
  app/Importer/AssetImporter.php
Labels: backend

#11149 Fixed #11129 - settings treeview won't stay active.
  app/Helpers/Helper.php
  resources/views/layouts/default.blade.php
Labels: frontend, backend

#11184 Google client-side TLS auth works better with null as context(?)
  app/Models/Ldap.php
Labels: backend

#11189 Fixed bug where username wasn’t showing for regular users
  resources/views/users/view.blade.php
Labels: frontend, backend

#11191 Updated language strings from activated to able to login
  resources/lang/en/admin/users/general.php
  resources/views/users/bulk-edit.blade.php
Labels: frontend, backend

#11190 Adjust requested assets and models workflow a little bit.
  app/Models/Asset.php
  resources/views/account/requestable-assets.blade.php
  resources/views/hardware/requested.blade.php
Labels: frontend, backend

#11196 Added a simple .env checker into the upgrader
  upgrade.php
Labels: backend

#11197 Fixes #11119 - Downgraded/Removed log statements
  app/Models/Ldap.php
Labels: backend

#11198 Check for APP_ENV in upgrader
  upgrade.php
Labels: backend

#11204 Fixes #11193 File Uploads don't show target in Activity report
  app/Http/Transformers/ActionlogsTransformer.php
  resources/views/reports/activity.blade.php
Labels: frontend, backend

#11202 Starter Livewire config (for subdirectories)
  config/livewire.php
Labels: backend

#11206 Added a self-update suggestion in the upgrader
  upgrade.php
Labels: backend

#11212 Fixes Exception checkout logs require target
  app/Http/Controllers/Api/LicenseSeatsController.php
  index.html
Labels: backend, legal

#11227 Fixes #11116 Error exception in getimagesize
  app/Http/Controllers/Account/AcceptanceController.php
Labels: backend
