Repository grokability/snipe-it, pull requests merged in 2022-09, with the labels that each got.

#11790 Fixed Double login when switching users
  app/Http/Controllers/Auth/LoginController.php
Labels: backend

#11072 Try conditional formatting to support apache 2.2 and 2.4
  public/.htaccess
Labels: :sos: testers-needed

#11811 Fixed Mini quantity field values are not importing into Snipe-IT
  app/Importer/AccessoryImporter.php
  app/Importer/ConsumableImporter.php
Labels: backend, importer

#11823 Fixes depreciation calculations off
  app/Http/Transformers/DepreciationsTransformer.php
  app/Models/Depreciable.php
Labels: backend

#11824 Fixed custom asset report timeout - removed assetlog
  app/Http/Controllers/ReportsController.php
Labels: backend

#11825 Added Applecare lookup link if manufacturer is apple
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#11771 Fixed #11769: PAT Test hardcoded text
  app/Models/AssetMaintenance.php
Labels: backend

#11830 Fixed #9801 #11199 Default Values for Checkbox Field Types Unaccessible
  app/Http/Controllers/CustomFieldsController.php
  resources/views/livewire/custom-field-set-default-values-for-model.blade.php
Labels: frontend, backend, custom fields

#11835 Fixes 500 in depreciation on asset view when no purchase date
  app/Models/Depreciable.php
  resources/lang/en/general.php
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#11836 Fixed 500 error if uploaded file is missing from asset view
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#11837 Downgraded BS Tables
  package-lock.json
  package.json
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
Labels: frontend, css, skins

#11838 Larger checkbox in lists
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/mix-manifest.json
  resources/assets/less/overrides.less
Labels: frontend, css, skins

#11842 Check for `licenses.files` permissions
  app/Http/Controllers/Licenses/LicenseFilesController.php
  app/Policies/LicensePolicy.php
  app/Policies/SnipePermissionsPolicy.php
  app/Providers/AuthServiceProvider.php
  resources/lang/en/admin/licenses/message.php
  resources/views/licenses/view.blade.php
Labels: frontend, backend

#11856 Fixed Purchase date "readonly" value makes purchase date unable to be nulled in update form [sc-19540]
  resources/views/partials/forms/edit/purchase_date.blade.php
Labels: frontend, backend

#11857 Fixed #11827 Throw exception when there are no available seats for checkout.
  app/Http/Controllers/Licenses/LicenseCheckoutController.php
Labels: backend

#11877 Use BS datepicker’s built in clear button
  resources/views/accessories/checkin.blade.php
  resources/views/asset_maintenances/edit.blade.php
  resources/views/hardware/audit.blade.php
  resources/views/hardware/bulk-checkout.blade.php
  resources/views/hardware/checkout.blade.php
  resources/views/hardware/quickscan.blade.php
  resources/views/kits/checkout.blade.php
  resources/views/licenses/edit.blade.php
  resources/views/models/custom_fields_form.blade.php
  resources/views/partials/forms/edit/purchase_date.blade.php
Labels: frontend, backend, custom fields

#11878 Delete duplicate fields from the importer dropdown menu [sc-19547]
  resources/assets/js/components/importer/importer-file.vue
Labels: frontend

#11882 Upgraded fontawesome
  package-lock.json
  package.json
  public/css/dist/all.css
  public/css/webfonts/fa-brands-400.ttf
  public/css/webfonts/fa-brands-400.woff2
  public/css/webfonts/fa-regular-400.ttf
  public/css/webfonts/fa-regular-400.woff2
  public/css/webfonts/fa-solid-900.ttf
  public/css/webfonts/fa-solid-900.woff2
  public/css/webfonts/fa-v4compatibility.ttf
  public/css/webfonts/fa-v4compatibility.woff2
  public/js/build/app.js
  public/js/dist/all.js
  public/mix-manifest.json
Labels: frontend, css, skins

#11854 Fixed #11847 404 error during Import if a checkout type of location is specified and no checkout location is passed
  app/Importer/ItemImporter.php
Labels: backend, importer

#11764 Added notes to audit mail notification
  resources/views/notifications.blade.php
  resources/views/notifications/markdown/upcoming-audits.blade.php
Labels: frontend, backend

#11853 Fixes the color choice for the ldap_test_results
  resources/assets/less/skins/skin-black-dark.less
  resources/assets/less/skins/skin-blue-dark.less
  resources/assets/less/skins/skin-green-dark.less
  resources/assets/less/skins/skin-orange-dark.less
  resources/assets/less/skins/skin-purple-dark.less
  resources/assets/less/skins/skin-red-dark.less
  resources/assets/less/skins/skin-yellow-dark.less
Labels: frontend, css, skins

#11671 Fixed unit test suite that was not running, added working browser test
  TESTING.md
  docker-compose.yml
  tests/Browser/LoginTest.php
  tests/DuskTestCase.php
Labels: backend

#11872 Fixed #11871 Replacing (deprecated) patchwork/utf8 by polyfill/mbstring.
  app/Models/CustomField.php
  composer.json
Labels: backend, dependencies

#11890 Fixed #11889 - API route for status labels asset listing
  routes/api.php
Labels: backend

#11893 Fixed #11521 - Add option to switch to using status meta from status label name
  app/Http/Controllers/Api/StatuslabelsController.php
  app/Http/Controllers/SettingsController.php
  app/Http/Transformers/PieChartTransformer.php
  database/migrations/2022_09_29_040231_add_chart_type_to_settings.php
  resources/lang/en/general.php
  resources/views/dashboard.blade.php
  resources/views/settings/general.blade.php
  routes/api.php
Labels: frontend, backend, api

#11894 Added counts to Dashboard Pie Chart legends and tooltips
  app/Http/Transformers/PieChartTransformer.php
  resources/views/dashboard.blade.php
Labels: frontend, backend

#11895 Modified dashboard tooltips to add percentage as well as count
  resources/views/dashboard.blade.php
Labels: frontend, backend

#11896 Fixed depreciation API call
  app/Http/Transformers/DepreciationsTransformer.php
Labels: backend

#11901 Use `EscapeFormula()` in CSV export
  .all-contributorsrc
  .env.example
  app/Http/Controllers/ReportsController.php
  config/app.php
Labels: backend
