Repository grokability/snipe-it, pull requests merged in 2022-12, with the labels that each got.

#12194 changes the life-ring icon color with themes
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/css/dist/skins/skin-black.css
  public/css/dist/skins/skin-black.min.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-blue.css
  public/css/dist/skins/skin-blue.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-green.css
  public/css/dist/skins/skin-green.min.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-orange.css
  public/css/dist/skins/skin-orange.min.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-purple.css
  public/css/dist/skins/skin-purple.min.css
  public/css/dist/skins/skin-red-dark.css
  public/css/dist/skins/skin-red-dark.min.css
  public/css/dist/skins/skin-red.css
  public/css/dist/skins/skin-red.min.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/css/dist/skins/skin-yellow.css
  public/css/dist/skins/skin-yellow.min.css
  public/mix-manifest.json
  resources/assets/less/skins/skin-black-dark.less
  resources/assets/less/skins/skin-black.less
  resources/assets/less/skins/skin-blue-dark.less
  resources/assets/less/skins/skin-blue.less
  resources/assets/less/skins/skin-green-dark.less
  resources/assets/less/skins/skin-green.less
  resources/assets/less/skins/skin-orange-dark.less
  resources/assets/less/skins/skin-orange.less
  resources/assets/less/skins/skin-purple-dark.less
  resources/assets/less/skins/skin-purple.less
  resources/assets/less/skins/skin-red-dark.less
  resources/assets/less/skins/skin-red.less
  resources/assets/less/skins/skin-yellow-dark.less
  resources/assets/less/skins/skin-yellow.less
Labels: frontend, css, skins

#12197 Fixed #11682 Custom field type of CUSTOM REGEX defaults back to ANY on editing
  resources/views/custom_fields/fields/edit.blade.php
Labels: frontend, backend, custom fields

#12204 Fixed: curly quotes in #12182
  app/Http/Controllers/Api/UsersController.php
Labels: backend, api

#12219 Fixed typo in screen reader text
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#12134 fixes a regression with the csv assigned to fields
  app/Http/Controllers/ReportsController.php
Labels: backend

#12221 Add throttle for password reset form
  app/Http/Controllers/Auth/ResetPasswordController.php
Labels: backend

#12233 Fixed #12215 - string for “Hello, :name” in pt-BR was using `%`
  resources/lang/pt-BR/general.php
Labels: backend

#12238 Add email in assigned_to on asset transformer
  app/Http/Transformers/AssetsTransformer.php
Labels: backend

#12181 Adds asset age to asset index and asset view pages
  app/Helpers/Helper.php
  app/Http/Transformers/AssetsTransformer.php
  app/Presenters/AssetPresenter.php
  resources/lang/en/general.php
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#12247 adds serial to components tab of assets
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#12243 Created method in users.php for adding up all assigned to user and pr…
  app/Models/User.php
  resources/lang/en/admin/users/message.php
  resources/views/users/view.blade.php
Labels: frontend, backend

#12205 Adds remote field to the user importer
  app/Importer/Importer.php
  app/Importer/UserImporter.php
  public/js/dist/all.js
  resources/assets/js/components/importer/importer-file.vue
Labels: frontend, backend, importer, skins

#12251 Upgraded font awesome to 6.2.1
  package.json
  public/js/build/app.js
  public/js/dist/all.js
  public/mix-manifest.json
  resources/views/importer/import.blade.php
Labels: frontend, backend, skins

#9876 Fixed #9875: Make locations deletable for non Superuser-Accounts with FullMultipleCompanySupport
  app/Models/Company.php
Labels: backend

#12250 Fixed: Grey out pw reset button for consistency
  resources/views/users/view.blade.php
Labels: frontend, backend

#12188 Removed extra logging case that was very noisy
  app/Http/Controllers/Auth/LoginController.php
Labels: backend

#12242 Added `purchase_cost` to user's default view [sc-19680]
  app/Providers/AuthServiceProvider.php
  config/permissions.php
  resources/views/account/view-assets.blade.php
Labels: frontend, backend

#12209 Fixed 500 when downloading the Unaccepted Assets report [sc-19555]
  app/Http/Controllers/ReportsController.php
Labels: backend

#12254 Commenting on a scope in Models/Company.php
  app/Models/Company.php
Labels: backend

#12266 Fixed: There was a bug with BS tables' select-all which showed an incorrect list of elements
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#12268 Fixed: Dashboard user count scoping when full company support is enabled
  app/Http/Controllers/DashboardController.php
Labels: backend

#12264 Added: notes to the accessories tab for user detail view
  resources/views/users/view.blade.php
Labels: frontend, backend

#12090 Added: validation for department names at Company locations
  app/Models/Department.php
  app/Providers/ValidationServiceProvider.php
  resources/lang/en/admin/departments/message.php
  resources/lang/en/validation.php
Labels: backend
