Repository grokability/snipe-it, pull requests merged in 2022-04, with the labels that each got.

#10895 Security fixes to master branch
  composer.json
  composer.lock
Labels: :closed_lock_with_key: security

#10901 Fixes #10898 (invalid consumable date time info in user view)
  app/Models/User.php
  resources/views/users/view.blade.php
Labels: frontend, backend

#10903 Fixes Dates in Print All Assigned report doesn't match to history
  app/Models/User.php
  resources/views/users/print.blade.php
Labels: frontend, backend

#10889 SCIM integration using laravel-scim-server library
  app/Models/SCIMUser.php
  app/Models/SnipeSCIMConfig.php
  app/Providers/AppServiceProvider.php
  app/Providers/RouteServiceProvider.php
  composer.json
  composer.lock
  config/app.php
  config/scim.php
  public/js/snipeit.js
  resources/assets/js/components/importer/importer-file.vue
  resources/assets/js/components/importer/importer.vue
  resources/views/layouts/default.blade.php
  routes/scim.php
Labels: frontend, backend

#10902 Fixed #10892 - MySQL 8 compatibilty requires primary key
  database/migrations/2015_09_21_235926_create_custom_field_custom_fieldset.php
  database/migrations/2022_04_05_135340_add_primary_key_to_custom_fields_pivot.php
Labels: backend

#10883 Fixes Importer always update existing values develop
  app/Http/Requests/ItemImportRequest.php
  resources/assets/js/components/importer/importer-file.vue
Labels: frontend, backend

#10917 This disables the display of HTML content during exports
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#10920 Fixed #10866 - action_date for check-in not including H:i:s
  app/Http/Controllers/Assets/AssetCheckinController.php
  app/Models/Loggable.php
Labels: backend

#10919 Fixed #10866 - Checkin time always shows 12am
  app/Http/Controllers/Assets/AssetCheckinController.php
  app/Models/Loggable.php
Labels: backend

#10914 Fixes Bulk user edit not updating checked out asset locations
  app/Http/Controllers/Users/BulkUsersController.php
Labels: backend

#10913 Fixes Bulk user edit not updating checked out asset locations
  app/Http/Controllers/Users/BulkUsersController.php
Labels: backend

#10935 Backport the license index fix from Develop onto the v5 branch
  database/migrations/2022_01_10_182548_add_license_id_index_to_license_seats.php
Labels: backend

#10942 Fixes potential XSS vuln in user requestable results
  app/Http/Controllers/Api/ProfileController.php
Labels: backend

#10943 Added status_id to asset checkout API
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Requests/AssetCheckoutRequest.php
Labels: backend

#10952 fixes double updates from action log and history
  app/Observers/AssetObserver.php
Labels: backend

#10971 Escape checkout target name
  app/Http/Transformers/DepreciationReportTransformer.php
Labels: backend

#10991 Added access gate to the requested assets index
  app/Http/Controllers/Assets/AssetsController.php
Labels: backend

#10994 Fixed model export filename to use str_slug for filename for JS export (like we do elsewhere)
  resources/views/models/view.blade.php
Labels: frontend, backend

#10998 Fixes #10980 - Prevent immediate saml login after normal logout
  app/Http/Controllers/Auth/LoginController.php
  resources/views/auth/login.blade.php
Labels: frontend, backend
