Repository grokability/snipe-it, pull requests merged in 2022-08, with the labels that each got.

#11593 Added bulk edit to company view
  resources/views/companies/view.blade.php
Labels: frontend, backend

#11578 Switched to conditionally adding the nbsp; that the table needs for proper layout if cell is empty
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#11595 Fixed routes for optimize
  app/Http/Controllers/Accessories/AccessoryCheckoutController.php
  app/Http/Controllers/Assets/BulkAssetsController.php
  app/Http/Controllers/Auth/SamlController.php
  app/Http/Controllers/Consumables/ConsumableCheckoutController.php
  resources/views/accessories/view.blade.php
  resources/views/auth/two_factor.blade.php
  resources/views/components/checkin.blade.php
  resources/views/components/view.blade.php
  resources/views/consumables/view.blade.php
  resources/views/hardware/checkin.blade.php
  resources/views/hardware/view.blade.php
  resources/views/layouts/default.blade.php
  resources/views/models/view.blade.php
  resources/views/users/view.blade.php
  routes/web.php
  routes/web/accessories.php
  routes/web/components.php
  routes/web/consumables.php
  routes/web/hardware.php
  routes/web/models.php
  routes/web/users.php
Labels: frontend, backend, consumables, saml

#11597 Fixed date format for Current Date output on location print assigned
  resources/views/locations/print.blade.php
Labels: frontend, backend

#11594 Adds options to include Deleted assets to custom asset reports
  app/Http/Controllers/ReportsController.php
  resources/lang/en/general.php
  resources/views/reports/custom.blade.php
Labels: frontend, backend

#11603 Use apropiate string for license actions
  resources/views/licenses/view.blade.php
Labels: frontend, backend

#11604 Hide requested assets if the user cannot see requestable items
  resources/views/layouts/default.blade.php
Labels: frontend, backend

#11605 Disallow checkout if qty = 0
  resources/views/consumables/view.blade.php
Labels: frontend, backend, consumables

#11596 Use unique_undeleted instead of unique for custom fields
  app/Models/CustomFieldset.php
Labels: backend, custom fields

#11601 Error 404 fixed on submitting without mandatory field
  app/Http/Controllers/Assets/BulkAssetsController.php
Labels: backend

#11608 Added time diff to EOL in asset view
  app/Http/Controllers/ReportsController.php
  app/Presenters/AssetPresenter.php
  app/Presenters/DepreciationReportPresenter.php
  resources/views/hardware/view.blade.php
  resources/views/notifications/markdown/report-expiring-assets.blade.php
Labels: frontend, backend

#11609 Fixed labels on radio buttons in custom report
  resources/views/reports/custom.blade.php
Labels: frontend, backend

#11610 Added deleted at to custom report export
  app/Http/Controllers/ReportsController.php
  resources/views/reports/custom.blade.php
Labels: frontend, backend

#11611 Added configuration change to maintenance types
  app/Models/AssetMaintenance.php
  resources/lang/en/admin/asset_maintenances/general.php
  resources/views/asset_maintenances/edit.blade.php
Labels: frontend, backend

#11612 Added relations to report search
  app/Http/Controllers/Api/ReportsController.php
  app/Http/Transformers/ActionlogsTransformer.php
  app/Models/Actionlog.php
Labels: backend, api

#11615 Fix auto incrementing in CSV importer [sc-19366]
  app/Importer/AssetImporter.php
Labels: backend, importer

#11617 Fixed wrong calculation of assigned components
  app/Helpers/Helper.php
Labels: backend

#11635 Added a closing div tag around the mail text help block, this was cau…
  resources/views/settings/general.blade.php
Labels: frontend, backend

#11642 Fixes Monthly depreciation calculation if EOL is blank
  app/Http/Transformers/DepreciationReportTransformer.php
Labels: backend

#11648 Fixed the active flag to be as it was in later v5 releases
  app/Console/Commands/LdapSync.php
Labels: backend, ldap, cli / artisan

#11649 Fixed #8928 - add URL and ID to custom asset report
  app/Http/Controllers/ReportsController.php
  resources/views/reports/custom.blade.php
Labels: frontend, backend

#11650 Fixed #6877 - Added notes to consumables, components on checkout
  app/Http/Controllers/Api/ComponentsController.php
  app/Http/Controllers/Api/ConsumablesController.php
  app/Http/Controllers/Components/ComponentCheckoutController.php
  app/Http/Controllers/Consumables/ConsumableCheckoutController.php
  app/Http/Transformers/ComponentsAssetsTransformer.php
  app/Http/Transformers/ComponentsTransformer.php
  app/Models/Component.php
  app/Models/User.php
  database/migrations/2022_08_10_141328_add_notes_denorm_to_consumables_users.php
  resources/views/accessories/view.blade.php
  resources/views/components/checkout.blade.php
  resources/views/components/view.blade.php
  resources/views/consumables/checkout.blade.php
  resources/views/consumables/view.blade.php
  resources/views/users/view.blade.php
  routes/api.php
Labels: frontend, backend, consumables, api

#11660 Fixes Departments update/store to allow company and/or location ids to be null
  app/Http/Controllers/DepartmentsController.php
Labels: backend

#11663 Prevent to delete a user if still has consumables associated to them
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/Users/UsersController.php
Labels: backend, api

#11675 Revert "Prevent to delete a user if still has consumables associated to them"
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/Users/UsersController.php
Labels: backend, api

#11666 Added `null` option for `purchase_date` and `expected_checkin` dates
  app/Http/Controllers/Assets/BulkAssetsController.php
  resources/lang/en/admin/hardware/form.php
  resources/lang/en/general.php
  resources/views/hardware/bulk.blade.php
  resources/views/partials/forms/edit/location-select.blade.php
Labels: frontend, backend

#11662 Fixed #6899 Docker container's php configuration isn't congruent with snipe-it uploads setting size.
  docker/startup.sh
Labels: docker

#11676 Adds the category in the side info on Models > View
  resources/views/models/view.blade.php
Labels: frontend, backend

#11712 Fixed #11711 clearfix missing on admin settings page to prevent blanking divs
  resources/views/settings/index.blade.php
Labels: frontend, backend

#11707 Fixed #11706 Manager name
  app/Console/Commands/LdapSync.php
  app/Http/Transformers/UsersTransformer.php
Labels: backend, ldap, cli / artisan

#11705 Fixed #10565, #11086: correctly looks up Manager DN from AD Manager a…
  app/Console/Commands/LdapSync.php
Labels: backend, ldap, cli / artisan

#11703 Fixed Translation String: wrong key at request canceled message
  app/Http/Controllers/ViewAssetsController.php
Labels: backend

#11651 Fixed Search in activity report for full name in relation
  app/Models/Traits/Searchable.php
Labels: backend

#11510 Fixed #11509 allow-ldap-anonymous-bind
  app/Models/Ldap.php
Labels: backend, ldap

#11723 Fixed crash on Asset View if file doesn’t exist on server
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#11727 Updated compiled assets
  config/version.php
  public/css/build/AdminLTE.css
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/css/dist/signature-pad.min.css
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/css/dist/skins/skin-black.css
  public/css/dist/skins/skin-black.min.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-blue.css
  public/css/dist/skins/skin-blue.min.css
  public/css/dist/skins/skin-contrast.css
  public/css/dist/skins/skin-contrast.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-green.css
  public/css/dist/skins/skin-green.min.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-orange.css
  public/css/dist/skins/skin-orange.min.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-purple.css
  public/css/dist/skins/skin-purple.min.css
  public/css/dist/skins/skin-red-dark.css
  public/css/dist/skins/skin-red-dark.min.css
  public/css/dist/skins/skin-red.css
  public/css/dist/skins/skin-red.min.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/css/dist/skins/skin-yellow.css
  public/css/dist/skins/skin-yellow.min.css
  public/css/webfonts/fa-brands-400.ttf
  public/css/webfonts/fa-brands-400.woff2
  public/css/webfonts/fa-regular-400.ttf
  public/css/webfonts/fa-regular-400.woff2
  public/css/webfonts/fa-solid-900.ttf
  public/css/webfonts/fa-solid-900.woff2
  public/css/webfonts/fa-v4compatibility.ttf
  public/css/webfonts/fa-v4compatibility.woff2
  public/js/build/app.js
  public/js/build/vendor.js
  public/js/dist/all.js
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
Labels: frontend, backend, css, skins

#11724 Fixed Validation error when creating custom fields' default values
  app/Http/Controllers/AssetModelsController.php
Labels: backend

#11726 Fixed #11709 Dates in custom fields not always stored in the correct format
  resources/views/models/custom_fields_form.blade.php
  resources/views/partials/forms/edit/purchase_date.blade.php
Labels: frontend, backend, custom fields

#11728 Added style to readonly date fields
  resources/views/partials/forms/edit/purchase_date.blade.php
Labels: frontend, backend

#11729 Fixed #11708 - pre-create private_storage directories for Docker restores
  docker/startup.sh
Labels: docker

#11730 Fixed #11679 Importing Licenses - Field Mismatch
  app/Importer/Importer.php
  app/Importer/ItemImporter.php
Labels: backend, importer

#11731 Fixed #10593 - added signature column to user history
  resources/views/users/view.blade.php
Labels: frontend, backend

#11735 Fixed: Log user out of other devices when they change their password
  app/Http/Controllers/ProfileController.php
  app/Http/Kernel.php
Labels: backend

#11700 Fixed 500 error when sending unaccepted assets reminder
  app/Http/Controllers/ReportsController.php
Labels: backend

#11738 Fixed #11695 Problem with checkin all and delete user.
  app/Http/Controllers/Users/BulkUsersController.php
Labels: backend

#11737 Fixed Validation error when empty default customfield values
  app/Http/Controllers/AssetModelsController.php
Labels: backend

#11752 Fixed #11742: display correct file sizes when using S3(-like) storage
  resources/views/hardware/view.blade.php
  resources/views/licenses/view.blade.php
  resources/views/models/view.blade.php
  resources/views/users/view.blade.php
Labels: frontend, backend

#11489 Fixed the order expiring assets are listed in notifications
  app/Models/Asset.php
Labels: backend

#11661 Send notifications when Acceptance Assets actions occur [sc-9917]
  app/Http/Controllers/Account/AcceptanceController.php
  app/Models/CheckoutAcceptance.php
  app/Notifications/AcceptanceAssetAcceptedNotification.php
  app/Notifications/AcceptanceAssetDeclinedNotification.php
  resources/lang/en/mail.php
  resources/views/notifications/markdown/asset-acceptance.blade.php
Labels: frontend, backend, notifications

#11765 Increased colspan for checkboxes
  resources/views/hardware/bulk.blade.php
Labels: frontend, backend
