Repository grokability/snipe-it, pull requests merged in 2022-01, with the labels that each got.

#10480 Fixed format property on invalid custom field object when trying to edit a field that doesn't exist
  app/Http/Controllers/CustomFieldsController.php
Labels: backend

#10492 Finished localizing backup restore strings
  resources/lang/en/admin/settings/general.php
  resources/views/settings/backups.blade.php
Labels: frontend, backend

#10265 Remove old ldap
  app/Console/Commands/LdapSync.php
  app/Console/Commands/LdapSyncNg.php
  app/Http/Controllers/Api/SettingsController.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Users/LDAPImportController.php
  app/Http/Livewire/LoginForm.php
  app/Models/Ldap.php
  app/Providers/LdapServiceProvider.php
  app/Services/LdapAd.php
  app/Services/LdapAdConfiguration.php
  composer.json
  composer.lock
  config/app.php
  resources/views/livewire/login-form.blade.php
  resources/views/settings/ldap.blade.php
  routes/api.php
Labels: frontend, backend

#10494 Fixed #7824
  app/Http/Controllers/Api/LicensesController.php
  app/Http/Controllers/Licenses/LicensesController.php
  app/Models/License.php
  database/factories/LicenseFactory.php
  database/migrations/2022_01_10_182548_add_license_id_index_to_license_seats.php
Labels: backend, legal

#10491 Fixed - v6 migration licenses table issue
  database/migrations/2013_11_15_190357_create_temp_licenses_table.php
  database/migrations/2013_11_25_013244_recreate_licenses_table.php
Labels: backend

#10498 Fix access control
  app/Http/Controllers/BulkAssetModelsController.php
Labels: backend

#10449 Added #10436: Restricted Logins to SAML controlled via environment variable
  .env.example
  app/Http/Controllers/Auth/LoginController.php
  config/app.php
  resources/lang/en-GB/admin/settings/general.php
  resources/lang/en-ID/admin/settings/general.php
  resources/lang/en/admin/settings/general.php
  resources/views/settings/saml.blade.php
Labels: frontend, backend

#10496 Fixed #10089 (partially): Back to master: Added some BS tables style overrides for mobile
  resources/assets/less/overrides.less
Labels: frontend

#10502 Add new UserAccountControl to permitted UAC's for AD.
  app/Console/Commands/LdapSync.php
  app/Services/LdapAd.php
Labels: backend

#10519 Make 'pending' assets properly requestable; use requestable scope
  app/Http/Controllers/Api/AssetsController.php
  app/Models/Asset.php
Labels: backend

#10521 Fixes an issue where importer is creating duplicate asset models for Master Branch
  app/Importer/ItemImporter.php
Labels: backend

#10520 Fixes an issue where importer is creating duplicate asset models
  app/Importer/ItemImporter.php
  routes/api.php
Labels: backend

#10522 Fixes bug where the depreciation report shows assets that not depreciate
  app/Http/Controllers/Api/AssetsController.php
  resources/views/models/edit.blade.php
  routes/api.php
Labels: frontend, backend

#10523 Fixes bug where the depreciation report shows assets that not deprecate for master
  app/Http/Controllers/Api/AssetsController.php
Labels: backend

#10527 Fixes PDO exeception syntax error when Expiring Alerts Threshold is not set
  app/Models/Asset.php
  app/Models/License.php
Labels: backend, legal

#10533 Add Zip field in the User Importer [sc-18556]
  app/Importer/UserImporter.php
  resources/assets/js/components/importer/importer-file.vue
Labels: frontend, backend

#10528 Force UrlGenerator's Root URL to be the base of APP_URL unless overriden
  .env.example
  app/Providers/AppServiceProvider.php
Labels: backend

#10566 Fix #10564: Edit the route to associate custom fields with fieldsets
  routes/web/fields.php
Labels: backend

#10568 Fixes Importing licenses without product key duplicates the license for develop branch
  app/Importer/LicenseImporter.php
Labels: backend, legal

#10534 Add Zip field in the User Importer for develop [sc-18556]
  app/Importer/UserImporter.php
  resources/assets/js/components/importer/importer-file.vue
Labels: frontend, backend

#10529 Force UrlGenerator's Root URL to be the base of APP_URL unless overriden (v5)
  .env.example
  app/Providers/AppServiceProvider.php
Labels: backend

#10570 Fixes donked layout required field error depreciation [sc-17111]
  resources/views/depreciations/edit.blade.php
Labels: frontend, backend

#10569 Fixes donked layout required field error depreciation in develop[sc-17111]
  resources/views/depreciations/edit.blade.php
Labels: frontend, backend

#10567 Fixes Importing licenses without product key duplicates the license
  app/Importer/LicenseImporter.php
Labels: backend, legal

#10511 Adds audit dates in the asset importer
  app/Importer/AssetImporter.php
  app/Importer/ItemImporter.php
  resources/assets/js/components/importer/importer-file.vue
Labels: frontend, backend

#10573 Add some guardrails around very-badly formatted APP_URL settings
  app/Providers/AppServiceProvider.php
Labels: backend

#10576 Added #9576 - Lookup Asset by Custom Field via API [sc-18632]
  app/Http/Controllers/Api/AssetsController.php
Labels: backend, api
