Repository grokability/snipe-it, pull requests merged in 2022-02, with the labels that each got.

#10586 Fixes Bulk edit doesn't show in Asset's history nor Activity report [sc-16550]
  app/Http/Controllers/Assets/BulkAssetsController.php
Labels: backend

#10588 Typo found in snipeit/routes/api.php @ line 391
  routes/api.php
Labels: backend

#10591 Allow invalid app urls develop
  app/Providers/AppServiceProvider.php
Labels: backend

#10590 Fixes Bulk edit doesn't show in Asset's history nor Activity report for develop [sc-16550]
  app/Http/Controllers/Assets/BulkAssetsController.php
Labels: backend

#10574 Add some guardrails around very-badly formatted APP_URL settings
  app/Providers/AppServiceProvider.php
Labels: backend

#10592 Fixed markdown upcoming audits email table
  resources/views/notifications/markdown/upcoming-audits.blade.php
Labels: frontend, backend

#10455 Added #10454: Quick Scan Checkin
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Assets/AssetsController.php
  resources/lang/en/admin/hardware/general.php
  resources/lang/en/general.php
  resources/views/hardware/quickscan-checkin.blade.php
  resources/views/layouts/default.blade.php
  routes/api.php
  routes/web/hardware.php
Labels: frontend, backend

#10605 Fixes: Column activated cannot be null for develop [sc-18528]
  resources/views/users/edit.blade.php
Labels: frontend, backend

#10604 Fixes: Column activated cannot be null [sc-18528]
  app/Http/Controllers/Users/UsersController.php
  resources/views/users/edit.blade.php
Labels: frontend, backend

#10610 Fixes #10563 - Rework the LDAP sync command to better handle the active flag
  app/Console/Commands/LdapSync.php
  database/migrations/2015_11_08_222305_add_ldap_fields_to_settings.php
  database/migrations/2022_02_03_214958_blank_out_ldap_active_flag.php
Labels: backend

#10611 D'oh! Migration fails on empty settings table :(
  database/migrations/2022_02_03_214958_blank_out_ldap_active_flag.php
Labels: backend

#10622 Fixed Bug/sc 18678/add required field marker to default currency
  resources/views/setup/user.blade.php
Labels: frontend, backend

#10623 Fixes #10577 - Fix "secure hostnames" feature for subdirectory-based Snipe-IT installs
  app/Providers/AppServiceProvider.php
Labels: backend

#10624 (Develop) fix secure hosts in subdirectory
  app/Providers/AppServiceProvider.php
Labels: backend

#10625 Fixes #10614 Checkin/Checkout API route's broken
  routes/api.php
Labels: backend

#10630 Fix /hardware/{id}/checkin API response on error
  app/Http/Controllers/Api/AssetsController.php
Labels: backend

#10635 Fixes #10627 Inconsistencies between checkout/checkin dates on asset history and activity log
  app/Models/Loggable.php
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#10636 Fixes #10627 Inconsistencies between checkout/checkin dates on asset history and activity log for master branch
  app/Models/Loggable.php
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#10637 Alert when invalid JSON is submitted to something that wants it
  app/Exceptions/Handler.php
  app/Http/Requests/Request.php
Labels: backend

#10638 Report invalid json develop
  app/Exceptions/Handler.php
  app/Http/Requests/Request.php
Labels: backend

#10628 Fixes #10299 Default Values do not allow Checkbox/Radio Buttons
  app/Http/Controllers/AssetModelsController.php
  resources/assets/js/components/forms/asset-models/fieldset-default-values.vue
  resources/views/models/custom_fields_form.blade.php
Labels: frontend, backend

#10646 Check that the field exists before trying to detach it from the fieldset
  app/Http/Controllers/CustomFieldsController.php
Labels: backend

#10640 Fix #10552: Add checkin_at parameter to /hardware/:id/checkin API
  app/Http/Controllers/Api/AssetsController.php
Labels: backend

#10654 Fixes ErrorException: Trying to get property 'checkin_email' of non-object [sc-17568]
  app/Models/Asset.php
Labels: backend

#10657 Fixed - Check for valid user before trying to present the auditor name
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#10662 Added additional gate for selectlists
  app/Http/Controllers/Api/AssetModelsController.php
  app/Http/Controllers/Api/CategoriesController.php
  app/Http/Controllers/Api/CompaniesController.php
  app/Http/Controllers/Api/DepartmentsController.php
  app/Http/Controllers/Api/LocationsController.php
  app/Http/Controllers/Api/ManufacturersController.php
  app/Http/Controllers/Api/SuppliersController.php
  app/Providers/AuthServiceProvider.php
Labels: backend, auth, api

#10665 Adds gate to supplier
  app/Http/Controllers/SuppliersController.php
Labels: backend

#10672 Added Asset edit/delete gates to maintenances
  app/Http/Controllers/Api/AssetMaintenancesController.php
  app/Http/Controllers/AssetMaintenancesController.php
Labels: backend

#10681 Fixes 2FA cookie -> user issue
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Middleware/CheckForTwoFactor.php
Labels: backend

#10683 Adds delete endpoint for licenses
  app/Http/Controllers/Api/LicensesController.php
Labels: backend, legal

#10679 Added usleep random to forgotten password method to mitigate timing attacks
  app/Http/Controllers/Auth/ForgotPasswordController.php
Labels: backend

#10670 Fixed #10639 - incorrect linear depreciation calculation
  app/Models/Depreciable.php
Labels: backend

#10655 Fixes ErrorException: Trying to get property 'checkin_email' of non-object for develop[sc-17568]
  app/Models/Asset.php
Labels: backend

#10688 Fixes #9592 - Added unique option to custom fields
  app/Http/Controllers/CustomFieldsController.php
  app/Http/Requests/ImageUploadRequest.php
  app/Models/CustomField.php
  app/Models/CustomFieldset.php
  database/migrations/2022_02_16_152431_add_unique_constraint_to_custom_field.php
  resources/lang/en/admin/custom_fields/general.php
  resources/views/custom_fields/fields/edit.blade.php
  resources/views/custom_fields/index.blade.php
Labels: frontend, backend

#10697 Feature Save logged in user data and re-add them after restore if they don't exist [ch-17664]
  app/Http/Controllers/SettingsController.php
  resources/lang/en/admin/settings/general.php
Labels: backend

#10700 Fixes #10699: Added 2 breaks in message.blade.php
  resources/views/vendor/mail/html/message.blade.php
Labels: frontend, backend

#10691 Fixed #10690 - Initial audit date fix
  app/Http/Controllers/SettingsController.php
  resources/lang/en/admin/settings/general.php
Labels: backend

#10713 Added use statement
  app/Exceptions/Handler.php
Labels: backend

#10720 Fix cors develop
  app/Http/Kernel.php
  config/cors.php
Labels: backend

#10718 Fix CORS requests on master (option *ONE*)
  app/Http/Kernel.php
Labels: backend

#10722 Fixes Restricted Logins to SAML controlled via environment variable #10436 - applies #10449 to master
  .env.example
  app/Http/Controllers/Auth/LoginController.php
  config/app.php
  resources/lang/en/admin/settings/general.php
  resources/views/settings/saml.blade.php
Labels: frontend, backend

#10727 Fix for negative CORS/SAML interaction
  app/Http/Kernel.php
  composer.json
  composer.lock
  config/cors.php
Labels: backend

#10734 Fixed API throttling
  .env.example
  app/Exceptions/Handler.php
  app/Http/Kernel.php
  config/app.php
  routes/api.php
Labels: backend

#10735 Separate notes on assets and asset models [sc-18810]
  app/Importer/AssetImporter.php
  app/Importer/ItemImporter.php
  resources/assets/js/components/importer/importer-file.vue
Labels: frontend, backend

#10736 Separate notes on assets and asset models on master branch [sc-18810]
  app/Importer/AssetImporter.php
  app/Importer/ItemImporter.php
  resources/assets/js/components/importer/importer-file.vue
Labels: frontend, backend

#10729 Fixes 10708: removed line height of manufacturer and changed size of fa-hdd to 2x
  resources/views/hardware/view.blade.php
Labels: frontend, backend
