Repository grokability/snipe-it, pull requests merged in 2022-07, with the labels that each got.

#11436 chore: Set permissions for GitHub actions
  .github/workflows/codacy-analysis.yml
  .github/workflows/docker-alpine.yml
  .github/workflows/docker.yml
Labels: config

#11438 Revert a change in our Linear Depreciation math
  app/Models/Depreciable.php
Labels: backend

#11440 Fixed #11393 - reject acceptance if no file is present
  app/Http/Controllers/Account/AcceptanceController.php
  resources/lang/en/general.php
  resources/views/account/accept/create.blade.php
Labels: frontend, backend

#11445 Replicates #11444
  app/Http/Controllers/Account/AcceptanceController.php
Labels: backend

#11437 chore: Included githubactions in the dependabot config
  .github/dependabot.yml
Labels: config

#11453 Fixes #11452 - Asset Restore routes/buttons also asset models/users restore as well
  resources/views/partials/bootstrap-table.blade.php
  resources/views/users/view.blade.php
  routes/web/hardware.php
  routes/web/users.php
Labels: frontend, backend

#11460 Fixes #11459 Missing import for Setting model in AcceptanceController
  app/Http/Controllers/Account/AcceptanceController.php
Labels: backend

#11462 Fixed #NA: typo
  resources/lang/af/general.php
  resources/lang/am/general.php
  resources/lang/bg/general.php
  resources/lang/ca/general.php
  resources/lang/cs/general.php
  resources/lang/cy/general.php
  resources/lang/da/general.php
  resources/lang/el/general.php
  resources/lang/en-GB/general.php
  resources/lang/en-ID/general.php
  resources/lang/en/general.php
  resources/lang/es-CO/general.php
  resources/lang/es-ES/general.php
  resources/lang/es-MX/general.php
  resources/lang/es-VE/general.php
  resources/lang/et/general.php
  resources/lang/fa/general.php
  resources/lang/fi/general.php
  resources/lang/fil/general.php
  resources/lang/fr/general.php
  resources/lang/ga-IE/general.php
  resources/lang/he/general.php
  resources/lang/hr/general.php
  resources/lang/id/general.php
  resources/lang/is/general.php
  resources/lang/iu/general.php
  resources/lang/ko/general.php
  resources/lang/lt/general.php
  resources/lang/lv/general.php
  resources/lang/mi/general.php
  resources/lang/mk/general.php
  resources/lang/ml-IN/general.php
  resources/lang/mn/general.php
  resources/lang/ms/general.php
  resources/lang/pl/general.php
  resources/lang/pt-PT/general.php
  resources/lang/ro/general.php
  resources/lang/ru/general.php
  resources/lang/si-LK/general.php
  resources/lang/sl/general.php
  resources/lang/sr-CS/general.php
  resources/lang/ta/general.php
  resources/lang/tl/general.php
  resources/lang/uk/general.php
  resources/lang/ur-PK/general.php
  resources/lang/vi/general.php
  resources/lang/zh-HK/general.php
  resources/lang/zh-TW/general.php
  resources/lang/zu/general.php
Labels: backend

#11451 Fixes custom fields not populating when creating asset from asset model page
  resources/views/hardware/edit.blade.php
Labels: frontend, backend

#11471 This adds some indexes for performance on license_seats
  database/migrations/2022_07_07_010406_add_indexes_to_license_seats.php
Labels: backend

#11480 Changed model file icon
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#11484 Fixes license file(s) delete modal showing entire model data instead of just the name
  resources/views/licenses/view.blade.php
Labels: frontend, backend, legal

#11490 Fixed - print assigned sig broken
  resources/views/users/print.blade.php
Labels: frontend, backend

#11483 Fixes - migrations on restore
  app/Http/Controllers/SettingsController.php
  database/migrations/2022_03_09_001334_add_eula_to_checkout_acceptance.php
Labels: backend

#11488 adds a checkbox to exclude archived assets from custom reports
  app/Http/Controllers/ReportsController.php
  resources/lang/en/general.php
  resources/views/reports/custom.blade.php
Labels: frontend, backend

#11502 Fixes #11496 - Wrong URL generated for download of asset acceptance PDF if locale was not en
  app/Http/Transformers/ActionlogsTransformer.php
Labels: backend

#11516 Fixed #11508 - font size in alert menu
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/mix-manifest.json
  resources/assets/less/overrides.less
  resources/views/layouts/default.blade.php
Labels: frontend, backend

#11517 Changed some autolabeler and code owners
  .github/CODEOWNERS
  .github/autolabeler.yml
Labels: config

#11531 Upgraded jquery-UI
  package-lock.json
  package.json
  public/js/build/app.js
  public/js/dist/all.js
  public/mix-manifest.json
Labels: frontend, skins

#11541 Fixes #11540 - accessory api routes from get to posts
  routes/api.php
Labels: backend

#11542 Features/users checkin without delete
  app/Http/Controllers/Users/BulkUsersController.php
  resources/lang/en/admin/users/general.php
  resources/lang/en/button.php
  resources/lang/en/general.php
  resources/views/users/confirm-bulk-delete.blade.php
Labels: frontend, backend

#11551 Fixed #11549 - dark skin dropdown menu fixes
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-red-dark.css
  public/css/dist/skins/skin-red-dark.min.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/mix-manifest.json
  resources/assets/less/skins/skin-black-dark.less
  resources/assets/less/skins/skin-blue-dark.less
  resources/assets/less/skins/skin-green-dark.less
  resources/assets/less/skins/skin-orange-dark.less
  resources/assets/less/skins/skin-purple-dark.less
  resources/assets/less/skins/skin-red-dark.less
  resources/assets/less/skins/skin-yellow-dark.less
Labels: frontend, css, skins

#11547 Applies current time to checkin date
  app/Http/Controllers/Api/AssetsController.php
Labels: backend, api

#11554 Bumped packages
  composer.json
  composer.lock
Labels: dependencies

#11562 Fixed inconsistent `*_LOG_LEVEL` variables; set reasonable defaults
  .env.docker
  .env.dusk.local
  .env.example
  .env.testing
  .env.testing-ci
  app.json
  config/app.php
  config/logging.php
Labels: backend, docker
