Repository grokability/snipe-it, pull requests merged in 2022-03, with the labels that each got.

#10751 Fix for location and model drop down with granular permissions.
  app/Providers/AuthServiceProvider.php
Labels: backend

#10739 Feature: Prevent showing of double values in a checkin or checkout email
  resources/views/notifications/markdown/checkin-asset.blade.php
  resources/views/notifications/markdown/checkout-asset.blade.php
Labels: frontend, backend

#10721 Added consumables endpoint to user API
  app/Http/Controllers/Api/UsersController.php
  routes/api.php
Labels: backend

#10417 Fixes trying to get property 'id' of non-object when running develop seeders.
  database/factories/AssetFactory.php
Labels: backend

#10682 Fixed weird JSON-handling on log_meta updates
  app/Http/Transformers/ActionlogsTransformer.php
Labels: backend

#10772 Use “update” instead of edit in gate
  app/Http/Controllers/Api/AssetMaintenancesController.php
  app/Http/Controllers/AssetMaintenancesController.php
Labels: backend

#10773 Features/adds ldap import and assets count to user api
  app/Http/Controllers/Api/UsersController.php
Labels: backend

#10774 Fixed #6918 - added notes to accessories, components, consumables
  app/Http/Controllers/Accessories/AccessoriesController.php
  app/Http/Controllers/Api/AccessoriesController.php
  app/Http/Controllers/Api/ComponentsController.php
  app/Http/Controllers/Api/ConsumablesController.php
  app/Http/Controllers/Components/ComponentsController.php
  app/Http/Controllers/Consumables/ConsumablesController.php
  app/Http/Transformers/ComponentsTransformer.php
  app/Http/Transformers/ConsumablesTransformer.php
  app/Models/Accessory.php
  app/Models/Component.php
  app/Models/Consumable.php
  app/Presenters/AccessoryPresenter.php
  app/Presenters/ComponentPresenter.php
  app/Presenters/ConsumablePresenter.php
  database/migrations/2022_03_03_225655_add_notes_to_accessories.php
  database/migrations/2022_03_03_225754_add_notes_to_components.php
  database/migrations/2022_03_03_225824_add_notes_to_consumables.php
  resources/views/accessories/edit.blade.php
  resources/views/accessories/view.blade.php
  resources/views/components/edit.blade.php
  resources/views/components/view.blade.php
  resources/views/consumables/edit.blade.php
  resources/views/consumables/view.blade.php
Labels: frontend, backend

#10771 Retry fix bad metadata display
  app/Http/Transformers/ActionlogsTransformer.php
Labels: backend

#10775 Added remote checkbox to user
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/Users/UsersController.php
  app/Http/Transformers/UsersTransformer.php
  app/Models/User.php
  app/Presenters/UserPresenter.php
  database/migrations/2022_03_04_080836_add_remote_to_user.php
  resources/lang/en/admin/users/general.php
  resources/views/users/edit.blade.php
  resources/views/users/view.blade.php
Labels: frontend, backend

#10777 Add remote user setting to bulk edit
  app/Http/Controllers/Users/BulkUsersController.php
  resources/lang/en/admin/users/general.php
  resources/views/users/bulk-edit.blade.php
Labels: frontend, backend

#10776 Added trim to email and username
  app/Http/Controllers/Users/UsersController.php
  app/Models/Recipients/AdminRecipient.php
Labels: backend

#10797 Use the max_results env value in the paginator
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#10798 Added QR and alt barcode urls to asset transformer
  app/Http/Transformers/AssetsTransformer.php
Labels: backend

#10799 Check if table exists before trying to create in migrations
  database/migrations/2018_07_28_023826_create_checkout_acceptances_table.php
  database/migrations/2018_10_18_191228_add_kits_licenses_table.php
  database/migrations/2018_10_19_153910_add_kits_table.php
  database/migrations/2018_10_19_154013_add_kits_models_table.php
  database/migrations/2019_02_07_185953_add_kits_consumables_table.php
  database/migrations/2019_02_07_190030_add_kits_accessories_table.php
Labels: backend

#10033 Fixed [ch14855] - create LDAP troubleshooter
  Dockerfile
  app/Console/Commands/LdapTroubleshooter.php
Labels: backend

#10805 Fixes #8143 Date localization not work in custom fields for develop branch
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#10804 Fixes #8143 Date localization not work in custom fields
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#10806 Removed experimental feature policies
  app/Http/Middleware/SecurityHeaders.php
Labels: backend

#10767 One attempt to fix the 'datatable double-request' problem.
  resources/views/partials/bootstrap-table.blade.php
  resources/views/reports/activity.blade.php
  resources/views/reports/depreciation.blade.php
Labels: frontend, backend

#10812 Fixes Carbon\Exceptions\InvalidFormatException: DateTime::__construct(): Failed to parse time string develop
  app/Importer/AssetImporter.php
  app/Importer/LicenseImporter.php
Labels: backend, legal

#10811 Fixes Carbon\Exceptions\InvalidFormatException: DateTime::__construct(): Failed to parse time string
  app/Importer/LicenseImporter.php
Labels: backend, legal

#10728 Fixed #10191 - font color contrast on mobile menu
  package-lock.json
  public/css/dist/skins/skin-blue.css
  public/css/dist/skins/skin-blue.min.css
  resources/assets/less/skins/skin-black-dark.less
  resources/assets/less/skins/skin-black.less
  resources/assets/less/skins/skin-blue-dark.less
  resources/assets/less/skins/skin-blue.less
  resources/assets/less/skins/skin-green-dark.less
  resources/assets/less/skins/skin-green.less
  resources/assets/less/skins/skin-orange-dark.less
  resources/assets/less/skins/skin-orange.less
  resources/assets/less/skins/skin-purple-dark.less
  resources/assets/less/skins/skin-purple.less
  resources/assets/less/skins/skin-red-dark.less
  resources/assets/less/skins/skin-red.less
  resources/assets/less/skins/skin-yellow-dark.less
  resources/assets/less/skins/skin-yellow.less
Labels: frontend

#10814 Added session killer artisan command
  app/Console/Commands/KillAllSessions.php
  app/Console/Commands/RestoreFromBackup.php
Labels: backend

#10829 Added filter by status_type in StatusLabels API index endpoint
  app/Http/Controllers/Api/StatuslabelsController.php
  app/Models/Statuslabel.php
Labels: backend

#10809 Fixes Customfields with boolean format not saving [ch-9973]
  app/Models/Asset.php
  resources/views/hardware/view.blade.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#10841 Fixed #10840 - defaulting to 0 on supplier ID if no value provided
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Assets/AssetsController.php
Labels: backend

#10848 Fixed #10819 - use full url for label barcodes
  resources/views/hardware/labels.blade.php
Labels: frontend, backend

#10849 Fixes #10769 - return to Due for Audit screen after auditing
  app/Http/Controllers/Assets/AssetsController.php
Labels: backend

#10851 Fixes #10753 Licenses assigned to assets don't follow users
  app/Http/Controllers/Assets/AssetCheckinController.php
  app/Http/Controllers/Assets/AssetCheckoutController.php
Labels: backend

#10853 Fixes Customfields with boolean format not saving master[sc-9973]
  app/Models/Asset.php
  resources/views/hardware/view.blade.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#10855 Validate custom fieldset only if the asset have one
  app/Models/Asset.php
Labels: backend

#10857 Fix bs tables export options
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#10737 Fixed #7891, #3019 and #8260 [sc-15014] - added asset acceptance and signed eula as pdf
  app/Http/Controllers/Account/AcceptanceController.php
  app/Http/Controllers/ActionlogController.php
  app/Http/Controllers/Api/ReportsController.php
  app/Http/Controllers/SettingsController.php
  app/Http/Transformers/ActionlogsTransformer.php
  app/Listeners/LogListener.php
  app/Models/Actionlog.php
  composer.json
  composer.lock
  config/app.php
  database/migrations/2022_03_09_001334_add_eula_to_checkout_acceptance.php
  database/migrations/2022_03_10_175740_add_eula_to_action_logs.php
  resources/lang/en/general.php
  resources/views/account/accept/accept-accessory-eula.blade.php
  resources/views/account/accept/accept-asset-eula.blade.php
  resources/views/hardware/view.blade.php
  resources/views/partials/bootstrap-table.blade.php
  routes/web.php
Labels: frontend, backend

#10873 Don't crash JS when there are no data-export-options (as is true in Dashboard) Fixes #10872
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#10874 Fix problem with static paths
  app/Console/Commands/MoveUploadsToNewDisk.php
Labels: backend

#10850 feature: adds ldap_manager field to ldap sync
  app/Console/Commands/LdapSync.php
  app/Http/Controllers/SettingsController.php
  app/Models/Ldap.php
  database/migrations/2022_03_21_162724_adds_ldap_manager.php
  resources/lang/en/admin/settings/general.php
  resources/views/settings/ldap.blade.php
Labels: frontend, backend

#10843 [Feature] Adds CodeQL to the SDLC process
  .github/workflows/SA-codeql.yml
  public/js/plugins/chartjs/Chart.bundle.js
Labels: frontend, backend, config

#10817 Fix #10810 unaccepted assets
  app/Http/Controllers/ReportsController.php
  resources/views/reports/unaccepted_assets.blade.php
Labels: frontend, backend

#10879 Merge master back down into develop
  .all-contributorsrc
  README.md
  app/Console/Commands/MoveUploadsToNewDisk.php
  app/Console/Commands/RestoreFromBackup.php
  app/Http/Controllers/Api/StatuslabelsController.php
  app/Importer/LicenseImporter.php
  app/Models/Asset.php
  app/Models/User.php
  config/version.php
  database/migrations/2018_10_18_191228_add_kits_licenses_table.php
  database/migrations/2018_10_19_153910_add_kits_table.php
  database/migrations/2018_10_19_154013_add_kits_models_table.php
  database/migrations/2019_02_07_185953_add_kits_consumables_table.php
  database/migrations/2019_02_07_190030_add_kits_accessories_table.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend
