Repository grokability/snipe-it, pull requests merged in 2022-06, with the labels that each got.

#11233 Fixed #11232 - missing closing div
  resources/views/depreciations/edit.blade.php
Labels: frontend, backend

#11046 Added history tab to accessories
  resources/views/accessories/view.blade.php
Labels: frontend, backend

#11235 fixed issue with misplaced div
  resources/views/accessories/view.blade.php
Labels: frontend, backend

#11243 Don’t use the formatted date for diff days in audit report
  resources/views/notifications/markdown/upcoming-audits.blade.php
Labels: frontend, backend

#11244 Dropped log level to warn on SAML error
  app/Services/Saml.php
Labels: backend

#11247 Added the validation strings for user creation password options
  resources/lang/en/validation.php
Labels: backend

#11248 Updated Asset Model gate to correctly display the button on view
  resources/views/models/view.blade.php
Labels: frontend, backend

#11246 Added explicit “Example:” text in placeholders
  resources/lang/en/general.php
  resources/views/settings/ldap.blade.php
Labels: frontend, backend

#11249 Fixed crashing on date formatting helper when value is not actually a date
  app/Helpers/Helper.php
Labels: backend

#11252 Fixes/locations improvements
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/LocationsController.php
  resources/lang/en/admin/locations/general.php
  resources/views/locations/print.blade.php
  resources/views/locations/view.blade.php
Labels: frontend, backend

#11254 Fixed #11224 - only show menu options if the user is allowed
  resources/views/partials/asset-bulk-actions.blade.php
Labels: frontend, backend

#11259 Fixes some issues in the asset observer
  app/Observers/AssetObserver.php
Labels: backend

#11261 Fixed #11255 - add address 2 field to locations listing
  app/Presenters/LocationPresenter.php
Labels: backend

#11262 Fixed #11093 - Return true/false for custom fields/fieldsets required value in API
  app/Http/Transformers/CustomFieldsTransformer.php
Labels: backend

#11263 Fixes log update action even if no changes are made to assets [sc-19131]
  app/Observers/AssetObserver.php
Labels: backend

#11273 Fixes EOL field doesn't have date formatter applied
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#11276 Added new JS data attributes for assets in manufacturers
  resources/views/manufacturers/view.blade.php
Labels: frontend, backend

#10824 Fixes Accessories total quantity shows a negative number for develop branch
  app/Http/Controllers/Accessories/AccessoriesController.php
  app/Http/Controllers/Components/ComponentsController.php
  app/Http/Controllers/Consumables/ConsumablesController.php
  app/Models/Accessory.php
  app/Models/Consumable.php
Labels: backend

#11286 Fixes #11092 Add element type of customfield to API response
  app/Http/Transformers/AssetsTransformer.php
Labels: backend

#11290 Fixes observer fails when creating and assigning a new asset
  app/Observers/AssetObserver.php
Labels: backend

#11291 Fixed regression: missing restore option for assets via API
  app/Http/Controllers/Api/AssetsController.php
  routes/api.php
Labels: backend

#11264 Fixed default ldap version if not specified
  app/Http/Controllers/SettingsController.php
  app/Models/Ldap.php
Labels: backend, ldap

#11300 Fixed font-awesome leading class
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#11271 Fix typo in language files
  resources/lang/en/admin/users/general.php
Labels: backend

#10988 Ensure schedule analysis job never runs on forked repos
  .github/workflows/codacy-analysis.yml
Labels: config

#11272 Fixes #8143 Date localization not working on custom fields
  app/Http/Transformers/AssetsTransformer.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#11258 Fixed colors in light color skins
  resources/assets/less/skins/skin-blue.less
  resources/assets/less/skins/skin-green.less
  resources/assets/less/skins/skin-orange.less
  resources/assets/less/skins/skin-purple.less
  resources/assets/less/skins/skin-red.less
Labels: frontend

#11281 cleans up dark modes
  resources/assets/less/skins/skin-blue-dark.less
  resources/assets/less/skins/skin-green-dark.less
  resources/assets/less/skins/skin-orange-dark.less
  resources/assets/less/skins/skin-purple-dark.less
  resources/assets/less/skins/skin-red-dark.less
  resources/assets/less/skins/skin-yellow-dark.less
Labels: frontend

#11282 redone none dark mode yellow skin
  resources/assets/less/skins/skin-yellow.less
Labels: frontend

#11301 Added models view (and bulk edit) in category detail view
  app/Http/Controllers/Api/AssetModelsController.php
  resources/views/categories/view.blade.php
  resources/views/models/index.blade.php
  resources/views/partials/bootstrap-table.blade.php
  resources/views/partials/models-bulk-actions.blade.php
Labels: frontend, backend

#11305 Fixed #11304 Trying to access array offset on value of type null at .../Transformers/AssetsTransformer.php
  app/Http/Transformers/AssetsTransformer.php
Labels: backend

#11169 Fixes Asset location doesn't change when assigned user's location change via importer
  app/Importer/UserImporter.php
Labels: backend

#11309 Fixed SC-19104 - fixes to ldap:troubleshoot artisan command
  app/Console/Commands/LdapTroubleshooter.php
Labels: backend

#11310 Fixes #11308 - bulk edit on statuslabels detail page
  resources/views/categories/view.blade.php
  resources/views/locations/view.blade.php
  resources/views/models/view.blade.php
  resources/views/partials/bootstrap-table.blade.php
  resources/views/statuslabels/view.blade.php
Labels: frontend, backend

#11314 Fixed #11175 - Use the Deja Vu font in PDFs to be able to support Cyrillic, etc
  config/dompdf.php
  resources/views/account/accept/accept-accessory-eula.blade.php
  resources/views/account/accept/accept-asset-eula.blade.php
Labels: frontend, backend

#11313 Nicer suppliers and manufacturers UI
  app/Http/Controllers/Api/AccessoriesController.php
  app/Http/Controllers/Api/AssetMaintenancesController.php
  app/Models/AssetMaintenance.php
  app/Models/Supplier.php
  resources/views/manufacturers/view.blade.php
  resources/views/suppliers/view.blade.php
Labels: frontend, backend

#11316 Tweaked CSS for smaller padlock
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/mix-manifest.json
  resources/assets/less/overrides.less
Labels: frontend

#11315 Added fullscreen option to tables
  resources/views/accessories/index.blade.php
  resources/views/accessories/view.blade.php
  resources/views/asset_maintenances/index.blade.php
  resources/views/categories/index.blade.php
  resources/views/companies/index.blade.php
  resources/views/components/index.blade.php
  resources/views/consumables/index.blade.php
  resources/views/departments/index.blade.php
  resources/views/groups/index.blade.php
  resources/views/hardware/audit-due.blade.php
  resources/views/hardware/audit-overdue.blade.php
  resources/views/hardware/index.blade.php
  resources/views/hardware/view.blade.php
  resources/views/kits/index.blade.php
  resources/views/licenses/index.blade.php
  resources/views/licenses/view.blade.php
  resources/views/locations/index.blade.php
  resources/views/manufacturers/index.blade.php
  resources/views/manufacturers/view.blade.php
  resources/views/models/view.blade.php
  resources/views/partials/bootstrap-table.blade.php
  resources/views/statuslabels/index.blade.php
  resources/views/statuslabels/view.blade.php
  resources/views/suppliers/index.blade.php
  resources/views/suppliers/view.blade.php
  resources/views/users/index.blade.php
  resources/views/users/view.blade.php
Labels: frontend, backend, legal

#11324 Features/add badges to companies
  resources/views/companies/view.blade.php
  resources/views/licenses/view.blade.php
Labels: frontend, backend, legal

#11329 Fixed #11285 - Depreciation index table missing pagination
  app/Http/Transformers/DepreciationsTransformer.php
Labels: backend

#11352 Fixed #11335 Assets transformer date customfields issues
  app/Http/Transformers/AssetsTransformer.php
Labels: backend

#11359 Fixes issue where asset images were showing up in checkin emails
  resources/views/notifications/markdown/checkin-asset.blade.php
Labels: frontend, backend

#11365 Added missing postal code from user view
  resources/views/users/view.blade.php
Labels: frontend, backend

#11380 Fixed #11378 - Added better excel export
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#11382 Fixes check for archived setting on counts
  app/Models/Asset.php
  resources/views/categories/view.blade.php
  resources/views/companies/view.blade.php
  resources/views/dashboard.blade.php
  resources/views/locations/view.blade.php
  resources/views/manufacturers/view.blade.php
  resources/views/suppliers/view.blade.php
  resources/views/users/view.blade.php
Labels: frontend, backend

#11384 Fixed missing archived tooltip
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#11386 Small fixes to default blue
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-blue.css
  public/css/dist/skins/skin-blue.min.css
  public/css/dist/skins/skin-contrast.css
  public/css/dist/skins/skin-contrast.min.css
  public/mix-manifest.json
  resources/assets/less/overrides.less
  resources/assets/less/skins/skin-blue.less
  resources/assets/less/variables.less
  resources/views/settings/index.blade.php
Labels: frontend, backend

#11379 adds eula blade for licenses/consumables/components and fixes assigned_to for dom_pdf
  app/Http/Controllers/Account/AcceptanceController.php
  resources/views/account/accept/accept-component-eula.blade.php
  resources/views/account/accept/accept-consumable-eula.blade.php
  resources/views/account/accept/accept-license-eula.blade.php
Labels: frontend, backend

#11375 fixes dropdown column select font color in bootstrap tables
  resources/assets/less/skins/skin-black-dark.less
  resources/assets/less/skins/skin-blue-dark.less
  resources/assets/less/skins/skin-orange-dark.less
  resources/assets/less/skins/skin-purple-dark.less
  resources/assets/less/skins/skin-red-dark.less
  resources/assets/less/skins/skin-yellow-dark.less
Labels: frontend

#11383 Added created_by to users
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/Users/UsersController.php
  app/Http/Transformers/UsersTransformer.php
  app/Models/User.php
  app/Presenters/UserPresenter.php
  database/migrations/2022_06_23_164407_add_user_id_to_users.php
  resources/views/users/view.blade.php
Labels: frontend, backend

#11387 Moved the settings search box higher
  resources/views/layouts/default.blade.php
  resources/views/settings/index.blade.php
Labels: frontend, backend

#11389 Typo of 'general' was in the migration blade a few places
  resources/views/setup/migrate.blade.php
Labels: frontend, backend

#11388 Disallow purge backup deletion by default and, enable via .env
  .env.example
  app/Http/Controllers/SettingsController.php
  config/app.php
  resources/lang/en/general.php
  resources/views/settings/backups.blade.php
  resources/views/settings/index.blade.php
Labels: frontend, backend

#11370 Adds validation to custom fields' default values
  app/Http/Controllers/AssetModelsController.php
  resources/lang/en/admin/custom_fields/message.php
  resources/views/livewire/custom-field-set-default-values-for-model.blade.php
Labels: frontend, backend

#10967 Fixes #8155 - improve the workflow during asset creation
  app/Http/Controllers/Assets/AssetsController.php
  resources/lang/en/admin/hardware/form.php
  resources/views/hardware/edit.blade.php
Labels: frontend, backend

#11403 Remember the state of the disclosure triangles in Assets
  resources/views/hardware/edit.blade.php
Labels: frontend, backend

#11407 Added disclosure arrows for lesser used options on user screen
  app/Http/Controllers/Assets/AssetsController.php
  resources/views/hardware/edit.blade.php
  resources/views/users/edit.blade.php
Labels: frontend, backend

#11405 Only care about the custom field's converted name when updating the custom field itself
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Assets/AssetsController.php
  app/Http/Transformers/AssetsTransformer.php
  app/Http/Transformers/ComponentsAssetsTransformer.php
  app/Models/CustomField.php
  app/Presenters/AssetAuditPresenter.php
  app/Presenters/AssetPresenter.php
Labels: backend

#11404 Fixed custom field transliteration
  app/Console/Commands/ReEncodeCustomFieldNames.php
Labels: backend

#11413 Add index across username and deleted_at to improve performance
  database/migrations/2022_06_28_234539_add_username_index_to_users.php
Labels: backend

#11412 Added model uploads
  app/Http/Controllers/AssetModelsFilesController.php
  app/Models/AssetModel.php
  resources/lang/en/general.php
  resources/views/hardware/view.blade.php
  resources/views/models/view.blade.php
  resources/views/partials/bootstrap-table.blade.php
  routes/web/models.php
Labels: frontend, backend

#11414 Added additional search filters for location API
  app/Http/Controllers/Api/LocationsController.php
Labels: backend

#11415 Added additional filters for api indexes
  app/Http/Controllers/Api/CategoriesController.php
  app/Http/Controllers/Api/CompaniesController.php
  app/Http/Controllers/Api/ComponentsController.php
  app/Http/Controllers/Api/ConsumablesController.php
  app/Http/Controllers/Api/DepartmentsController.php
  app/Http/Controllers/Api/GroupsController.php
  app/Http/Controllers/Api/ManufacturersController.php
  app/Http/Controllers/Api/StatuslabelsController.php
  app/Http/Controllers/Api/SuppliersController.php
Labels: backend

#11416 Added personal access endpoint to API
  app/Console/Commands/GeneratePersonalAccessToken.php
  app/Http/Controllers/Api/ProfileController.php
  routes/api.php
Labels: backend

#11418 Download backup via API
  app/Http/Controllers/Api/SettingsController.php
  routes/api.php
Labels: backend

#10758 Fixes BadMethodCallException Call to undefined method App\Models\Asset::unaccepted() for master [ch-17636]
  app/Http/Controllers/ReportsController.php
Labels: backend

#9822 Fixed #9813: Duplicate function accept-asset
  app/Http/Controllers/ViewAssetsController.php
  resources/views/account/accept-asset.blade.php
  resources/views/account/accept/create.blade.php
  routes/web.php
Labels: frontend, backend

#11430 Make SCIM be more tolerant of missing fields
  app/Models/SnipeSCIMConfig.php
Labels: backend

#11427 [feature] adds button to email user list of assets from profile
  app/Http/Controllers/Users/UsersController.php
  resources/lang/en/admin/users/general.php
  resources/views/users/view.blade.php
  routes/web/users.php
Labels: frontend, backend

#11435 Added warnings for common LDAP misconfigs
  app/Http/Controllers/SettingsController.php
Labels: backend
