Repository grokability/snipe-it, pull requests merged in 2022-10, with the labels that each got.

#11906 Fixed error 500 when downloading asset acceptance report. [sc-19555]
  app/Http/Controllers/ReportsController.php
Labels: backend

#11908 Overhaul of UI for unprivileged users
  app/Http/Controllers/ProfileController.php
  app/Http/Controllers/Users/UsersController.php
  resources/lang/en/general.php
  resources/views/account/view-assets.blade.php
  routes/web.php
Labels: frontend, backend

#11924 Added autoglossonyms for locales and translations for countries
  resources/lang/en/localizations.php
  resources/macros/macros.php
Labels: backend

#11925 Fixed #11710 - Validation of checkbox data with multiple values
  resources/views/models/custom_fields_form.blade.php
Labels: frontend, backend, custom fields

#11926 Added start and end dates to users
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/Users/UsersController.php
  app/Http/Transformers/UsersTransformer.php
  app/Models/User.php
  app/Presenters/UserPresenter.php
  database/migrations/2022_10_05_163044_add_start_termination_date_to_users.php
  resources/lang/en/general.php
  resources/views/partials/forms/edit/datepicker.blade.php
  resources/views/users/edit.blade.php
  resources/views/users/view.blade.php
Labels: frontend, backend, api

#11927 Use the new scim-trace feature from our fork of laravel-scim-server lib
  composer.lock
  config/logging.php
  config/scim.php
Labels: backend, scim

#11937 Fixes the margin top adjustment for desktop
  resources/assets/less/overrides.less
Labels: frontend, css, skins

#11959 Fixed Depreciation date diff readable precision
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#11952 Added clearer LDAP activated helptext
  resources/lang/en/admin/settings/general.php
  resources/views/settings/ldap.blade.php
Labels: frontend, backend, ldap

#11960 Sets nullable attribute on validation
  app/Http/Controllers/SettingsController.php
Labels: backend

#11942 Correct comparison logic
  app/Http/Controllers/Api/LicenseSeatsController.php
Labels: backend, api

#11964 Use admin ID for audit log notification
  app/Models/Loggable.php
Labels: backend

#11834 try/catch wrap notifications on checkin/checkout
  app/Listeners/CheckoutableListener.php
Labels: backend

#11986 Fixes the calc of months and fixes typo of the word depreciation
  app/Models/Depreciable.php
Labels: backend

#11988 Fixed wrong icons for mobile view for locations listing
  resources/views/locations/view.blade.php
Labels: frontend, backend

#11995 Fixed: Okta LDAP Manager Attribute - Try to better-handle LDAP Manager settings
  app/Console/Commands/LdapSync.php
Labels: backend, ldap, cli / artisan

#12006 Added cache manager lookups in LDAP for performance boost
  app/Console/Commands/LdapSync.php
Labels: backend, ldap, cli / artisan

#12008 Added default tab to locations
  app/Http/Controllers/Assets/BulkAssetsController.php
  resources/views/locations/view.blade.php
  resources/views/partials/asset-bulk-actions.blade.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#12015 Changed button icon for importer
  resources/views/importer/import.blade.php
Labels: frontend, backend

#12030 Added externalId support to SCIM integration
  app/Models/SnipeSCIMConfig.php
  database/migrations/2022_10_25_193823_add_externalid_to_users.php
Labels: backend, scim

#12028 Fixed #12027: Add memcached php extensions to docker images
  Dockerfile
  Dockerfile.alpine
Labels: docker

#11928 Fix typo in Dockerfile.fpm-alpine
  Dockerfile.fpm-alpine
Labels: docker

#11951 adds shortcuts for listing, creating, and saving
  resources/views/accessories/index.blade.php
  resources/views/components/index.blade.php
  resources/views/consumables/index.blade.php
  resources/views/hardware/index.blade.php
  resources/views/layouts/default.blade.php
  resources/views/licenses/index.blade.php
  resources/views/partials/asset-bulk-actions.blade.php
  resources/views/partials/forms/edit/submit.blade.php
  resources/views/users/edit.blade.php
  resources/views/users/index.blade.php
Labels: frontend, backend, consumables

#12035 Features/added new tab to locations
  app/Http/Controllers/Api/LocationsController.php
  app/Http/Transformers/LocationsTransformer.php
  app/Models/Location.php
  app/Presenters/LocationPresenter.php
  resources/lang/en/admin/locations/message.php
  resources/views/locations/view.blade.php
Labels: frontend, backend, api

#12038 Added - set `expected_checkin` to `null` on user bulk checkin and delete
  app/Http/Controllers/Users/BulkUsersController.php
Labels: backend

#12040 Renamed column back to assets_count for legacy
  app/Http/Controllers/Api/LocationsController.php
  app/Http/Transformers/LocationsTransformer.php
  app/Presenters/LocationPresenter.php
Labels: backend, api

#12041 Fixed #12009 - Added ability to reflect color in sidenav if one is given
  resources/views/layouts/default.blade.php
Labels: frontend, backend

#12042 Fixed string for invalid current password
  app/Http/Controllers/ProfileController.php
Labels: backend

#11766 Fixed (?) method name?
  app/Http/Controllers/ReportsController.php
Labels: backend
