Repository grokability/snipe-it, pull requests merged in 2022-11, with the labels that each got.

#12057 Added uploads to components
  app/Http/Controllers/Api/ConsumablesController.php
  app/Http/Controllers/Consumables/ConsumablesFilesController.php
  app/Models/Consumable.php
  config/permissions.php
  resources/views/consumables/view.blade.php
  resources/views/partials/bootstrap-table.blade.php
  routes/web/consumables.php
  storage/private_uploads/consumables/.gitignore
Labels: frontend, backend, consumables, api

#12058 Added uploads to components
  app/Http/Controllers/Components/ComponentsFilesController.php
  app/Models/Component.php
  config/permissions.php
  resources/lang/en/general.php
  resources/views/components/view.blade.php
  routes/web/components.php
  storage/private_uploads/components/.gitignore
Labels: frontend, backend

#12059 Use the generic file uploads strings
  app/Http/Controllers/Consumables/ConsumablesFilesController.php
Labels: backend, consumables

#12060 Added accessories file uploads
  app/Http/Controllers/Accessories/AccessoriesFilesController.php
  app/Models/Accessory.php
  config/permissions.php
  resources/views/accessories/view.blade.php
  routes/web/accessories.php
  storage/private_uploads/accessories/.gitignore
Labels: frontend, backend

#12049 Fixed writes to the `externalId` from SCIM
  app/Models/SnipeSCIMConfig.php
  app/Models/User.php
Labels: backend, scim

#12066 Fixed - small uploads fixes
  app/Http/Controllers/Accessories/AccessoriesFilesController.php
  app/Http/Controllers/AssetModelsFilesController.php
  app/Http/Controllers/Components/ComponentsFilesController.php
  app/Http/Controllers/Consumables/ConsumablesFilesController.php
  resources/views/accessories/view.blade.php
  resources/views/components/view.blade.php
  resources/views/consumables/view.blade.php
  resources/views/models/view.blade.php
Labels: frontend, backend, consumables

#12067 Fixed model file image path/variable
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#12088 Added new SCIM env vars; and upgraded SCIM library
  .env.example
  composer.lock
  config/scim.php
Labels: backend, scim

#12105 Fixed 500 on missing license files
  resources/views/licenses/view.blade.php
Labels: frontend, backend

#12107 Fixed 500 error if model files are missing
  resources/views/models/view.blade.php
Labels: frontend, backend

#12096 Added custom field option to view assets
  app/Http/Controllers/CustomFieldsController.php
  app/Http/Controllers/ViewAssetsController.php
  app/Http/Transformers/CustomFieldsTransformer.php
  app/Models/CustomField.php
  database/migrations/2022_11_07_134348_add_display_to_user_in_custom_fields.php
  resources/lang/en/admin/custom_fields/general.php
  resources/views/account/view-assets.blade.php
  resources/views/custom_fields/fields/edit.blade.php
  resources/views/custom_fields/index.blade.php
Labels: frontend, backend, custom fields

#12106 Fix HTTP AssetTransformer to generate an empty object for missing custom fields
  app/Http/Transformers/AssetsTransformer.php
Labels: backend

#12117 Fixes PR #12106 missing slash for std class
  app/Http/Transformers/AssetsTransformer.php
Labels: backend

#12118 Allow searching firectly for asset tag and serial
  app/Http/Controllers/Api/AssetsController.php
Labels: backend, api

#12121 Replace error suppression with better logic
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#12119 Added: API endpoint to trigger a user email notification with their assigned assets
  app/Http/Controllers/Api/UsersController.php
  routes/api.php
Labels: backend, api

#12120 Added ability to include deleted items in tag search endpoint
  app/Http/Controllers/Api/AssetsController.php
Labels: backend, api

#12129 Fixed #12109 - Duplicate column on Category listing
  app/Presenters/CategoryPresenter.php
Labels: backend

#12131 Fixed 500 if `format` is not passed to the create custom field endpoint payload
  app/Http/Controllers/Api/CustomFieldsController.php
Labels: backend, custom fields, api

#12132 Handle use case where there are no custom fields for any assigned models
  app/Http/Controllers/ViewAssetsController.php
Labels: backend

#12127 Fixed #12095 - email logo still linking even if settings deny it
  resources/views/notifications/markdown/checkin-asset.blade.php
Labels: frontend, backend

#12122 fixes checkout to all description
  app/Console/Commands/CheckoutLicenseToAllUsers.php
Labels: frontend, backend, cli / artisan

#12141 Added `serial` column to the user history page
  app/Http/Transformers/ActionlogsTransformer.php
  resources/views/reports/activity.blade.php
  resources/views/users/view.blade.php
Labels: frontend, backend

#12139 Fixed #9949 - PATCH to custom fields failing on validation (alt approach to #12011)
  app/Models/CustomField.php
Labels: backend

#12148 Fix restore icon in table view
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#12157 Fixed background color for readonly date picker fields
  resources/views/partials/forms/edit/datepicker.blade.php
Labels: frontend, backend

#12165 Fixed #12046 #12137 Custom field checkboxes not holding value
  resources/views/models/custom_fields_form.blade.php
Labels: frontend, backend, custom fields

#12168 Fixed #12161 500 error when accepting assets
  app/Models/CheckoutAcceptance.php
Labels: backend

#12166 Fixed #12046 #12137 Custom field checkboxes not holding value for develop
  resources/views/models/custom_fields_form.blade.php
Labels: frontend, backend, custom fields

#12164 Fix categories view columns matching
  app/Presenters/CategoryPresenter.php
Labels: backend

#12159 Pulled in latest upstream changes for improved standards-compliance
  composer.lock
  config/scim.php
Labels: backend, scim

#12167 Fixed #11980 Submit button deactivated in Users' Bulk Checkin if no status selected
  resources/views/users/confirm-bulk-delete.blade.php
Labels: frontend, backend

#12125 Fixed #11699 and #12065 Email issues
  resources/views/vendor/mail/html/message.blade.php
  resources/views/vendor/notifications/email.blade.php
Labels: frontend, backend

#12185 Added serial number to emailed inventory report
  resources/views/notifications/markdown/user-inventory.blade.php
Labels: frontend, backend

#12187 Fixed #12133 - Added job title to header in print assets view
  resources/views/users/print.blade.php
Labels: frontend, backend

#12182 Fixed #12119 - updated user inventory language to use strings
  app/Http/Controllers/Api/UsersController.php
  resources/lang/en/admin/accessories/message.php
  resources/lang/en/admin/users/message.php
Labels: backend, api
