Repository grokability/snipe-it, pull requests merged in 2023-02, with the labels that each got.

#12438 Fixed #9694 Replace iOS "Add to homescreen icon"
  public/img/snipe-logo-bug.png
  resources/views/layouts/default.blade.php
Labels: frontend, backend

#12439 Fixed: username doubles on 'checked-out-to' column if display is resized [sc-19869], [fd-33242]
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#12429 Cherry-picked Feature: Add DB_PORT to pgsql connection
  config/database.php
Labels: backend

#12433 Fixed Invalid date value on assets acceptance mail notification
  app/Http/Controllers/Account/AcceptanceController.php
Labels: backend

#12386 Fixed #12382 - added checked out count to accessories
  app/Http/Controllers/Accessories/AccessoriesController.php
  app/Http/Controllers/Api/AccessoriesController.php
  app/Http/Transformers/AccessoriesTransformer.php
  app/Models/Accessory.php
  app/Presenters/AccessoryPresenter.php
  resources/views/accessories/edit.blade.php
  resources/views/accessories/view.blade.php
Labels: frontend, backend, api

#12409 Fixed: Checkin limit string translation for components
  resources/lang/en/admin/components/general.php
  resources/views/components/checkin.blade.php
Labels: frontend, backend

#12437 Fixed: Active Directory "not-delegated+dont-expire-password+normal-accounts" can now login
  app/Console/Commands/LdapSync.php
Labels: backend, ldap, cli / artisan

#12423 Fixed #12418 - added ability to edit custom field names via GUI
  app/Http/Controllers/Api/CustomFieldsetsController.php
  app/Http/Controllers/CustomFieldsetsController.php
  resources/lang/en/admin/custom_fields/general.php
  resources/views/custom_fields/fieldsets/edit.blade.php
  resources/views/custom_fields/index.blade.php
Labels: frontend, backend, custom fields, api

#12407 Fixed: translation for slack message notification
  app/Models/User.php
  resources/lang/en/admin/users/general.php
  resources/views/consumables/checkout.blade.php
Labels: frontend, backend, consumables, api

#12444 Fixed: Short-circuit the LDAP sync is LDAP is disabled
  app/Console/Commands/LdapSync.php
Labels: backend, ldap, cli / artisan

#12445 Added an exit for the LDAP disabled sync short-circuit
  app/Console/Commands/LdapSync.php
Labels: backend, ldap, cli / artisan

#12454 Handle missing userfiles more gracefully
  resources/lang/en/general.php
  resources/views/users/view.blade.php
Labels: frontend, backend

#12456 Fixed #12449 - Added checkout/checkin note to user history
  resources/views/users/view.blade.php
Labels: frontend, backend

#12421 Fixed: translations added for the hardware blades
  resources/lang/en/admin/hardware/general.php
  resources/lang/en/admin/models/message.php
  resources/lang/en/general.php
  resources/views/hardware/checkin.blade.php
  resources/views/hardware/checkout.blade.php
  resources/views/hardware/quickscan-checkin.blade.php
  resources/views/hardware/quickscan.blade.php
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#12457 Fixed regression in fieldset -> field association
  app/Http/Controllers/CustomFieldsetsController.php
Labels: backend, custom fields

#12459 Updated model restore route
  resources/views/models/view.blade.php
Labels: frontend, backend

#12474 Fixed mismatched field/fieldset
  app/Http/Controllers/CustomFieldsetsController.php
Labels: backend, custom fields

#12480 Fixed UI bug where download button was missing for non-images
  resources/lang/en/general.php
  resources/views/users/view.blade.php
Labels: frontend, backend

#12486 Don't auto assign feature requests to Snipe
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: config

#12478 Fixed #12064 Mail-Template missing translation strings
  app/Notifications/CurrentInventory.php
  resources/lang/en/mail.php
  resources/views/vendor/notifications/email.blade.php
Labels: frontend, backend, notifications

#12489 Improve error messaging around invalid characters in import
  app/Http/Controllers/Api/ImportController.php
Labels: backend, api

#12490 Removed "required" marker for manufacturer on asset models (since it is not actually required)
  resources/views/modals/model.blade.php
  resources/views/models/edit.blade.php
Labels: frontend, backend

#12498 Translations for the layout setup
  resources/lang/en/general.php
  resources/views/layouts/default.blade.php
  resources/views/layouts/setup.blade.php
Labels: frontend, backend

#12477 Added functionality to Apple Warranty link
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#12506 Use translation strings for importer exceptions
  app/Http/Controllers/Api/ImportController.php
  resources/lang/en/admin/hardware/message.php
Labels: backend, api

#12514 Fix asset names being removed during API checkout requests
  app/Http/Controllers/Api/AssetsController.php
Labels: backend, api

#12513 adds a red icon next to the undeployable status
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#12516 Fixed #12252 Quotes in Custom Field regex are being HTML-escaped
  app/Http/Controllers/CustomFieldsController.php
  database/migrations/2023_02_12_224353_fix_unescaped_customfields_format.php
Labels: frontend, backend, custom fields, skins

#12466 Style fixes
  .gitignore
  app/Console/Commands/CreateAdmin.php
  app/Console/Commands/LdapSync.php
  app/Http/Controllers/ModalController.php
  app/Http/Controllers/ReportsController.php
  app/Http/Controllers/SettingsController.php
  app/Http/Middleware/CheckForTwoFactor.php
  app/Http/Requests/SaveUserRequest.php
  app/Http/Transformers/AssetModelsTransformer.php
  app/Models/Asset.php
  app/Models/CustomField.php
  app/Models/Ldap.php
  app/Models/Setting.php
  app/Models/Traits/Searchable.php
  app/Models/User.php
  app/Notifications/AcceptanceAssetAcceptedNotification.php
  app/Notifications/AcceptanceAssetDeclinedNotification.php
  app/Notifications/InventoryAlert.php
  app/Notifications/SendUpcomingAuditNotification.php
  app/Notifications/WelcomeNotification.php
  app/Presenters/UserPresenter.php
  app/Services/Saml.php
  composer.json
  composer.lock
  config/insights.php
  phpstan.neon.dist
  phpstan.neon.example
  psalm.xml
  routes/api.php
  routes/console.php
  upgrade.php
Labels: backend, ldap, dependencies, saml, cli / artisan, notifications

#12517 Silence E_WARNING "exceptions"
  app/Exceptions/Handler.php
  config/logging.php
Labels: backend

#12473 Fixed ErrorException: Attempt to read property "id" on null [sc-19855]
  app/Http/Transformers/ActionlogsTransformer.php
Labels: backend

#12470 Fixed Rollbar 16883 Error: Attempt to assign property "assigned_to" on null
  app/Importer/LicenseImporter.php
Labels: backend, importer

#12408 Enforce Y-m-d as date format for date fields
  app/Models/Accessory.php
  app/Models/Asset.php
  app/Models/Component.php
  app/Models/Consumable.php
  app/Models/License.php
  app/Models/User.php
  resources/lang/en/validation.php
Labels: backend

#12446 Adds Livewire slack inputs
  app/Http/Controllers/Api/SettingsController.php
  app/Http/Controllers/SettingsController.php
  app/Http/Livewire/SlackSettingsForm.php
  app/Http/Requests/SlackSettingsRequest.php
  app/Models/Setting.php
  resources/views/livewire/slack-settings-form.blade.php
  resources/views/settings/slack.blade.php
Labels: frontend, backend, api

#12522 Fixes slack livewire translations, UI
  app/Http/Livewire/SlackSettingsForm.php
  resources/lang/en/admin/settings/message.php
  resources/views/livewire/slack-settings-form.blade.php
  resources/views/settings/slack.blade.php
Labels: frontend, backend

#12521 Fixed awkward checkout text in checkedout side panel
  resources/views/partials/assets-assigned.blade.php
Labels: frontend, backend

#12523 Fixes slack settings submit button availability
  app/Http/Livewire/SlackSettingsForm.php
  resources/views/livewire/slack-settings-form.blade.php
Labels: frontend, backend

#12524 Cleanup some small UI bugaboos (padding, etc)
  resources/views/layouts/edit-form.blade.php
  resources/views/partials/forms/edit/submit.blade.php
Labels: frontend, backend

#12422 Have acceptance result notifications adhere to alerts enabled setting
  app/Models/CheckoutAcceptance.php
  app/Notifications/AcceptanceAssetAcceptedNotification.php
  app/Notifications/AcceptanceAssetDeclinedNotification.php
Labels: backend, notifications

#12529 allows users to clear their slack settings
  app/Http/Livewire/SlackSettingsForm.php
Labels: frontend, backend

#12533 Fixed 12531 (demo): hotfix and I don’t know why this is causing problems
  app/Models/Asset.php
Labels: backend

#12545 Two more translations
  resources/lang/pl/admin/categories/message.php
  resources/lang/pl/admin/models/message.php
Labels: backend

#12525 Add libsodium shim, and mark the sodium extension as 'optional'
  composer.json
  composer.lock
  upgrade.php
Labels: backend, dependencies

#12538 Added #12532: add version endpoint
  routes/api.php
Labels: backend

#12447 FIXED: Translations on the User Creation setup page
  resources/lang/en/admin/users/general.php
  resources/views/setup/user.blade.php
Labels: frontend, backend

#12124 Adds Boolean to Users Table for Auto Assigning Licenses
  app/Console/Commands/CheckoutLicenseToAllUsers.php
  app/Http/Controllers/Users/UsersController.php
  database/migrations/2022_11_15_232525_adds_should_autoassign_bool_to_users_table.php
  resources/lang/en/admin/users/general.php
  resources/views/users/edit.blade.php
Labels: frontend, backend, cli / artisan

#11984 Correct assignedusers relation setting
  app/Models/License.php
Labels: backend

#12509 Added images to emailed user inventory report [sc-19801]
  app/Models/User.php
  resources/views/notifications/markdown/user-inventory.blade.php
Labels: frontend, backend

#12537 Fixed #12531 Expected Checkin Date on Asset Checkout throws an error
  app/Models/Asset.php
Labels: backend

#12550 Properly close tag in mail template
  resources/views/notifications/markdown/user-inventory.blade.php
Labels: frontend, backend

#12467 Fix full company scoping in user selects
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/Assets/AssetCheckoutController.php
  database/factories/SettingFactory.php
  resources/views/hardware/checkout.blade.php
  tests/Feature/Api/Users/UsersForSelectListTest.php
  tests/TestCase.php
Labels: frontend, backend, api

#12406 Added a checkbox to notate VIP status
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/Users/UsersController.php
  app/Models/User.php
  app/Presenters/UserPresenter.php
  database/migrations/2023_01_23_232933_add_vip_to_users.php
  resources/lang/en/admin/users/general.php
  resources/views/users/edit.blade.php
  resources/views/users/view.blade.php
Labels: frontend, backend, api

#12410 Paginate accessories report
  app/Http/Controllers/Api/AccessoriesController.php
  app/Http/Controllers/ReportsController.php
  resources/views/reports/accessories.blade.php
Labels: frontend, backend, api

#12556 Fix purchase date field in asset seeder
  database/factories/AssetFactory.php
Labels: backend

#12558 Fixed ErrorException: A non-numeric value encountered in app/Models/License [sc-20187]
  app/Models/License.php
Labels: backend

#12560 Pass the existing asset name to the bulk checkout form
  app/Http/Controllers/Assets/BulkAssetsController.php
Labels: backend

#12561 Fixed #12559 Unable to import Purchase Date field
  app/Importer/ItemImporter.php
Labels: backend, importer

#12572 Added max results limit to report index
  app/Http/Controllers/Api/ReportsController.php
Labels: backend, api

#12573 Added table aliases to fix ambiguous SQL clause
  app/Models/Asset.php
Labels: backend

#12574 Fixed Address in mailbox given does not comply with RFC 2822, 3.6.2. [sc-202022]
  app/Models/CheckoutAcceptance.php
Labels: backend

#12582 Adding ability to see boolean values when using normal table export
  resources/lang/en/general.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#12583 Fixed User start and end date throws validation error [sc-20228]
  app/Models/User.php
Labels: backend

#12584 Convert string to date object for formatting
  resources/views/partials/forms/edit/datepicker.blade.php
Labels: frontend, backend
