Repository grokability/snipe-it, pull requests merged in 2023-03, with the labels that each got.

#12585 Fix license seeder
  database/factories/LicenseFactory.php
Labels: backend

#12575 Fixed: TypeError: get_class(): Argument #1 ($object) must be of type object, null given
  app/Http/Controllers/Licenses/LicenseCheckinController.php
  app/Models/Loggable.php
Labels: backend

#12393 Added EOL as de-normed and sortable on assets
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Assets/AssetsController.php
  app/Http/Transformers/AssetsTransformer.php
  app/Models/Asset.php
  app/Presenters/AssetPresenter.php
  database/migrations/2023_01_21_225350_add_eol_date_on_assets_table.php
  resources/views/hardware/edit.blade.php
  resources/views/hardware/view.blade.php
  resources/views/partials/forms/edit/eol_date.blade.php
Labels: frontend, backend, :sos: testers-needed, api

#12580 Add GitHub Action to push translation sources to Crowdin
  .github/workflows/crowdin-upload.yml
Labels: config

#12586 Compiled dev assets
  config/version.php
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/mix-manifest.json
Labels: frontend, backend, css, skins

#12578 Fixed Undefined variable `$total`
  app/Http/Controllers/Api/StatuslabelsController.php
Labels: backend, api

#12589 Updated font-awesome to ^6.3.0
  package-lock.json
  package.json
  public/css/dist/all.css
  public/css/webfonts/fa-brands-400.ttf
  public/css/webfonts/fa-brands-400.woff2
  public/css/webfonts/fa-regular-400.ttf
  public/css/webfonts/fa-regular-400.woff2
  public/css/webfonts/fa-solid-900.ttf
  public/css/webfonts/fa-solid-900.woff2
  public/css/webfonts/fa-v4compatibility.ttf
  public/css/webfonts/fa-v4compatibility.woff2
  public/mix-manifest.json
Labels: frontend, css, skins

#12590 Fixes/check for array in linux setup
  app/Http/Controllers/SettingsController.php
Labels: backend

#12591 Actually display name of company in Accessories Report
  resources/views/reports/accessories.blade.php
Labels: frontend, backend

#12592 The 'download activity report' displayed the wrong value for 'admin' (fixes FD-33368)
  app/Http/Controllers/ReportsController.php
Labels: backend

#12593 Added ability to clone location
  app/Http/Controllers/LocationsController.php
  app/Http/Transformers/LocationsTransformer.php
  resources/views/locations/edit.blade.php
  routes/web.php
Labels: frontend, backend

#12602 Fixed #12601 Error checkin license seats
  app/Http/Controllers/Licenses/LicenseCheckinController.php
Labels: backend

#12610 enable sortable for ID column
  resources/views/groups/index.blade.php
Labels: frontend, backend

#12611 Fixed #10779: Add Reverse Proxy support to Pre-Flight URL check
  app/Http/Controllers/SettingsController.php
Labels: backend

#12612 Fixed #11800: Include path in the expected URL during Pre-Flight
  app/Http/Controllers/SettingsController.php
Labels: backend

#12621 Fixes depreciation model rule for months
  app/Models/Depreciation.php
Labels: backend

#12625 Suppress SCIMExceptions from cluttering up Rollbar
  app/Exceptions/Handler.php
  config/logging.php
Labels: backend

#12623 Check that the file exists before trying to stat it for filesize
  app/Http/Controllers/Api/ImportController.php
  app/Http/Controllers/Api/SettingsController.php
  resources/lang/de/general.php
Labels: backend, api

#12626 Fix seeder so assets are checked out to users
  database/factories/ActionlogFactory.php
Labels: backend

#12624 Added `vip` and `byod` to importer
  app/Http/Controllers/Api/UsersController.php
  app/Http/Transformers/UsersTransformer.php
  app/Importer/AssetImporter.php
  app/Importer/UserImporter.php
  app/Importer/import_mappings.md
  public/js/build/app.js
  public/js/dist/all.js
  public/mix-manifest.json
  resources/assets/js/components/importer/importer-file.vue
  sample_csvs/MOCK_ASSETS.csv
  sample_csvs/MOCK_USERS.csv
Labels: frontend, backend, importer, api, skins

#12628 Maintain asset name during import with checkout
  app/Importer/AssetImporter.php
Labels: backend, importer

#12631 Dynamically determine target route for expected checkin emails
  app/Models/Asset.php
  resources/views/notifications/markdown/report-expected-checkins.blade.php
Labels: frontend, backend

#12633 Fixed 500 when admin erroneously tries to upload a tiff as logo, cleaned up logo upload layout
  app/Http/Requests/ImageUploadRequest.php
  public/js/build/app.js
  public/js/dist/all.js
  public/mix-manifest.json
  resources/assets/js/snipeit.js
  resources/lang/en/general.php
  resources/views/partials/forms/edit/uploadLogo.blade.php
Labels: frontend, backend, skins

#12617 Fixed #12249: fix csv importer for serial_number field
  app/Importer/ItemImporter.php
Labels: frontend, backend, importer

#12640 Fixes unit and feature test suite
  .env.testing
  .env.testing.example
  .gitignore
  TESTING.md
  database/factories/AssetFactory.php
  database/factories/SupplierFactory.php
  phpunit.xml
  tests/Feature/Api/Users/UsersForSelectListTest.php
  tests/TestCase.php
  tests/Unit/AccessoryTest.php
  tests/Unit/AssetMaintenanceTest.php
  tests/Unit/AssetModelTest.php
  tests/Unit/AssetTest.php
  tests/Unit/BaseTest.php
  tests/Unit/CategoryTest.php
  tests/Unit/CompanyTest.php
  tests/Unit/ComponentTest.php
  tests/Unit/ConsumableTest.php
  tests/Unit/CustomFieldTest.php
  tests/Unit/DepreciationTest.php
  tests/Unit/ImporterTest.php
  tests/Unit/LocationTest.php
  tests/Unit/NotificationTest.php
  tests/Unit/PermissionsTest.php
  tests/Unit/SnipeModelTest.php
  tests/Unit/StatuslabelTest.php
  tests/Unit/UserTest.php
Labels: backend

#12648 Fixed #12647: fix translation and adds icon on property reassignable
  resources/views/licenses/view.blade.php
Labels: frontend, backend

#12638 Fixed #12635 - dashboard category should not show archived
  app/Http/Controllers/Api/CategoriesController.php
  app/Models/Category.php
  resources/views/categories/view.blade.php
  resources/views/dashboard.blade.php
Labels: frontend, backend, api

#12659 fixes alerts to notifications in notification settings
  resources/lang/en/admin/settings/general.php
Labels: backend

#12660 Bumped codacy workflow
  .github/workflows/codacy-analysis.yml
Labels: config

#12570 Adds General option to the webhooks settings
  app/Http/Livewire/SlackSettingsForm.php
  composer.json
  database/migrations/2023_02_28_173527_adds_webhook_option_to_settings_table.php
  resources/lang/en/admin/settings/general.php
  resources/lang/en/admin/settings/message.php
  resources/lang/en/general.php
  resources/views/livewire/slack-settings-form.blade.php
  resources/views/settings/index.blade.php
  resources/views/settings/slack.blade.php
Labels: frontend, backend, dependencies

#12663 fixes webhook variables to lowercase
  app/Http/Livewire/SlackSettingsForm.php
  database/migrations/2023_02_28_173527_adds_webhook_option_to_settings_table.php
  resources/lang/en/admin/settings/general.php
  resources/views/livewire/slack-settings-form.blade.php
Labels: frontend, backend

#12665 Removed loading and reduced chunking to 10
  database/migrations/2023_01_21_225350_add_eol_date_on_assets_table.php
Labels: backend

#12667 Small UI tweaks
  resources/lang/en/general.php
  resources/views/livewire/slack-settings-form.blade.php
  resources/views/settings/slack.blade.php
Labels: frontend, backend

#12599 Fixed Column not found: 1054 Unknown column '0' in 'field list' [sc-20004]
  app/Http/Controllers/Api/UsersController.php
Labels: backend, api

#12670 Catch Duplicate Headers in Asset History Import
  app/Http/Controllers/Assets/AssetsController.php
Labels: backend

#12672 Fixed Consumable Factory Seeder
  database/factories/ConsumableFactory.php
Labels: backend

#12673 Fixed Component factory
  database/factories/ComponentFactory.php
Labels: backend

#12664 The final lowercase in webhooks
  resources/views/livewire/slack-settings-form.blade.php
Labels: frontend, backend

#12668 Fixed ErrorException: Undefined array key 0 [sc-20424]
  app/Http/Controllers/ReportsController.php
Labels: backend

#12674 Fixed missing variable in Slack hook test
  app/Http/Livewire/SlackSettingsForm.php
Labels: frontend, backend

#12636 Datestamp on "Print All Assigned" generated form
  resources/lang/en/admin/users/general.php
  resources/views/users/print.blade.php
Labels: frontend, backend

#12679 Handle already-deleted license files more gracefully
  app/Http/Controllers/Licenses/LicenseFilesController.php
  resources/lang/en/general.php
Labels: backend

#12683 Fixes/additional sort
  app/Http/Controllers/Api/UsersController.php
Labels: backend, api

#12684 Added console command to normalize capitalization on names
  app/Console/Commands/NormalizeUserNames.php
Labels: backend, cli / artisan

#12685 Added user merge
  app/Http/Controllers/Users/BulkUsersController.php
  resources/lang/en/general.php
  resources/views/partials/users-bulk-actions.blade.php
  resources/views/users/confirm-merge.blade.php
  routes/web/users.php
Labels: frontend, backend

#12686 Added email and username to merge user confirmation screen
  resources/views/users/confirm-merge.blade.php
Labels: frontend, backend

#12687 Made the table wider, used icons to compact space
  resources/views/users/confirm-merge.blade.php
Labels: frontend, backend

#12689 Added password lock restriction and and uses new strings in user merge
  app/Http/Controllers/Users/BulkUsersController.php
  resources/views/users/confirm-merge.blade.php
Labels: frontend, backend

#12690 More merge-user polishing
  app/Events/UserMerged.php
  app/Http/Controllers/Users/BulkUsersController.php
  app/Listeners/LogListener.php
  app/Presenters/ActionlogPresenter.php
  resources/lang/en/general.php
  resources/views/users/confirm-merge.blade.php
  resources/views/users/view.blade.php
Labels: frontend, backend

#12691 Small cleanup for bulk delete checkin
  resources/lang/en/general.php
  resources/views/partials/asset-bulk-actions.blade.php
  resources/views/partials/users-bulk-actions.blade.php
  resources/views/users/confirm-bulk-delete.blade.php
Labels: frontend, backend

#12692 Corrected gates, added fillable
  app/Http/Controllers/Api/GroupsController.php
  app/Models/Group.php
Labels: backend, api

#12693 Updates the Gate “use” statement to be more specific
  app/Http/Controllers/Api/ProfileController.php
  app/Http/Controllers/Assets/AssetsController.php
  app/Http/Controllers/ProfileController.php
  app/Http/Middleware/CheckPermissions.php
  app/Http/Transformers/AccessoriesTransformer.php
  app/Http/Transformers/AssetMaintenancesTransformer.php
  app/Http/Transformers/AssetsTransformer.php
  app/Http/Transformers/CategoriesTransformer.php
  app/Http/Transformers/CompaniesTransformer.php
  app/Http/Transformers/ComponentsAssetsTransformer.php
  app/Http/Transformers/ComponentsTransformer.php
  app/Http/Transformers/ConsumablesTransformer.php
  app/Http/Transformers/DepartmentsTransformer.php
  app/Http/Transformers/DepreciationsTransformer.php
  app/Http/Transformers/GroupsTransformer.php
  app/Http/Transformers/LicenseSeatsTransformer.php
  app/Http/Transformers/LicensesTransformer.php
  app/Http/Transformers/ManufacturersTransformer.php
  app/Http/Transformers/PredefinedKitsTransformer.php
  app/Http/Transformers/StatuslabelsTransformer.php
  app/Http/Transformers/SuppliersTransformer.php
  app/Http/Transformers/UsersTransformer.php
Labels: backend, consumables, api

#12694 Fixed #12671: Re-enable config:cache when there's no Rollbar
  config/logging.php
Labels: backend

#12680 Clone accessories
  app/Http/Controllers/Accessories/AccessoriesController.php
  app/Http/Transformers/AccessoriesTransformer.php
  resources/lang/en/admin/accessories/general.php
  resources/views/accessories/view.blade.php
  routes/web/accessories.php
Labels: frontend, backend

#12701 Fixed #12682 - add default location to maintenance report
  app/Http/Transformers/AssetMaintenancesTransformer.php
  resources/views/reports/asset_maintenances.blade.php
Labels: frontend, backend

#12704 Added next audit date override in bulk asset edit
  app/Http/Controllers/Assets/BulkAssetsController.php
  resources/views/hardware/bulk.blade.php
Labels: frontend, backend

#12703 adds clear and save button, save button updates accordingly
  app/Http/Livewire/SlackSettingsForm.php
  resources/lang/en/admin/settings/general.php
  resources/views/livewire/slack-settings-form.blade.php
Labels: frontend, backend

#12705 Slack webhook UI tweaks, added select2
  app/Helpers/Helper.php
  app/Http/Livewire/SlackSettingsForm.php
  app/Providers/SettingsServiceProvider.php
  resources/lang/en/general.php
  resources/views/livewire/slack-settings-form.blade.php
  resources/views/partials/forms/demo-mode.blade.php
Labels: frontend, backend

#12706 Forgot the static method declaration in new isDemoMode method - derp
  app/Helpers/Helper.php
Labels: backend

#12707 Fixes back-in-time Slack v slack migration
  database/migrations/2023_03_21_215218_update_slack_setting.php
Labels: backend

#11431 [Fix / Minor Change] Asset checkinbytag now consistent with existingAPI
  app/Http/Controllers/Api/AssetsController.php
  routes/api.php
Labels: backend

#12709 Ability to remove user location from users
  app/Http/Controllers/Users/BulkUsersController.php
  resources/lang/en/general.php
  resources/views/hardware/bulk.blade.php
  resources/views/users/bulk-edit.blade.php
Labels: frontend, backend

#12708 Livewire importer without subcomponent
  app/Helpers/Helper.php
  app/Http/Controllers/ImportsController.php
  app/Http/Livewire/Importer.php
  app/Http/Transformers/AssetsTransformer.php
  app/Models/CustomField.php
  app/Providers/RouteServiceProvider.php
  public/js/build/app.js
  public/js/dist/all.js
  public/mix-manifest.json
  resources/assets/js/components/alert.vue
  resources/assets/js/components/importer/importer-errors.vue
  resources/assets/js/components/importer/importer-file.vue
  resources/assets/js/components/importer/importer.vue
  resources/assets/js/snipeit.js
  resources/assets/js/vue.js
  resources/lang/en/general.php
  resources/views/importer/import.blade.php
  resources/views/livewire/custom-field-set-default-values-for-model.blade.php
  resources/views/livewire/importer.blade.php
  resources/views/users/edit.blade.php
  routes/web.php
Labels: frontend, backend, skins

#12710 Handled a few more hard-coded strings
  app/Http/Controllers/Assets/AssetsController.php
  resources/lang/en/admin/users/general.php
  resources/lang/en/general.php
  resources/views/livewire/importer.blade.php
Labels: frontend, backend

#12669 #20178: Added Dell and Lenovo to warranty link function
  public/img/demo/manufacturers/dellicon.png
  public/img/demo/manufacturers/lenovoicon.png
  resources/lang/en/admin/hardware/general.php
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#12717 Fixes calls to changed webhook properties names
  app/Models/Setting.php
  app/Models/User.php
  app/Notifications/AuditNotification.php
  app/Notifications/CheckinAccessoryNotification.php
  app/Notifications/CheckinAssetNotification.php
  app/Notifications/CheckinLicenseSeatNotification.php
  app/Notifications/CheckoutAccessoryNotification.php
  app/Notifications/CheckoutAssetNotification.php
  app/Notifications/CheckoutConsumableNotification.php
  app/Notifications/CheckoutLicenseSeatNotification.php
  app/Notifications/RequestAssetCancelation.php
  app/Notifications/RequestAssetNotification.php
  resources/lang/en/general.php
  resources/views/accessories/checkout.blade.php
  resources/views/consumables/checkout.blade.php
  resources/views/hardware/checkout.blade.php
  resources/views/licenses/checkout.blade.php
Labels: frontend, backend, consumables, notifications

#12721 Fixes the migration of sqlite databases
  database/migrations/2021_04_14_180125_add_ids_to_tables.php
  database/migrations/2023_02_28_173527_adds_webhook_option_to_settings_table.php
Labels: backend

#12720 Fixed Undefined array key 266 rollbar 17086
  app/Helpers/Helper.php
Labels: backend

#12713 Fixed Trying to access array offset on value of type null [sc-20528]
  resources/views/notifications/markdown/report-expiring-assets.blade.php
Labels: frontend, backend

#12661 Adds translations for category types to index and edit of categories
  app/Helpers/Helper.php
  app/Http/Transformers/CategoriesTransformer.php
Labels: backend

#12728 Use single “accessory” translation
  app/Helpers/Helper.php
Labels: backend

#12729 Fixed translation string for importer
  resources/views/livewire/importer.blade.php
Labels: frontend, backend

#12732 User preflight fix translation strings w/ bad path
  resources/views/setup/user.blade.php
Labels: frontend, backend

#12743 Changed log level to debug vs info/error in the new Livewire importer
  app/Http/Livewire/Importer.php
Labels: frontend, backend

#12744 Use named route with params
  resources/views/account/requestable-assets.blade.php
Labels: frontend, backend

#12747 Pre-Flight String fixes for step 2
  resources/lang/en/general.php
  resources/views/setup/migrate.blade.php
Labels: frontend, backend

#12752 Fixed ErrorException: Attempt to read property "rtd_location_id" on null [sc-20562]
  app/Http/Controllers/Api/AssetsController.php
Labels: backend, api

#12753 Fixes/lang for group not found
  app/Http/Controllers/GroupsController.php
  resources/lang/en/admin/groups/message.php
  resources/views/groups/index.blade.php
Labels: frontend, backend

#12764 Fixes potential unwanted overwrites in asset imports
  app/Importer/AssetImporter.php
  resources/lang/en/general.php
  resources/views/livewire/importer.blade.php
Labels: frontend, backend, importer

#12758 Fixed Call to a member function present() on null [sc-20594]
  resources/views/account/accept/index.blade.php
Labels: frontend, backend

#12762 Bulk Restore from Deleted
  app/Http/Controllers/Assets/BulkAssetsController.php
  resources/lang/en/admin/hardware/form.php
  resources/lang/en/admin/hardware/message.php
  resources/views/hardware/bulk-restore.blade.php
  resources/views/hardware/index.blade.php
  resources/views/partials/asset-bulk-actions.blade.php
  routes/web/hardware.php
Labels: frontend, backend, restore

#12760 Updating Apple warranty link to match current Apple webpage
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#12763 Fixed Call to a Member Function Licenses() on null [sc-20606]
  app/Http/Controllers/Api/AssetsController.php
Labels: backend, api

#12767 Quick fix for bulk restore menu
  resources/views/partials/asset-bulk-actions.blade.php
Labels: frontend, backend
