Repository grokability/snipe-it, pull requests merged in 2023-11, with the labels that each got.

#13828 fixed ldap location sync
  app/Console/Commands/LdapSync.php
Labels: backend, ldap, cli / artisan

#13837 Added employee number to user merge screen
  resources/views/users/confirm-merge.blade.php
Labels: frontend

#13848 Fixed missing import
  app/Notifications/CheckinAssetNotification.php
Labels: backend, notifications

#13847 Removed Refresh Button on Client Tables
  resources/views/account/accept/index.blade.php
  resources/views/account/view-assets.blade.php
Labels: frontend

#13842 Fixed notes not saving to action log when licenses are checked in/out
  app/Http/Controllers/Licenses/LicenseCheckinController.php
  app/Http/Controllers/Licenses/LicenseCheckoutController.php
  tests/Feature/Checkouts/LicenseCheckoutTest.php
Labels: backend, tests

#13814 Added #13754 - asset history tab to locations view
  resources/views/locations/view.blade.php
Labels: frontend

#13769 clarifies an address column under locations
  app/Presenters/LocationPresenter.php
  resources/lang/en/admin/locations/table.php
Labels: backend, translations

#13852 Fixed URL to favicon on default blade (used in 404 messages)
  resources/views/layouts/basic.blade.php
Labels: frontend

#13857 Bug Fix: Undefined array key 266
  app/Helpers/Helper.php
  tests/Feature/Reports/CustomReportTest.php
  tests/Unit/Helpers/HelperTest.php
Labels: backend, tests

#13871 [Snyk] Security upgrade alpine from 3.17.3 to 3.17.5
  Dockerfile.alpine
Labels: docker

#13864 Fixed GitHub Action tests for v7
  .github/workflows/tests.yml
  composer.json
  composer.lock
Labels: backend, dependencies, config

#13830 Resolves Exceptions When An Array is Submitted and Exception Occurs Before Validation
  app/Exceptions/Handler.php
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Requests/StoreAssetRequest.php
  app/Models/Asset.php
  app/Providers/ValidationServiceProvider.php
  tests/Feature/Api/Assets/AssetStoreTest.php
Labels: backend, api, tests

#13831 Added multi location sync for ldap
  app/Console/Commands/LdapSync.php
  app/Http/Controllers/Users/LDAPImportController.php
  resources/views/users/ldap.blade.php
Labels: frontend, backend, ldap, cli / artisan

#13859 Fixed ErrorExemption: Attempt to read property "id" on bool [sc-23945]
  app/Importer/AssetImporter.php
Labels: backend, importer

#13680 Changed data source input to select in new label engine
  app/Http/Controllers/LabelsController.php
  app/Http/Controllers/SettingsController.php
  app/Models/Labels/FieldOption.php
  resources/views/partials/label2-field-definitions.blade.php
  resources/views/settings/labels.blade.php
Labels: frontend, backend

#13764 Fixed the `getExpiringLicenses` query
  app/Models/License.php
Labels: backend

#13878 Clarified upload error text
  resources/lang/en/general.php
Labels: translations

#13887 Fix for Unique Serial
  app/Http/Traits/UniqueSerialTrait.php
  app/Models/Asset.php
  app/Providers/ValidationServiceProvider.php
  resources/lang/en/validation.php
Labels: backend, translations

#13892 added a `empty()` around location_id to fix ldap sync bug
  app/Console/Commands/LdapSync.php
Labels: backend, ldap, cli / artisan

#13879 added user location scope
  app/Http/Controllers/Api/UsersController.php
  app/Models/User.php
Labels: backend, api

#13903 Redirect if category is missing or invalid
  app/Http/Controllers/Api/ConsumablesController.php
  app/Http/Controllers/Consumables/ConsumableCheckoutController.php
  resources/lang/en/general.php
Labels: backend, consumables, api, translations

#13898 Fixed #13850: Too few arguments to function in App\Importer\UserImporter::fetchManager()
  app/Importer/UserImporter.php
Labels: backend, importer

#13913 Fixed #13905 - Use `unique_undeleted` instead of `unique_serial`
  app/Models/Asset.php
  app/Providers/ValidationServiceProvider.php
Labels: backend

#13914 Fixed missing translation string for `validation.two_column_unique_undeleted`
  app/Providers/ValidationServiceProvider.php
  resources/lang/en/validation.php
Labels: backend, translations

#13922 Created mutator on category checkin_email
  app/Models/Category.php
Labels: backend

#13923 Quick revert for #13830
  app/Http/Controllers/Api/AssetsController.php
Labels: backend, api

#13926 Fixed issue where delete then restore could result in duplicate asset tags
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Api/ManufacturersController.php
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/AssetModelsController.php
  app/Http/Controllers/Assets/AssetsController.php
  app/Http/Controllers/ManufacturersController.php
  app/Http/Controllers/Users/UsersController.php
  app/Http/Transformers/AssetModelsTransformer.php
  app/Http/Transformers/AssetsTransformer.php
  app/Http/Transformers/UsersTransformer.php
  app/Models/AssetModel.php
  app/Models/Category.php
  app/Models/Manufacturer.php
  app/Models/User.php
  resources/lang/en/general.php
  resources/views/partials/bootstrap-table.blade.php
  routes/api.php
Labels: frontend, backend, api, translations

#13928 Fixes double logging on asset restore
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Api/ManufacturersController.php
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/AssetModelsController.php
  app/Http/Controllers/Assets/AssetsController.php
  app/Http/Controllers/ManufacturersController.php
  app/Http/Controllers/Users/UsersController.php
  app/Observers/AssetObserver.php
Labels: backend, api

#13930 Added user observer
  app/Observers/UserObserver.php
  app/Providers/AppServiceProvider.php
Labels: backend

#13931 Use updated icons for activity report
  app/Presenters/ActionlogPresenter.php
Labels: backend

#13932 Use allowlist for user observer logging
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/ProfileController.php
  app/Observers/UserObserver.php
  resources/lang/en/passwords.php
  resources/views/account/view-assets.blade.php
Labels: frontend, backend, translations

#13933 Removed extra return statement in consumables API checkout method
  app/Http/Controllers/Api/ConsumablesController.php
Labels: backend, consumables, api

#13934 Escape the asset tag before passing it to the view
  app/Http/Controllers/Assets/AssetsController.php
Labels: backend

#13940 Added location to user view assets
  resources/views/account/view-assets.blade.php
Labels: frontend

#13941 Upgraded webpack to 5.89.0
  package-lock.json
  package.json
Labels: javascript, dependencies

#13942 Updated acorn to 8.11.2
  package-lock.json
  package.json
Labels: javascript, dependencies

#13943 Upgrade alpinejs from 3.12.3 to 3.13.2 #13936
  package-lock.json
  package.json
Labels: javascript, dependencies

#13944 Upgrade jspdf-autotable from 3.5.31 to 3.7.1 #13937
  package-lock.json
  package.json
Labels: javascript, dependencies

#13945 Higher contrast on green dark skin (#13915 for develop)
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/js/dist/all-defer.js
  public/mix-manifest.json
  resources/assets/less/skins/skin-green-dark.less
Labels: frontend, javascript, css, skins

#13948 SCIM active flag must be a boolean
  app/Models/SnipeSCIMConfig.php
Labels: backend, scim

#13947 Refactored checkout for items with bad or missing category
  app/Http/Controllers/Accessories/AccessoryCheckoutController.php
  app/Http/Controllers/Components/ComponentCheckoutController.php
  app/Http/Controllers/Consumables/ConsumableCheckoutController.php
  app/Http/Controllers/Licenses/LicenseCheckoutController.php
  resources/lang/en/admin/licenses/message.php
  resources/views/licenses/checkout.blade.php
Labels: frontend, backend, consumables, translations

#13950 Check for the array key in `$activeFile->first_row` in importer
  resources/views/livewire/importer.blade.php
Labels: frontend, livewire

#13909 Hiding Order Column in Custom Fieldsets
  resources/views/custom_fields/fieldsets/view.blade.php
Labels: frontend, custom fields

#13965 Translation of No Group notice on User edit page
  resources/lang/en/admin/settings/general.php
  resources/lang/en/admin/users/table.php
  resources/views/users/edit.blade.php
Labels: frontend, translations

#13959 Fixed status and model in bulk edit
  app/Http/Controllers/Assets/BulkAssetsController.php
  app/Models/Asset.php
  resources/lang/en/general.php
  resources/views/hardware/bulk-restore.blade.php
  resources/views/hardware/bulk.blade.php
  resources/views/hardware/view.blade.php
Labels: frontend, backend, restore, translations

#13954 Fixed user total asset cost to appear conditionally
  resources/views/users/view.blade.php
Labels: frontend

#13970 Created mutator for requestable attribute
  app/Models/Asset.php
Labels: backend

#13975 Fixes CVE-2023-49316 by upgrading phpseclib/phpseclib
  composer.lock
Labels: backend, dependencies

#13978 Test ldap
  composer.json
  composer.lock
  tests/Support/Settings.php
  tests/Unit/LdapTest.php
Labels: backend, ldap, dependencies, tests
