Repository grokability/snipe-it, pull requests merged in 2023-01, with the labels that each got.

#12298 Fixed db seeder when company id is not present
  app/Providers/ValidationServiceProvider.php
Labels: backend

#12305 Fixed: Change license_seat changing method to properly 'true up' license seats
  app/Models/License.php
Labels: backend

#12306 Fixed incomplete sentence in translation file for audit interval
  resources/lang/en/admin/settings/general.php
Labels: backend

#12308 Fixed missing translation string
  app/Http/Requests/ItemImportRequest.php
  resources/lang/en/validation.php
Labels: backend

#12263 Fixed: page-break and padding at the end of document for labels
  resources/views/hardware/labels.blade.php
Labels: frontend, backend

#12315 Features/added default values to model api
  app/Http/Transformers/AssetModelsTransformer.php
Labels: backend

#12316 Chunk sync script
  app/Console/Commands/SyncAssetCounters.php
Labels: backend, cli / artisan

#12317 Truncate URL with ellipsis if too long
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/mix-manifest.json
  resources/assets/less/overrides.less
  resources/views/hardware/view.blade.php
Labels: frontend, backend, css, skins

#12325 Fixed #12288 - LDAP default group feature refactor
  app/Console/Commands/LdapSync.php
  resources/lang/en/admin/settings/general.php
  resources/views/settings/ldap.blade.php
Labels: frontend, backend, ldap, cli / artisan

#12324 Added username to display in asset listings
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#12326 The cache system in getSettings() cached values "forever." That's bad.
  app/Models/Setting.php
  app/Observers/SettingObserver.php
Labels: backend

#12327 Determine which transformer to use based on number of assets
  app/Http/Controllers/Api/AssetsController.php
Labels: backend, api

#12328 Fixed bySerial endpoint to always return a list
  app/Http/Controllers/Api/AssetsController.php
Labels: backend, api

#12330 Fixed UX issue where assets sidenav would collapse if custom status label is selected
  resources/views/layouts/default.blade.php
Labels: frontend, backend

#12329 Fixed rollbar integration if ROLLBAR_TOKEN is provided
  config/logging.php
Labels: backend

#12336 Refactor category API for fewer queries
  app/Http/Controllers/Api/CategoriesController.php
  app/Http/Transformers/CategoriesTransformer.php
  app/Models/Category.php
  resources/lang/en/admin/categories/message.php
  resources/views/categories/edit.blade.php
Labels: frontend, backend, api

#12335 Fixed #12004: Snipe-IT restore didn't work on Windows
  app/Console/Commands/RestoreFromBackup.php
Labels: backend, :sos: testers-needed, backups, restore, cli / artisan

#12352 Added South Sudan to country list
  resources/lang/en/localizations.php
Labels: backend

#12353 Only add rollbar to the logging array if the app is in production
  config/logging.php
Labels: backend

#12355 Added categories to default visiable set on asset models
  app/Presenters/AssetModelPresenter.php
Labels: backend

#12363 Fixed #12362: Bug With Passwords Including Ampersands?
  app/Notifications/WelcomeNotification.php
Labels: backend, notifications

#12364 BREAKING: Partial fix for #12356: Make 2FA sortable in user list
  app/Http/Controllers/Api/UsersController.php
  app/Http/Transformers/UsersTransformer.php
  app/Models/User.php
  app/Presenters/UserPresenter.php
Labels: backend, api

#12370 Fixed file uploads for accessories, components, and consumables
  app/Providers/AuthServiceProvider.php
  resources/views/accessories/view.blade.php
  resources/views/components/view.blade.php
  resources/views/consumables/view.blade.php
Labels: frontend, backend, consumables

#12369 Added BYOD to assets
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Assets/AssetsController.php
  app/Http/Middleware/AssetCountForSidebar.php
  app/Http/Transformers/AssetsTransformer.php
  app/Models/Asset.php
  app/Presenters/AssetPresenter.php
  database/migrations/2023_01_18_122534_add_byod_to_assets.php
  resources/lang/en/general.php
  resources/views/hardware/edit.blade.php
  resources/views/hardware/index.blade.php
  resources/views/hardware/view.blade.php
  resources/views/layouts/default.blade.php
Labels: frontend, backend, api

#12377 Fixed #12340 Deleting imported files visually drops first element in table.
  resources/views/importer/import.blade.php
Labels: frontend, backend

#12378 Allow users to set a blank asset name during checkout
  app/Models/Asset.php
Labels: backend

#12380 Updated dev assets
  public/css/build/AdminLTE.css
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/css/dist/signature-pad.min.css
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/css/dist/skins/skin-black.css
  public/css/dist/skins/skin-black.min.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-blue.css
  public/css/dist/skins/skin-blue.min.css
  public/css/dist/skins/skin-contrast.css
  public/css/dist/skins/skin-contrast.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-green.css
  public/css/dist/skins/skin-green.min.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-orange.css
  public/css/dist/skins/skin-orange.min.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-purple.css
  public/css/dist/skins/skin-purple.min.css
  public/css/dist/skins/skin-red-dark.css
  public/css/dist/skins/skin-red-dark.min.css
  public/css/dist/skins/skin-red.css
  public/css/dist/skins/skin-red.min.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/css/dist/skins/skin-yellow.css
  public/css/dist/skins/skin-yellow.min.css
  public/js/build/app.js
  public/js/build/vendor.js
  public/js/dist/all.js
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
Labels: frontend, css, skins

#12379 Fix minor visual bug on asset show page
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#12389 Fixed #12388 - Add CSS to the div to correct the weird indenting
  resources/views/livewire/custom-field-set-default-values-for-model.blade.php
Labels: frontend

#12400 Fixed "Backup before importing?" checkbox on import page
  app/Http/Controllers/Api/ImportController.php
Labels: backend, importer, api

#12398 Fixed: translations for EULA Acceptance Summary
  resources/lang/en/general.php
  resources/views/account/accept/accept-accessory-eula.blade.php
  resources/views/account/accept/accept-asset-eula.blade.php
  resources/views/account/accept/accept-component-eula.blade.php
  resources/views/account/accept/accept-consumable-eula.blade.php
  resources/views/account/accept/accept-license-eula.blade.php
Labels: frontend, backend

#12387 Updated - Refactored ImageHandler request to be more re-usable, and checkboxes with missing `minimal` class for iCheck
  app/Http/Controllers/ProfileController.php
  app/Http/Controllers/Users/UsersController.php
  app/Http/Requests/ImageUploadRequest.php
  app/Models/User.php
  resources/views/accessories/edit.blade.php
  resources/views/account/profile.blade.php
  resources/views/categories/edit.blade.php
  resources/views/companies/edit.blade.php
  resources/views/components/edit.blade.php
  resources/views/consumables/edit.blade.php
  resources/views/departments/edit.blade.php
  resources/views/hardware/edit.blade.php
  resources/views/locations/edit.blade.php
  resources/views/manufacturers/edit.blade.php
  resources/views/models/edit.blade.php
  resources/views/partials/forms/edit/image-upload.blade.php
  resources/views/suppliers/edit.blade.php
  resources/views/users/edit.blade.php
Labels: frontend, backend, consumables

#12405 Fixed buttons colors in high contrast theme
  resources/assets/less/skins/skin-contrast.less
Labels: frontend, css, skins

#12411 Resolved Rollbar error 16746 - missing array key 'extension'
  app/Console/Commands/RestoreFromBackup.php
Labels: backend, backups, restore, cli / artisan

#12341 Redo SCIM config; use latest laravel-scim-server from our fork
  app/Models/SnipeSCIMConfig.php
  composer.lock
  config/scim.php
Labels: backend, scim

#12435 Fixed the endpoint for user notification with all their assigned assets
  app/Http/Controllers/Api/UsersController.php
Labels: backend, api
