Repository grokability/snipe-it, pull requests merged in 2023-06, with the labels that each got.

#13123 fix slack channel notifications
  app/Notifications/AuditNotification.php
  app/Notifications/CheckinAccessoryNotification.php
  app/Notifications/CheckinAssetNotification.php
  app/Notifications/CheckinLicenseSeatNotification.php
  app/Notifications/CheckoutAccessoryNotification.php
  app/Notifications/CheckoutAssetNotification.php
  app/Notifications/CheckoutConsumableNotification.php
  app/Notifications/CheckoutLicenseSeatNotification.php
  app/Notifications/RequestAssetCancelation.php
  app/Notifications/RequestAssetNotification.php
Labels: backend, notifications

#13139 Updated webpack, added new dev assets
  package-lock.json
  package.json
  public/js/build/app.js
  public/js/dist/all.js
  public/mix-manifest.json
Labels: frontend, javascript, dependencies, skins

#13143 Fixed #13129: Add missing LDAP lib required for LDAPS support
  Dockerfile
Labels: docker

#13041 Refactor importer for localization
  app/Http/Livewire/Importer.php
  app/Importer/AssetImporter.php
  app/Importer/Importer.php
  app/Importer/ItemImporter.php
  app/Importer/UserImporter.php
  app/Importer/import_mappings.md
  resources/lang/en/general.php
  resources/views/livewire/importer.blade.php
  sample_csvs/MOCK_ACCESSORIES.csv
  sample_csvs/MOCK_ASSETS.csv
  sample_csvs/MOCK_CONSUMABLES.csv
  sample_csvs/MOCK_USERS.csv
  sample_csvs/accessories-sample.csv
  sample_csvs/assets-sample-BAD.csv
  sample_csvs/assets-sample-BLANKS.csv
  sample_csvs/assets-sample.csv
  sample_csvs/consumables-sample.csv
  sample_csvs/licenses-sample.csv
  sample_csvs/locations-sample.csv
  sample_csvs/users-sample.csv
Labels: frontend, backend, consumables, importer, livewire, translations

#13158 Added warranty confirmation to asset maintenance table
  app/Http/Controllers/Api/AssetMaintenancesController.php
  app/Http/Transformers/AssetMaintenancesTransformer.php
  app/Presenters/AssetMaintenancesPresenter.php
  resources/views/reports/asset_maintenances.blade.php
Labels: frontend, backend, api

#13093 feature: Added asset_tag column in requestable assets page
  resources/views/account/requestable-assets.blade.php
Labels: frontend

#13171 Accept user ID as authoratative field for updates
  app/Http/Livewire/Importer.php
  app/Importer/UserImporter.php
Labels: backend, importer, livewire

#13159 fixed audit log image not appearing
  app/Presenters/AssetAuditPresenter.php
  resources/views/partials/bootstrap-table.blade.php
  resources/views/reports/audit.blade.php
Labels: frontend, backend

#13186 Moved logic for tighter constraints when ids are passed
  app/Http/Controllers/Api/AssetsController.php
Labels: backend, api

#13196 Fixed issue when importing Assets and no status labels exists [sc-23359]
  app/Importer/AssetImporter.php
Labels: backend, importer

#13200 Set table alias for model number sort scope
  app/Models/Asset.php
Labels: backend

#13220 Add missing relationship check in Asset Transformer
  app/Http/Transformers/AssetsTransformer.php
Labels: backend

#13216 Fix translation string in user importer
  resources/lang/en/general.php
Labels: translations

#13207 adds half_year fix from jdickerson71388
  app/Models/Depreciable.php
Labels: backend

#13045 Checkin/out info on side bar
  resources/lang/en/admin/hardware/general.php
  resources/views/hardware/view.blade.php
Labels: frontend, translations

#13223 Delete notes column map from assets importer
  app/Http/Livewire/Importer.php
Labels: backend, importer, livewire

#13227 More reshuffling of scopes in assets API
  app/Http/Controllers/Api/AssetsController.php
Labels: backend, api

#13222 Fixed #13213 - Use the Helper::parseEscapedMarkedown in notes
  app/Http/Transformers/AccessoriesTransformer.php
  app/Http/Transformers/ActionlogsTransformer.php
  app/Http/Transformers/AssetMaintenancesTransformer.php
  app/Http/Transformers/AssetModelsTransformer.php
  app/Http/Transformers/AssetsTransformer.php
  app/Http/Transformers/ComponentsTransformer.php
  app/Http/Transformers/ConsumablesTransformer.php
  app/Http/Transformers/LicensesTransformer.php
  app/Http/Transformers/SuppliersTransformer.php
  app/Http/Transformers/UsersTransformer.php
Labels: backend, consumables

#13219 Cancel requested assets without checkin/out [ch-17606]
  app/Http/Controllers/ViewAssetsController.php
  app/Models/Requestable.php
  resources/lang/en/general.php
  resources/views/hardware/requested.blade.php
  routes/web.php
Labels: frontend, backend, translations

#13228 Use proper alias for table scope
  app/Models/Asset.php
Labels: backend

#13229 fixed custom fields labels being unreadable
  resources/assets/less/skins/skin-yellow-dark.less
Labels: frontend, css, skins

#13230 Fixed windows backup filename - swapped colon in timestamp to hyphen to handle windows filesystems
  app/Http/Controllers/SettingsController.php
Labels: backend

#13231 Redirect if the license can’t be found
  app/Http/Controllers/Licenses/LicenseCheckoutController.php
Labels: backend

#13232 fixed barcode and info from overlapping
  resources/views/hardware/labels.blade.php
Labels: frontend
