Repository grokability/snipe-it, pull requests merged in 2023-10, with the labels that each got.

#13585 Standardize Asset EOL Date
  app/Http/Controllers/AssetModelsController.php
  app/Http/Controllers/Assets/AssetsController.php
  app/Importer/AssetImporter.php
  app/Importer/ItemImporter.php
  app/Models/Asset.php
  app/Observers/AssetObserver.php
  app/Presenters/AssetPresenter.php
  database/factories/AssetFactory.php
  database/migrations/2023_07_13_052204_denormalized_eol_and_add_column_for_explicit_date_to_assets.php
  resources/views/hardware/view.blade.php
  resources/views/partials/forms/edit/eol_date.blade.php
  sample_csvs/assets-sample.csv
Labels: frontend, backend, importer, livewire

#13694 Logs non-compliant barcode error as debug message
  app/Models/Labels/Label.php
Labels: backend

#13695 Log non-compliant barcode error as debug message
  app/Models/Labels/Label.php
Labels: backend

#13696 Fixed potential call to a member function toArray() on null
  app/Models/Labels/Field.php
Labels: backend

#13713 [Snyk] Security upgrade css-loader from 4.3.0 to 5.0.0 #13685
  package-lock.json
  package.json
Labels: javascript, dependencies

#13693 added proper margin-top to sidebar menu on bigger resolutions
  resources/assets/less/overrides.less
Labels: frontend, css, skins

#13704 Added a check-in button on components tab of Asset view
  app/Http/Controllers/Components/ComponentCheckinController.php
  resources/views/components/checkin.blade.php
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#13720 Fixed missing escaping asset history old/new values
  app/Http/Transformers/ActionlogsTransformer.php
Labels: backend

#13726 Added tighter controls for matching log ID and item_id
  app/Http/Controllers/Accessories/AccessoriesFilesController.php
  app/Http/Controllers/Assets/AssetFilesController.php
  app/Http/Controllers/Consumables/ConsumablesFilesController.php
  app/Http/Controllers/Licenses/LicenseFilesController.php
  app/Http/Controllers/Users/UserFilesController.php
  resources/lang/en/admin/users/message.php
Labels: backend, consumables, translations

#13727 Set resend acceptance to POST
  app/Http/Controllers/ReportsController.php
  resources/views/reports/unaccepted_assets.blade.php
  routes/web.php
Labels: frontend, backend

#13728 Fixes qty remaining requirements for component checkout via API
  .all-contributorsrc
  README.md
  app/Http/Controllers/Api/ComponentsController.php
Labels: backend, api

#13734 Fixed the storing of group permissions when creating via API
  app/Http/Controllers/Api/GroupsController.php
  tests/Feature/Api/Groups/GroupStoreTest.php
Labels: backend, api, tests

#13748 Fixed #13723 - race condition on asset observer for older migration
  app/Observers/AssetObserver.php
  database/migrations/2023_01_21_225350_add_eol_date_on_assets_table.php
  database/migrations/2023_07_13_052204_denormalized_eol_and_add_column_for_explicit_date_to_assets.php
Labels: backend

#13749 Handle case where value is deleted in history
  app/Http/Transformers/ActionlogsTransformer.php
  app/Models/Asset.php
Labels: backend

#13753 Check that the location is valid before debugging
  app/Console/Commands/LdapSync.php
Labels: backend, ldap, cli / artisan

#13756 Fixed #13652 - Labels Using Wrong Logo
  app/Models/Setting.php
  app/View/Label.php
Labels: backend

#13757 Fixed RB-17334 - ErrorException: Undefined variable $user_formatted_array
  app/Importer/Importer.php
Labels: backend, importer

#13759 Check for true/false explicitly on api table view
  resources/views/manufacturers/index.blade.php
Labels: frontend

#13761 Check for valid date in custom report
  app/Http/Controllers/ReportsController.php
  app/Http/Requests/CustomAssetReportRequest.php
  resources/views/reports/custom.blade.php
Labels: frontend, backend

#13762 Make sure order number is not an array
  app/Http/Controllers/Api/AssetsController.php
  resources/views/hardware/index.blade.php
Labels: frontend, backend, api

#13763 fixed the bulk edit button on Asset tab
  resources/views/hardware/view.blade.php
Labels: frontend

#13758 Fixed ErrorException: Array to String Conversion rb17355
  app/Http/Controllers/Api/AssetsController.php
  app/Models/Asset.php
  app/Models/CustomFieldset.php
  app/Providers/ValidationServiceProvider.php
  resources/lang/en/validation.php
Labels: backend, custom fields, api, translations

#13778 [Improvement] Dashboard
  resources/views/dashboard.blade.php
Labels: frontend

#13777 [FIX] Custom report - date fields error
  app/Http/Requests/CustomAssetReportRequest.php
Labels: backend

#13787 Fixed ErrorException: Undefined array key in importer blade [sc-23864]
  resources/lang/en/help.php
  resources/views/livewire/importer.blade.php
Labels: frontend, livewire, translations

#13584 added an option to bulk edit location & fixed location bug
  app/Http/Controllers/Assets/BulkAssetsController.php
  resources/lang/en/admin/hardware/form.php
  resources/views/hardware/bulk.blade.php
Labels: frontend, backend, translations

#13796 Added optional custom fields to requestable assets page
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Api/ProfileController.php
  app/Http/Controllers/CustomFieldsController.php
  app/Http/Transformers/AssetsTransformer.php
  app/Models/Asset.php
  app/Models/CustomField.php
  database/migrations/2023_10_25_064324_add_show_in_requestable_to_custom_fields.php
  resources/lang/en/admin/custom_fields/general.php
  resources/views/account/requestable-assets.blade.php
  resources/views/account/requested.blade.php
  resources/views/custom_fields/fields/edit.blade.php
  resources/views/custom_fields/index.blade.php
Labels: frontend, backend, custom fields, api, translations

#13799 Fixed #13795 Unlogged checkin action post updating the username of an asset through the CSV import
  app/Importer/AssetImporter.php
Labels: backend, importer

#13776 [FIX and improvements] EOL rate and EOL date
  app/Http/Controllers/AssetModelsController.php
  app/Http/Controllers/Assets/AssetsController.php
  app/Http/Transformers/AssetsTransformer.php
  app/Observers/AssetObserver.php
  app/Presenters/AssetModelPresenter.php
  app/Presenters/AssetPresenter.php
  resources/views/hardware/view.blade.php
  resources/views/partials/forms/edit/eol_date.blade.php
Labels: frontend, backend

#13800 Fixed FD-38641 - Bulk asset edit unable to update model_id, misc other bugs
  app/Http/Controllers/Assets/BulkAssetsController.php
  app/Http/Transformers/ActionlogsTransformer.php
  app/Observers/AssetObserver.php
  database/factories/ActionlogFactory.php
  database/factories/CustomFieldFactory.php
  database/seeders/CustomFieldSeeder.php
  database/seeders/DatabaseSeeder.php
  resources/lang/en/general.php
  resources/views/custom_fields/index.blade.php
  resources/views/hardware/bulk.blade.php
  resources/views/models/custom_fields_form_bulk_edit.blade.php
  resources/views/notifications.blade.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend, custom fields, translations, tests

#13802 Fixes EOL on Custom Report
  app/Http/Controllers/ReportsController.php
Labels: backend

#13803 Added User Phone & Address Fields to Custom Asset Report
  app/Http/Controllers/ReportsController.php
  resources/views/reports/custom.blade.php
Labels: frontend, backend

#13809 Added min_amt value to model detail page
  resources/views/models/view.blade.php
Labels: frontend

#13810 Fixed #11179: APP_FORCE_TLS is missing from the example .env.docker
  .env.docker
Labels: docker

#13731 Added trim to import values
  app/Importer/AccessoryImporter.php
  app/Importer/AssetImporter.php
  app/Importer/ComponentImporter.php
  app/Importer/ConsumableImporter.php
  app/Importer/ItemImporter.php
  app/Importer/LicenseImporter.php
  app/Importer/LocationImporter.php
  app/Importer/UserImporter.php
Labels: backend, importer

#13811 add missing translation string
  resources/lang/en/admin/users/message.php
Labels: translations

#13815 Add additional fields to Download All in Activity Report
  app/Http/Controllers/ReportsController.php
Labels: backend

#13817 Added checkboxes to intentionally remove field values in bulk user edit
  app/Http/Controllers/Users/BulkUsersController.php
  resources/views/users/bulk-edit.blade.php
Labels: frontend, backend

#13818 Fixed validation handling on backup uploads
  app/Http/Controllers/SettingsController.php
  resources/views/settings/backups.blade.php
Labels: frontend, backend, backups

#13819 Check that the category exists on user print page
  resources/views/users/print.blade.php
Labels: frontend

#13820 Fixed Attempt to read property fields on null [sc-23903]
  app/Models/Asset.php
Labels: backend

#13816 Fixed datetime displayed on license edit for fields that should be date
  app/Models/License.php
  resources/views/licenses/edit.blade.php
Labels: frontend, backend

#13821 More graceful failure if ldap_results JSON decode isn’t set
  app/Http/Controllers/Users/LDAPImportController.php
Labels: backend, ldap
