Repository grokability/snipe-it, pull requests merged in 2023-09, with the labels that each got.

#12901 Added users total cost of assets to user profile
  app/Models/User.php
  resources/lang/en/admin/users/table.php
  resources/views/users/view.blade.php
Labels: frontend, backend, translations

#13565 Account for hard-deleted models, suppliers
  app/Http/Transformers/ActionlogsTransformer.php
  resources/lang/en/admin/models/message.php
  resources/lang/en/admin/suppliers/message.php
Labels: backend, translations

#13557 Added/Fixed: track changes on asset checkin/out
  app/Events/CheckoutableCheckedIn.php
  app/Events/CheckoutableCheckedOut.php
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Assets/AssetCheckinController.php
  app/Listeners/LogListener.php
  app/Models/Asset.php
  app/Models/Loggable.php
Labels: backend, api

#13547 Fixed ErrorException: Attempt to read property "asset_tag" on null (rollbar #3541)
  app/Http/Controllers/Assets/BulkAssetsController.php
Labels: backend

#13567 Add default location to tracked changes on checkin actionlog
  app/Models/Loggable.php
Labels: backend

#13571 Fixed Attempt to read property require_acceptance on null [rollbar-3557]
  app/Models/License.php
  app/Models/LicenseSeat.php
Labels: backend

#13573 Upgrade to new branch for our fork of laravel-scim-server
  composer.lock
Labels: backend, dependencies

#13574 Fixed Unaccepted Assets report has incorrect people [freshdesk-37808]
  app/Http/Controllers/ReportsController.php
Labels: backend

#13566 Fixed #13562 - Added inline file link
  app/Http/Controllers/Accessories/AccessoriesFilesController.php
  app/Http/Controllers/AssetModelsFilesController.php
  app/Http/Controllers/Assets/AssetFilesController.php
  app/Http/Controllers/Components/ComponentsFilesController.php
  app/Http/Controllers/Consumables/ConsumablesFilesController.php
  app/Http/Controllers/Licenses/LicenseFilesController.php
  app/Http/Controllers/Users/UserFilesController.php
  resources/views/accessories/view.blade.php
  resources/views/components/view.blade.php
  resources/views/consumables/view.blade.php
  resources/views/hardware/view.blade.php
  resources/views/licenses/view.blade.php
  resources/views/models/view.blade.php
  resources/views/users/view.blade.php
Labels: frontend, backend, consumables

#13575 Added validation around department_id in API patch request
  app/Http/Requests/SaveUserRequest.php
  tests/Feature/Api/Users/UsersUpdateTest.php
Labels: backend, tests

#13577 Fixed failing test
  tests/Feature/Api/Users/UsersUpdateTest.php
Labels: tests

#13526 Added threshold notifications and min qty for Asset models
  app/Helpers/Helper.php
  app/Http/Controllers/Api/AssetModelsController.php
  app/Http/Controllers/AssetModelsController.php
  app/Http/Transformers/ActionlogsTransformer.php
  app/Http/Transformers/AssetModelsTransformer.php
  app/Models/AssetModel.php
  app/Presenters/AssetModelPresenter.php
  database/migrations/2023_08_21_181742_add_min_amt_to_models_table.php
  resources/views/models/edit.blade.php
Labels: frontend, backend, api

#13586 Fixed Call to a member function checkedOutToUser() on null [rollbar-3598]
  app/Http/Controllers/ReportsController.php
Labels: backend

#13597 Reset checkout to value when navigating away from type
  app/Listeners/CheckoutableListener.php
  resources/assets/js/snipeit.js
Labels: frontend, backend, javascript, skins

#13581 Upgraded actions/checkout to v4 (via #13580)
  .github/workflows/SA-codeql.yml
  .github/workflows/codacy-analysis.yml
  .github/workflows/crowdin-upload.yml
  .github/workflows/docker-alpine.yml
  .github/workflows/docker.yml
  .github/workflows/tests.yml
Labels: config

#13549 Fixed ErrorException: Attempt to read property "id" on null (rollbar #3541)
  app/Listeners/CheckoutableListener.php
Labels: backend

#13520 Fixed Not reassignable Licenses shouldn't show 'Checkin All Seats' button [sc-23506]
  app/Http/Controllers/Licenses/LicenseCheckinController.php
  resources/lang/en/admin/licenses/general.php
  resources/views/licenses/view.blade.php
Labels: frontend, backend, translations

#13415 Added `CompanyableTrait` to `Department` model
  app/Http/Controllers/Api/DepartmentsController.php
  app/Models/Department.php
  tests/Feature/Api/Departments/DepartmentIndexTest.php
Labels: backend, api, tests

#13343 Fixed #13336 - Save unhashed password if no password provided
  app/Console/Commands/LdapSync.php
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/Auth/LoginController.php
  app/Models/Ldap.php
  app/Models/SCIMUser.php
  app/Models/User.php
Labels: backend, ldap, api, scim, cli / artisan

#13602 Fixed checkbox formatting on quickstart
  resources/views/setup/user.blade.php
Labels: frontend

#13605 Simplify upload messaging, handle -1% error
  resources/lang/en/general.php
  resources/views/livewire/importer.blade.php
  resources/views/notifications.blade.php
Labels: frontend, livewire, translations

#13606 Fixed #13592 - unable to delete model from view page
  resources/lang/en/general.php
  resources/views/models/view.blade.php
Labels: frontend, translations

#13608 Use relative path in backups for cleaner directory structure
  config/backup.php
Labels: backups

#13610 Fixes #13609 - disallow sorting on age
  app/Presenters/AssetPresenter.php
Labels: backend

#13612 Fixed regression that disabled sticky headers
  public/js/build/app.js
  public/js/dist/all.js
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
  resources/views/partials/bootstrap-table.blade.php
  webpack.mix.js
Labels: frontend, javascript, skins

#13613 Added column re-ordering
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
  resources/assets/css/dragtable.css
  resources/assets/js/bootstrap-table-reorder-columns.js
  resources/assets/js/dragtable.js
  resources/views/partials/bootstrap-table.blade.php
  webpack.mix.js
Labels: frontend, javascript, css, skins

#13625 Replaces #13618 - Bump docker/build-push-action from 4 to 5
  .github/workflows/docker-alpine.yml
  .github/workflows/docker.yml
Labels: config

#13626 Replaces #13617 - Bump docker/setup-buildx-action from 2 to 3
  .github/workflows/docker-alpine.yml
  .github/workflows/docker.yml
Labels: config

#13627 Replaces #13616 - Bump docker/metadata-action from 4 to 5
  .github/workflows/docker-alpine.yml
  .github/workflows/docker.yml
Labels: config

#13623 Made develop the target branch for dependabot
  .github/dependabot.yml
Labels: config

#13629 Fixed #13628 - removed duplicate favicon tag
  resources/views/layouts/basic.blade.php
Labels: frontend

#13634 Added factories to autolabeler action
  .github/autolabeler.yml
Labels: config

#12992 Adds tag for docker builds
  .github/workflows/docker-alpine.yml
  .github/workflows/docker.yml
Labels: config

#13650 Features/more info in settings
  config/app.php
  resources/lang/en/admin/settings/general.php
  resources/views/settings/index.blade.php
Labels: frontend, translations

#13655 Fixed bug where checkout to location would throw an error if FMCS was enabled
  app/Http/Controllers/Assets/AssetCheckoutController.php
  resources/lang/en/general.php
Labels: backend, translations

#13657 Commented out sortable columns
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend

#13667 Fixed #13658 for asset history with encrypted fields
  app/Http/Transformers/ActionlogsTransformer.php
Labels: backend

#13671 Fixed #13670 - order number missing from license import
  app/Http/Livewire/Importer.php
  app/Importer/Importer.php
  app/Importer/LicenseImporter.php
Labels: backend, importer, livewire

#13672 Fixed #13662 - added clipboard.js
  package-lock.json
  package.json
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/js/build/vendor.js
  public/js/dist/all.js
  public/mix-manifest.json
  resources/lang/en/general.php
  resources/views/hardware/view.blade.php
  resources/views/layouts/default.blade.php
  resources/views/licenses/view.blade.php
  webpack.mix.js
Labels: frontend, javascript, css, dependencies, skins, translations

#13674 Fixed bug where license checkout/checkin notes were not being saved
  app/Http/Controllers/Licenses/LicenseCheckinController.php
  app/Http/Controllers/Licenses/LicenseCheckoutController.php
  app/Http/Transformers/LicenseSeatsTransformer.php
  app/Presenters/LicensePresenter.php
  resources/views/licenses/checkin.blade.php
  resources/views/licenses/checkout.blade.php
Labels: frontend, backend

#13677 Set modal focus to modal-name field
  public/js/build/app.js
  public/js/dist/all.js
  public/mix-manifest.json
  resources/assets/js/snipeit_modals.js
  resources/views/modals/user.blade.php
Labels: frontend, javascript, skins

#13678 Fieldset Properly Sortable in Asset Models Table
  app/Http/Controllers/Api/AssetModelsController.php
  app/Models/AssetModel.php
Labels: backend, api

#13679 Fixed General Webhooks error messaging and validation
  app/Http/Livewire/SlackSettingsForm.php
  resources/lang/en/admin/settings/message.php
  resources/views/livewire/slack-settings-form.blade.php
Labels: frontend, backend, javascript, dependencies, skins, livewire, translations

#13681 Fixed uncaught type error when attempting to render barcodes with invalid characters
  app/Http/Controllers/LabelsController.php
  app/Models/Labels/Label.php
Labels: backend

#13683 Fixed consumable user view route name
  resources/views/consumables/view.blade.php
  routes/api.php
Labels: frontend, consumables
