Repository grokability/snipe-it, pull requests merged in 2023-08, with the labels that each got.

#13397 Fixed #13372: Put guard around assigning location via LDAP
  app/Console/Commands/LdapSync.php
Labels: backend, ldap, cli / artisan

#13421 Re-add the option for asset_eol_date as an import field
  app/Http/Livewire/Importer.php
Labels: backend, importer, livewire

#13424 Fixed tooltip not loading on encrypted field lock icon on asset detail view
  resources/views/layouts/default.blade.php
  resources/views/models/custom_fields_form.blade.php
Labels: frontend, custom fields

#13425 Updated webpack
  package-lock.json
  package.json
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
Labels: frontend, javascript, css, dependencies, skins

#13407 Added messaging to category edit page to improve clarity around when users will be emailed
  app/Http/Livewire/CategoryEditForm.php
  resources/lang/en/admin/categories/general.php
  resources/views/categories/edit.blade.php
  resources/views/livewire/category-edit-form.blade.php
  tests/Feature/Livewire/CategoryEditFormTest.php
Labels: frontend, backend, livewire, translations, tests

#13428 Updated autotable
  package-lock.json
  package.json
Labels: javascript, dependencies

#13434 Improved test stability and messaging
  tests/Support/CustomTestMacros.php
Labels: tests

#13431 Removed unneeded `Company::scopeCompanyables` from `ReportsController`
  app/Http/Controllers/ReportsController.php
  database/factories/UserFactory.php
  tests/Feature/Reports/CustomReportTest.php
Labels: backend, tests

#13439 Fixed route for accessory index
  app/Http/Controllers/Accessories/AccessoriesController.php
Labels: backend

#13445 Fixed case in BS table formatter for boolean
  resources/views/reports/asset_maintenances.blade.php
Labels: frontend

#13454 Fixed #13450 - remove escaping on saveing new custom fields
  app/Http/Controllers/CustomFieldsetsController.php
Labels: backend, custom fields

#13448 Fixed #13446 - added translations to status label type column
  resources/views/statuslabels/index.blade.php
Labels: frontend, backend

#13455 Fixed #13382 - confusion around localization date
  resources/macros/macros.php
  resources/views/settings/localization.blade.php
Labels: frontend

#13442 Add email to companies
  app/Http/Controllers/Api/CompaniesController.php
  app/Http/Controllers/CompaniesController.php
  app/Http/Transformers/CompaniesTransformer.php
  app/Models/Company.php
  app/Presenters/CompanyPresenter.php
  database/migrations/2023_08_13_172600_add_email_to_companies.php
  resources/views/companies/edit.blade.php
Labels: frontend, backend, api

#12050 New Label Engine
  app/Helpers/Helper.php
  app/Http/Controllers/Api/LabelsController.php
  app/Http/Controllers/Assets/AssetsController.php
  app/Http/Controllers/Assets/BulkAssetsController.php
  app/Http/Controllers/LabelsController.php
  app/Http/Controllers/SettingsController.php
  app/Http/Transformers/LabelsTransformer.php
  app/Models/Labels/DefaultLabel.php
  app/Models/Labels/Field.php
  app/Models/Labels/FieldOption.php
  app/Models/Labels/Label.php
  app/Models/Labels/RectangleSheet.php
  app/Models/Labels/Sheet.php
  app/Models/Labels/Sheets/Avery/L7162.php
  app/Models/Labels/Sheets/Avery/L7162_A.php
  app/Models/Labels/Sheets/Avery/L7162_B.php
  app/Models/Labels/Sheets/Avery/L7163.php
  app/Models/Labels/Sheets/Avery/L7163_A.php
  app/Models/Labels/Sheets/Avery/_5267.php
  app/Models/Labels/Sheets/Avery/_5267_A.php
  app/Models/Labels/Sheets/Avery/_5520.php
  app/Models/Labels/Sheets/Avery/_5520_A.php
  app/Models/Labels/Tapes/Brother/TZe_12mm.php
  app/Models/Labels/Tapes/Brother/TZe_12mm_A.php
  app/Models/Labels/Tapes/Brother/TZe_24mm.php
  app/Models/Labels/Tapes/Brother/TZe_24mm_A.php
  app/Presenters/LabelPresenter.php
  app/View/Label.php
  composer.json
  database/migrations/2022_10_25_215520_add_label2_settings.php
  package.json
  public/js/dist/all-defer.js
  public/mix-manifest.json
  public/uploads/companies/.gitignore
  public/uploads/companies/company-image-test.png
  resources/lang/en/admin/labels/message.php
  resources/lang/en/admin/labels/table.php
  resources/lang/en/admin/settings/general.php
  resources/views/layouts/default.blade.php
  resources/views/partials/bootstrap-table.blade.php
  resources/views/partials/label2-field-definitions.blade.php
  resources/views/partials/label2-preview.blade.php
  resources/views/settings/labels.blade.php
  routes/api.php
  routes/web.php
  routes/web/hardware.php
  webpack.mix.js
Labels: frontend, backend, api, dependencies, skins

#13463 Accessory checkin via API reported wrong target user
  app/Http/Controllers/Api/AccessoriesController.php
Labels: backend, api

#13457 Fixed #13365 - Added LOGIN_AUTOCOMPLETE as env var
  .env.example
  config/auth.php
  resources/views/auth/login.blade.php
Labels: frontend

#13473 Check that there is a company before trying to get name property
  app/View/Label.php
  resources/views/settings/labels.blade.php
Labels: frontend, backend

#13476 Accessory checkin via API reported wrong target user
  app/Http/Controllers/Api/AccessoriesController.php
Labels: backend, api

#13471 Fixed #13409 Search in component detail view not working
  app/Http/Controllers/Api/ComponentsController.php
Labels: backend, api

#13483 Fixed #13359 Advanced search by Default Location does not work
  app/Models/Asset.php
Labels: backend

#13391 Fixed Ldap sync field clear bug
  app/Console/Commands/LdapSync.php
Labels: backend, ldap, cli / artisan

#13488 Fixed #13487 - include supplier url in listing
  app/Http/Controllers/Api/SuppliersController.php
Labels: backend, api

#13489 Make sure the columns and rows can never be 0
  app/Models/Labels/DefaultLabel.php
Labels: backend

#13491 Removed the black label from around the default labels in new label engine
  app/Models/Labels/DefaultLabel.php
Labels: backend

#13492 Added Dymo labelwriter
  app/Http/Controllers/LabelsController.php
  app/Http/Transformers/LabelsTransformer.php
  app/Models/Labels/Label.php
  app/Models/Labels/Tapes/Dymo/LabelWriter.php
  app/Models/Labels/Tapes/Dymo/LabelWriter_30252.php
  app/Presenters/LabelPresenter.php
Labels: backend

#13456 Fixed passing invalid argument to `strpos()`
  app/Observers/AssetObserver.php
Labels: backend

#13436 Bumped dependencies
  composer.lock
Labels: backend, dependencies

#13485 Added better handling of information of asset history
  app/Http/Transformers/ActionlogsTransformer.php
  resources/lang/en/general.php
Labels: backend, translations

#12761 Bulk Editing Custom Fields
  app/Http/Controllers/Assets/BulkAssetsController.php
  app/Models/AssetModel.php
  app/Models/CustomField.php
  resources/lang/en/admin/hardware/form.php
  resources/lang/en/general.php
  resources/views/hardware/bulk.blade.php
  resources/views/models/custom_fields_form_bulk_edit.blade.php
  resources/views/notifications.blade.php
Labels: frontend, backend, custom fields, translations

#13453 Fixed #13317 Accessories declined by user remain assigned
  app/Http/Controllers/Account/AcceptanceController.php
  app/Models/Accessory.php
Labels: backend

#13496 Fixed #13495 added setting for name order
  app/Http/Controllers/SettingsController.php
  app/Http/Transformers/UsersTransformer.php
  app/Models/User.php
  app/Presenters/UserPresenter.php
  database/migrations/2023_08_21_064609_add_name_ordering_to_settings.php
  resources/lang/en/general.php
  resources/macros/macros.php
  resources/views/account/profile.blade.php
  resources/views/account/view-assets.blade.php
  resources/views/layouts/default.blade.php
  resources/views/settings/localization.blade.php
Labels: frontend, backend, translations

#13501 Small fixes to checkbox layout in general settings blade
  resources/views/settings/general.blade.php
Labels: frontend

#13509 Fixed asset model query in action log transformer
  app/Http/Transformers/ActionlogsTransformer.php
Labels: backend

#13525 Fixed undeclared variable in ActionlogsTransformer
  app/Http/Transformers/ActionlogsTransformer.php
Labels: backend

#13533 Clearer labels barcode text
  resources/lang/en/admin/settings/general.php
  resources/views/settings/labels.blade.php
Labels: frontend, translations

#13535 Fixed #13521 - make modal “select files” button wider
  resources/views/modals/upload-file.blade.php
Labels: frontend

#13518 Run tests for PHP 7.4, 8.0, and 8.1.1 via GitHub Actions
  .github/workflows/tests.yml
Labels: config

#13537 Fixed #13500 - Try to prevent the browser from pre-filling the LDAP password
  resources/views/settings/ldap.blade.php
Labels: frontend, ldap

#13528 Fixed #12548 Cloning a model blanks fieldset of new one
  app/Http/Controllers/AssetModelsController.php
  resources/views/models/edit.blade.php
Labels: frontend, backend

#13544 Fixed user search not adhering to company scoping
  app/Http/Controllers/Api/UsersController.php
  tests/Feature/Api/Users/UsersSearchTest.php
Labels: backend, api, tests

#13546 Don’t cast as boolean, do validate as boolean for User validation
  app/Models/Asset.php
  app/Models/User.php
  tests/Feature/Api/Users/UpdateUserApiTest.php
  tests/Feature/Users/UpdateUserTest.php
Labels: backend, tests

#13507 Added eager loading for `changedinfo` and removed encrypted values from Asset history
  app/Http/Transformers/ActionlogsTransformer.php
  resources/lang/en/admin/companies/message.php
Labels: backend, translations

#13550 Removed Dusk
  .chipperci.yml
  .gitignore
  TESTING.md
  app/Providers/AppServiceProvider.php
  composer.json
  composer.lock
  tests/Browser/LoginTest.php
  tests/Browser/Pages/HomePage.php
  tests/Browser/Pages/Page.php
  tests/Browser/console/.gitignore
  tests/Browser/screenshots/.gitignore
  tests/Browser/source/.gitignore
  tests/DuskTestCase.php
Labels: backend, dependencies, tests
