Repository grokability/snipe-it, pull requests merged in 2023-04, with the labels that each got.

#12781 Color picker UI fix
  resources/views/statuslabels/edit.blade.php
Labels: frontend, backend

#12765 Change protected $dates to casts
  app/Models/Asset.php
  app/Models/User.php
Labels: backend

#12790 Updated support URL
  app/Http/Controllers/Controller.php
Labels: backend

#12792 Fixed #12776 - larger EOL field
  resources/views/models/edit.blade.php
Labels: frontend, backend

#12793 Fixed #12772 - use the APP_URL config more consistently
  app/Http/Controllers/SettingsController.php
  app/Http/Middleware/CheckForSetup.php
  app/Models/Location.php
  app/Notifications/FirstAdminNotification.php
  app/Notifications/WelcomeNotification.php
  app/Presenters/AssetModelPresenter.php
  app/Presenters/UserPresenter.php
  app/Services/Saml.php
  resources/views/account/requestable-assets.blade.php
  resources/views/asset_maintenances/index.blade.php
  resources/views/errors/403.blade.php
  resources/views/errors/404.blade.php
  resources/views/errors/503.blade.php
  resources/views/hardware/edit.blade.php
  resources/views/hardware/requested.blade.php
  resources/views/layouts/default.blade.php
  resources/views/locations/print.blade.php
  resources/views/notifications/FirstAdmin.blade.php
  resources/views/notifications/Welcome.blade.php
  resources/views/partials/assets-assigned.blade.php
  resources/views/partials/bootstrap-table.blade.php
  resources/views/settings/saml.blade.php
  resources/views/setup/done.blade.php
  resources/views/statuslabels/index.blade.php
  resources/views/users/print.blade.php
  resources/views/vendor/mail/markdown/message.blade.php
  resources/views/vendor/notifications/email.blade.php
Labels: frontend, backend, saml, notifications

#12787 Added unavailable message to prevent over-checkout of Accessories
  app/Http/Controllers/Accessories/AccessoryCheckoutController.php
  resources/lang/en/admin/accessories/message.php
Labels: backend

#12800 Fixed accessories verifying that enough remain to be checked out
  app/Http/Controllers/Accessories/AccessoryCheckoutController.php
  app/Models/Accessory.php
Labels: backend

#12799 Added BM JS
  config/services.php
  resources/views/layouts/default.blade.php
  resources/views/partials/bpay.blade.php
Labels: frontend, backend

#12802 Check for available quantity on consumables before checkout
  app/Http/Controllers/Api/ConsumablesController.php
  app/Http/Controllers/Consumables/ConsumableCheckoutController.php
  resources/lang/en/admin/consumables/message.php
Labels: backend, consumables, api

#12804 Remove "FARTS" from bpay.blade.php
  resources/views/partials/bpay.blade.php
Labels: frontend, backend

#12803 Small component UI/validation/API fixes
  app/Http/Controllers/Api/ComponentsController.php
  app/Http/Controllers/Components/ComponentCheckoutController.php
  resources/lang/en/admin/components/message.php
  resources/views/components/checkout.blade.php
Labels: frontend, backend, api

#12807 Echo out the array values in withInput()
  resources/views/hardware/edit.blade.php
  resources/views/partials/forms/edit/serial.blade.php
Labels: frontend, backend

#12810 Maintain activated state on editing a user
  app/Http/Controllers/Users/UsersController.php
  resources/views/users/edit.blade.php
Labels: frontend, backend

#12818 Check for Carbon exception
  app/Exceptions/Handler.php
  app/Models/License.php
  resources/views/licenses/edit.blade.php
Labels: frontend, backend

#12826 Added invalid parse to dontReport
  app/Exceptions/Handler.php
  app/Models/License.php
  resources/views/licenses/edit.blade.php
  resources/views/partials/forms/edit/datepicker.blade.php
Labels: frontend, backend

#12833 Update Dockerfile to Ubuntu 22.04 and PHP 8.1
  Dockerfile
  Dockerfile.alpine
  Dockerfile.fpm-alpine
Labels: docker

#12827 Better handling for weird data passed to the API via limit and offset
  app/Http/Controllers/Api/AccessoriesController.php
  app/Http/Controllers/Api/AssetMaintenancesController.php
  app/Http/Controllers/Api/AssetModelsController.php
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Api/CategoriesController.php
  app/Http/Controllers/Api/CompaniesController.php
  app/Http/Controllers/Api/ComponentsController.php
  app/Http/Controllers/Api/ConsumablesController.php
  app/Http/Controllers/Api/DepartmentsController.php
  app/Http/Controllers/Api/DepreciationsController.php
  app/Http/Controllers/Api/GroupsController.php
  app/Http/Controllers/Api/LicenseSeatsController.php
  app/Http/Controllers/Api/LicensesController.php
  app/Http/Controllers/Api/LocationsController.php
  app/Http/Controllers/Api/ManufacturersController.php
  app/Http/Controllers/Api/PredefinedKitsController.php
  app/Http/Controllers/Api/ReportsController.php
  app/Http/Controllers/Api/StatuslabelsController.php
  app/Http/Controllers/Api/SuppliersController.php
  app/Http/Controllers/Api/UsersController.php
Labels: backend, consumables, api

#12842 Use abs() instead of max
  app/Http/Controllers/Api/AccessoriesController.php
  app/Http/Controllers/Api/AssetMaintenancesController.php
  app/Http/Controllers/Api/AssetModelsController.php
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Api/CategoriesController.php
  app/Http/Controllers/Api/CompaniesController.php
  app/Http/Controllers/Api/ComponentsController.php
  app/Http/Controllers/Api/ConsumablesController.php
  app/Http/Controllers/Api/DepartmentsController.php
  app/Http/Controllers/Api/DepreciationsController.php
  app/Http/Controllers/Api/GroupsController.php
  app/Http/Controllers/Api/LicenseSeatsController.php
  app/Http/Controllers/Api/LicensesController.php
  app/Http/Controllers/Api/LocationsController.php
  app/Http/Controllers/Api/ManufacturersController.php
  app/Http/Controllers/Api/PredefinedKitsController.php
  app/Http/Controllers/Api/ReportsController.php
  app/Http/Controllers/Api/StatuslabelsController.php
  app/Http/Controllers/Api/SuppliersController.php
  app/Http/Controllers/Api/UsersController.php
Labels: backend, consumables, api

#12843 Temp fix for the seeders
  database/seeders/AssetSeeder.php
Labels: backend

#12834 Introduced improved way to interact with settings in tests
  database/factories/SettingFactory.php
  tests/Feature/Api/Assets/AssetIndexTest.php
  tests/Feature/Api/Users/UsersForSelectListTest.php
  tests/Support/InteractsWithSettings.php
  tests/Support/Settings.php
  tests/TestCase.php
Labels: backend

#12830 Added supplier to components and consumables
  app/Http/Controllers/Api/ComponentsController.php
  app/Http/Controllers/Api/ConsumablesController.php
  app/Http/Controllers/Api/SuppliersController.php
  app/Http/Controllers/Components/ComponentsController.php
  app/Http/Controllers/Consumables/ConsumablesController.php
  app/Http/Transformers/ComponentsTransformer.php
  app/Http/Transformers/ConsumablesTransformer.php
  app/Http/Transformers/SuppliersTransformer.php
  app/Models/Component.php
  app/Models/Consumable.php
  app/Models/Supplier.php
  app/Presenters/ComponentPresenter.php
  app/Presenters/ConsumablePresenter.php
  database/factories/ComponentFactory.php
  database/factories/ConsumableFactory.php
  database/migrations/2023_04_12_135822_add_supplier_to_components.php
  resources/views/components/edit.blade.php
  resources/views/consumables/edit.blade.php
  resources/views/partials/forms/edit/category-select.blade.php
  resources/views/partials/forms/edit/supplier-select.blade.php
  resources/views/suppliers/index.blade.php
  resources/views/suppliers/view.blade.php
Labels: frontend, backend, consumables, api

#12844 Small blade partial fixes
  resources/views/partials/forms/edit/category-select.blade.php
  resources/views/partials/forms/edit/quantity.blade.php
  resources/views/partials/forms/edit/supplier-select.blade.php
Labels: frontend, backend

#12845 Upgrade bootstrap-table from 1.20.2 to 1.21.3 (Formerly #12733)
  package-lock.json
  package.json
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
Labels: frontend, css, skins

#12847 Adds a few more auto-labels
  .github/autolabeler.yml
Labels: config

#12848 Added a singleton to filter API limit value
  app/Http/Controllers/Api/AccessoriesController.php
  app/Http/Controllers/Api/AssetMaintenancesController.php
  app/Http/Controllers/Api/AssetModelsController.php
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Api/CategoriesController.php
  app/Http/Controllers/Api/CompaniesController.php
  app/Http/Controllers/Api/ComponentsController.php
  app/Http/Controllers/Api/ConsumablesController.php
  app/Http/Controllers/Api/DepartmentsController.php
  app/Http/Controllers/Api/DepreciationsController.php
  app/Http/Controllers/Api/GroupsController.php
  app/Http/Controllers/Api/LicenseSeatsController.php
  app/Http/Controllers/Api/LicensesController.php
  app/Http/Controllers/Api/LocationsController.php
  app/Http/Controllers/Api/ManufacturersController.php
  app/Http/Controllers/Api/PredefinedKitsController.php
  app/Http/Controllers/Api/ReportsController.php
  app/Http/Controllers/Api/StatuslabelsController.php
  app/Http/Controllers/Api/SuppliersController.php
  app/Http/Controllers/Api/UsersController.php
  app/Providers/SettingsServiceProvider.php
Labels: backend, consumables, api

#12857 Remove start/end dates form casts array
  app/Models/User.php
Labels: backend

#12855 Allow checkout of available components down to zero stock (fixes #12854)
  app/Http/Controllers/Components/ComponentCheckoutController.php
Labels: backend

#12828 Fixed dark themes pagination and notification drop menu
  resources/assets/less/skins/skin-black-dark.less
  resources/assets/less/skins/skin-blue-dark.less
  resources/assets/less/skins/skin-green-dark.less
  resources/assets/less/skins/skin-orange-dark.less
  resources/assets/less/skins/skin-purple-dark.less
  resources/assets/less/skins/skin-red-dark.less
  resources/assets/less/skins/skin-yellow-dark.less
Labels: frontend, css, skins

#12832 Fixed footer space when customized
  resources/assets/less/overrides.less
  resources/views/layouts/default.blade.php
Labels: frontend, backend, css, skins

#12849 Added license checkin/checkout to all in license GUI
  app/Console/Commands/CreateAdmin.php
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/Licenses/LicenseCheckinController.php
  app/Http/Controllers/Licenses/LicenseCheckoutController.php
  app/Http/Controllers/Licenses/LicensesController.php
  app/Http/Controllers/Users/BulkUsersController.php
  app/Http/Controllers/Users/UsersController.php
  app/Http/Transformers/LicensesTransformer.php
  app/Http/Transformers/UsersTransformer.php
  app/Importer/UserImporter.php
  app/Models/License.php
  app/Models/Supplier.php
  app/Models/User.php
  app/Presenters/LicensePresenter.php
  app/Presenters/UserPresenter.php
  resources/lang/en/admin/licenses/general.php
  resources/lang/en/general.php
  resources/views/custom_fields/index.blade.php
  resources/views/groups/edit.blade.php
  resources/views/hardware/view.blade.php
  resources/views/layouts/default.blade.php
  resources/views/licenses/view.blade.php
  resources/views/modals/confirm-action.blade.php
  resources/views/modals/upload-file.blade.php
  resources/views/models/custom_fields_form.blade.php
  resources/views/partials/bootstrap-table.blade.php
  resources/views/partials/forms/edit/minimum_quantity.blade.php
  resources/views/partials/forms/edit/permissions-base.blade.php
  resources/views/users/bulk-edit.blade.php
  resources/views/users/edit.blade.php
  resources/views/users/view.blade.php
  routes/web/licenses.php
Labels: frontend, backend, custom fields, importer, api, cli / artisan, translations

#12875 Fixed space from un deployable total in sidebar
  resources/views/layouts/default.blade.php
Labels: frontend

#12885 Fixed Call to a member function totalSeatsByLicenseID() on null
  app/Http/Controllers/Licenses/LicensesController.php
Labels: backend

#12887 Fix: Ensure users editing themselves do not deactivate their account
  app/Http/Controllers/Users/UsersController.php
  tests/Feature/Users/UpdateUserTest.php
Labels: backend, tests

#12910 Added more granular permissions on bulk actions for assets
  app/Http/Controllers/Assets/BulkAssetsController.php
Labels: backend

#12904 Fixed #8342: Add ARM64 architecture to Docker Builds
  .github/workflows/docker-alpine.yml
  .github/workflows/docker.yml
Labels: config

#12913 Change from a standard Eloquent mapping for ID to a custom setRead
  app/Models/SnipeSCIMConfig.php
Labels: backend, scim

#12914 Fixes state leak between tests
  tests/Feature/Users/UpdateUserTest.php
Labels: tests

#12912 added ldap_location to settings
  app/Console/Commands/LdapSync.php
  app/Http/Controllers/SettingsController.php
  app/Models/Ldap.php
  app/Models/Setting.php
  database/migrations/2023_04_25_181817_adds_ldap_location_to_settings_table.php
  resources/lang/en/admin/settings/general.php
  resources/views/settings/ldap.blade.php
Labels: frontend, backend, ldap, cli / artisan, translations

#12888 [Snyk] Upgrade webpack from 5.76.2 to 5.77.0
  package-lock.json
  package.json
Labels: javascript, dependencies

#12905 Fixes where clause operator in artisan checkout command
  app/Console/Commands/CheckoutLicenseToAllUsers.php
Labels: backend, cli / artisan

#12903 Fixes sending webhook notifications for checkout and checkin
  app/Listeners/CheckoutableListener.php
  app/Models/LicenseSeat.php
  app/Models/User.php
  database/factories/LicenseSeatFactory.php
  tests/Feature/Notifications/AccessoryWebhookTest.php
  tests/Feature/Notifications/AssetWebhookTest.php
  tests/Feature/Notifications/ComponentWebhookTest.php
  tests/Feature/Notifications/ConsumableWebhookTest.php
  tests/Feature/Notifications/LicenseWebhookTest.php
  tests/Support/Settings.php
Labels: backend, tests

#12756 Fixed #8208, #8896, #8985 and #9789: Currency issues when using non-english locales (resubmission)
  app/Http/Controllers/Accessories/AccessoriesController.php
  app/Http/Controllers/Api/AssetMaintenancesController.php
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/AssetMaintenancesController.php
  app/Http/Controllers/Assets/AssetsController.php
  app/Http/Controllers/Assets/BulkAssetsController.php
  app/Http/Controllers/Components/ComponentsController.php
  app/Http/Controllers/Consumables/ConsumablesController.php
  app/Http/Controllers/Licenses/LicensesController.php
  app/Models/AssetMaintenance.php
  app/Models/SnipeModel.php
Labels: backend, consumables, api

#12917 Applies #12868 - fixes EOL date on asset creation
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Assets/AssetsController.php
Labels: backend, api

#12906 Dynamic warranty link for manufacturers' support urls
  app/Http/Controllers/ManufacturersController.php
  app/Models/Manufacturer.php
  app/Presenters/AssetPresenter.php
  resources/views/hardware/view.blade.php
Labels: frontend, backend

#12929 Use the asset tag instead of asset name if no name is given
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend

#12930 Added help text to the now-dynamic manufacturer URLS
  resources/lang/en/admin/manufacturers/message.php
  resources/views/manufacturers/edit.blade.php
Labels: frontend, translations

#12932 Added dynamic warranty URL to manufacturers
  app/Http/Controllers/Api/ManufacturersController.php
  app/Http/Controllers/ManufacturersController.php
  app/Http/Transformers/ManufacturersTransformer.php
  app/Models/Manufacturer.php
  app/Presenters/AssetPresenter.php
  app/Presenters/ManufacturerPresenter.php
  database/factories/ManufacturerFactory.php
  database/migrations/2023_04_26_160235_add_warranty_url_to_manufacturers.php
  resources/lang/en/admin/manufacturers/table.php
  resources/views/hardware/view.blade.php
  resources/views/manufacturers/edit.blade.php
Labels: frontend, backend, api, translations

#12933 Remove auto-link from from manufacturer warranty
  app/Presenters/ManufacturerPresenter.php
  resources/views/hardware/view.blade.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#12942 Added missing case for licenses for item_count
  app/Http/Transformers/CategoriesTransformer.php
Labels: backend

#12928 Env-ify hashing variables, setting the normal defaults
  .env.example
  config/hashing.php
Labels: config

#12941 Created At and Updated At fields on License table view
  app/Presenters/LicensePresenter.php
Labels: backend

#12950 Fixed #12946 - warranty lookup url was not nullable
  app/Models/Manufacturer.php
Labels: backend
