Repository grokability/snipe-it, pull requests merged in 2023-07, with the labels that each got.

#13169 Making Serial Number the logic checked against for new imports
  app/Importer/LicenseImporter.php
Labels: backend, importer

#13264 Fix label wrapping on category edit page
  resources/views/categories/edit.blade.php
Labels: frontend

#13279 Upgraded acorn
  package-lock.json
  package.json
Labels: javascript, dependencies

#13280 [Snyk] Upgrade webpack from 5.86.0 to 5.87.0 #13267
  package-lock.json
  package.json
Labels: javascript, dependencies

#13282 Fixes dev dependency on PHP 7.4
  composer.json
  composer.lock
Labels: backend, dependencies

#13281 Fixed #13276 Error Showing Requested Assets
  app/Models/CheckoutRequest.php
  resources/views/hardware/requested.blade.php
Labels: frontend, backend

#13277 Added phone, fax to departments, locations, companies
  app/Http/Controllers/Api/CompaniesController.php
  app/Http/Controllers/Api/DepartmentsController.php
  app/Http/Controllers/Api/LocationsController.php
  app/Http/Controllers/CompaniesController.php
  app/Http/Controllers/DepartmentsController.php
  app/Http/Controllers/LocationsController.php
  app/Http/Transformers/CompaniesTransformer.php
  app/Http/Transformers/DepartmentsTransformer.php
  app/Http/Transformers/LocationsTransformer.php
  app/Models/Company.php
  app/Models/Department.php
  app/Models/Location.php
  app/Presenters/CompanyPresenter.php
  app/Presenters/LocationPresenter.php
  database/migrations/2023_07_06_092507_add_phone_fax_to_locations.php
  resources/views/companies/edit.blade.php
  resources/views/departments/edit.blade.php
  resources/views/locations/edit.blade.php
  resources/views/partials/forms/edit/fax.blade.php
  resources/views/suppliers/edit.blade.php
Labels: frontend, backend, api

#13292 Avoid accidentally wiping local database when running tests
  .chipperci.yml
  tests/DuskTestCase.php
  tests/TestCase.php
Labels: tests

#13268 Fixed License importer missing Checkout to: Username and Checkout to: Email in dropdown [sc-23456]
  app/Http/Livewire/Importer.php
Labels: backend, importer, livewire

#13233 fixed margin if qr_code present
  resources/views/hardware/labels.blade.php
Labels: frontend

#13225 Fixed #13167 Default location not being set/updated upon check-in
  app/Http/Controllers/Assets/AssetCheckinController.php
  resources/views/hardware/checkin.blade.php
  resources/views/partials/forms/edit/location-select.blade.php
Labels: frontend, backend

#13302 Fixed #13256 - Added option to switch to localStorage instead of cookies
  .env.example
  config/session.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend

#13301 Better auto increment asset-tags [FD-32892]
  app/Http/Controllers/Api/AssetsController.php
  app/Models/Asset.php
  app/Observers/AssetObserver.php
  tests/Support/Settings.php
  tests/Unit/AssetTest.php
Labels: backend, api, tests

#13288 Added Inline markdown method
  app/Helpers/Helper.php
  app/Http/Transformers/AccessoriesTransformer.php
  app/Http/Transformers/ActionlogsTransformer.php
  app/Http/Transformers/AssetMaintenancesTransformer.php
  app/Http/Transformers/AssetModelsTransformer.php
  app/Http/Transformers/AssetsTransformer.php
  app/Http/Transformers/ComponentsTransformer.php
  app/Http/Transformers/ConsumablesTransformer.php
  app/Http/Transformers/LicensesTransformer.php
  app/Http/Transformers/SuppliersTransformer.php
  app/Http/Transformers/UsersTransformer.php
  app/Presenters/AssetModelPresenter.php
  resources/views/accessories/view.blade.php
  resources/views/asset_maintenances/view.blade.php
  resources/views/consumables/view.blade.php
  resources/views/hardware/view.blade.php
  resources/views/licenses/view.blade.php
  resources/views/suppliers/view.blade.php
  resources/views/users/view.blade.php
Labels: frontend, backend, consumables

#13184 User department now visible in side pane of asset view page
  resources/lang/en/admin/hardware/general.php
  resources/views/hardware/view.blade.php
Labels: frontend, translations

#13311 Fixed: deleted users showing in current users
  app/Http/Controllers/Api/UsersController.php
Labels: backend, api

#13315 Moved warranty into manufactuer’s section
  resources/views/hardware/view.blade.php
Labels: frontend

#13318 Fixed Employee Number no longer importing [sc-23497]
  app/Http/Livewire/Importer.php
Labels: backend, importer, livewire

#13322 Fix to ldap_location attribute
  app/Console/Commands/LdapSync.php
Labels: backend, ldap, cli / artisan

#13310 Fixed the inability to load location select when editing profile
  app/Http/Controllers/Api/LocationsController.php
  database/factories/UserFactory.php
  tests/Feature/Api/Locations/LocationsForSelectListTest.php
Labels: backend, api, tests

#13319 Added test cases around user search
  tests/Feature/Api/Users/UsersSearchTest.php
Labels: tests

#13333 Added strtolower for category type
  app/Helpers/Helper.php
Labels: backend

#13299 Update league/oauth2-server for CVE-2023-3726
  composer.json
Labels: backend, dependencies

#13197 Current value added to asset index page
  app/Http/Controllers/ReportsController.php
  app/Http/Transformers/AssetsTransformer.php
  app/Presenters/AssetPresenter.php
Labels: backend

#13342 Fixes #13341: Clean up correct seats on license delete
  app/Http/Controllers/Licenses/LicensesController.php
Labels: backend

#13344 Fixes bug/sc-23509: Added manufacturer back into license importer
  app/Http/Livewire/Importer.php
  app/Importer/LicenseImporter.php
Labels: backend, importer, livewire

#13349 Fixed: tighter check for valid model
  resources/lang/en/admin/models/message.php
  resources/views/hardware/view.blade.php
Labels: frontend, translations

#13347 Possible alternative to fixing #13296 - custom report failing when th…
  app/Models/Asset.php
Labels: backend

#12940 Delete button on asset view page
  app/Http/Controllers/Assets/AssetsController.php
  resources/lang/en/admin/hardware/general.php
  resources/lang/en/general.php
  resources/views/hardware/view.blade.php
Labels: frontend, backend, translations

#13363 Fixed #13298 "No records Found" when Switching between Single and Multi-Page Licenses
  app/Http/Controllers/Api/LicenseSeatsController.php
Labels: backend, api

#13361 Fixed custom fieldset order
  resources/views/custom_fields/fieldsets/view.blade.php
Labels: frontend, custom fields

#13379 Fixed #13376 Component checkout via API returns error
  app/Http/Controllers/Api/ComponentsController.php
Labels: backend, api

#13295 Fixed #11794 Admins Cannot View Encrypted Field
  app/Http/Transformers/AssetsTransformer.php
  app/Providers/AuthServiceProvider.php
  config/permissions.php
  resources/views/hardware/view.blade.php
  resources/views/models/custom_fields_form.blade.php
Labels: frontend, backend, custom fields

#13386 Updated BS table and table export plugins
  package-lock.json
  package.json
Labels: javascript, dependencies

#13309 Fixed #13300 Custom Asset Report, Checkout date range never includes current day
  app/Http/Controllers/ReportsController.php
Labels: backend
