Repository grokability/snipe-it, pull requests merged in 2024-02, with the labels that each got.

#14215 Removed initial check for assets, licenses, etc
  resources/views/companies/view.blade.php
Labels: frontend

#14216 Fixed company asset counts for dashboard widget
  app/Http/Controllers/Api/CompaniesController.php
Labels: backend, api

#14213 Fixed FD-40296 - mobile uploads sometimes uploading with incorrect orientation
  app/Http/Requests/ImageUploadRequest.php
Labels: backend

#14217 Upgrade bootstrap-table from 1.22.1 to 1.22.2 #14199
  package-lock.json
  package.json
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
Labels: frontend, javascript, css, dependencies, skins

#14218 Security upgrade alpine from 3.18.5 to 3.18.6 #14178
  Dockerfile.alpine
Labels: docker

#14190 Fixed consumable checkout via API not sending notification
  app/Http/Controllers/Api/ConsumablesController.php
  app/Http/Controllers/Consumables/ConsumableCheckoutController.php
  database/factories/ConsumableFactory.php
  tests/Feature/Api/Accessories/AccessoryCheckoutTest.php
  tests/Feature/Api/Consumables/ConsumableCheckoutTest.php
  tests/Feature/Checkouts/AccessoryCheckoutTest.php
  tests/Feature/Checkouts/ConsumableCheckoutTest.php
Labels: backend, consumables, api, tests

#13805 Use parseEscapedMarkedownInline for more views
  resources/views/components/view.blade.php
  resources/views/models/view.blade.php
Labels: frontend

#14219 Fixed #14185 - Resurfaced `load_remote` in admin
  app/Http/Controllers/SettingsController.php
  resources/lang/en-US/admin/settings/general.php
  resources/views/settings/general.blade.php
Labels: frontend, backend, translations

#14220 Removed loading of assets for label count
  resources/views/locations/view.blade.php
  resources/views/manufacturers/view.blade.php
  resources/views/models/view.blade.php
  resources/views/suppliers/view.blade.php
Labels: frontend

#14221 Chunk data to reduce memory on large datasets when updating `next_audit_date`
  app/Http/Controllers/SettingsController.php
Labels: backend

#14222 Added tests around getIdForCurrentUser method
  app/Models/Company.php
  tests/Unit/Models/Company/CompanyTest.php
  tests/Unit/Models/Company/GetIdForCurrentUserTest.php
Labels: backend, tests

#14227 Switch to bulk updating to handle audit interval updates
  app/Http/Controllers/SettingsController.php
Labels: backend

#14228 Fixed: 404 Error on Importer When Uploading a .csv Under Certain Circumstance
  resources/views/livewire/importer.blade.php
Labels: frontend, livewire

#14233 Fixes file upload XSS vulnerability [sc-24156]
  app/Http/Controllers/Accessories/AccessoriesFilesController.php
  app/Http/Controllers/AssetModelsFilesController.php
  app/Http/Controllers/Assets/AssetFilesController.php
  app/Http/Controllers/Components/ComponentsFilesController.php
  app/Http/Controllers/Consumables/ConsumablesFilesController.php
  app/Http/Controllers/Licenses/LicenseFilesController.php
  app/Http/Controllers/Users/UserFilesController.php
  app/Http/Requests/AssetFileRequest.php
  app/Http/Requests/ImageUploadRequest.php
  app/Http/Requests/UploadFileRequest.php
  resources/views/partials/forms/edit/image-upload.blade.php
Labels: frontend, backend, consumables

#14187 Fixed the general webhook not notifying anymore
  app/Listeners/CheckoutableListener.php
  app/Notifications/CheckinAccessoryNotification.php
  app/Notifications/CheckinAssetNotification.php
  app/Notifications/CheckinLicenseSeatNotification.php
  app/Notifications/CheckoutAccessoryNotification.php
  app/Notifications/CheckoutAssetNotification.php
  app/Notifications/CheckoutConsumableNotification.php
  app/Notifications/CheckoutLicenseSeatNotification.php
Labels: backend, notifications

#14229 Fixed select inputs un-select2-ifying on mobile
  resources/assets/js/snipeit.js
  resources/views/users/confirm-bulk-delete.blade.php
Labels: frontend, javascript, skins

#14240 Fixed barcodes crashing if asset was deleted
  app/Http/Controllers/Assets/AssetsController.php
  resources/views/users/view.blade.php
  routes/web/users.php
Labels: frontend, backend

#14241 Revert "Fixed barcodes crashing if asset was deleted"
  app/Http/Controllers/Assets/AssetsController.php
  resources/views/users/view.blade.php
  routes/web/users.php
Labels: frontend, backend

#14243 Fixed ReportsController to not try to return a serial if the item doesn’t exist
  app/Http/Controllers/ReportsController.php
Labels: backend

#14244 Return null if asset was hard-deleted/purged
  app/Http/Controllers/Assets/AssetsController.php
Labels: backend

#14188 Fixes Default Location Being Set During Asset Creation and Checkout
  app/Http/Controllers/Assets/AssetsController.php
Labels: backend

#14256 Fixed accessory check in emails being sent when setting disabled
  app/Notifications/CheckinAccessoryNotification.php
  database/factories/AccessoryFactory.php
  tests/Feature/Checkins/AccessoryCheckinTest.php
Labels: backend, notifications, tests

#14250 Cleaned up navbar-custom-menu
  resources/views/layouts/default.blade.php
Labels: frontend

#14236 Change how we check forward-looking upgrade requirements
  upgrade.php
Labels: backend, config

#14245 Fixes CVE-2024-24821 by upgrading composer/composer
  composer.lock
Labels: backend, dependencies

#14246 Fixes CVE-2022-24894 by upgrading symfony/http-kernel
  composer.lock
Labels: backend, dependencies

#14247 Fixes CVE-2023-37260 upgrading league/oauth2-server
  composer.lock
Labels: backend, dependencies

#14255 Added LDAP group tag to LDAP tests
  TESTING.md
  tests/Unit/LdapTest.php
Labels: ldap, tests

#14261 Fixed incorrect string for location not existing
  app/Http/Controllers/LocationsController.php
Labels: backend

#14264 Added serial and status label to asset maintenances page and API
  app/Http/Controllers/Api/AssetMaintenancesController.php
  app/Http/Controllers/AssetMaintenancesController.php
  app/Http/Transformers/AssetMaintenancesTransformer.php
  app/Models/Asset.php
  app/Models/AssetMaintenance.php
  app/Presenters/AssetMaintenancesPresenter.php
  resources/lang/en-US/general.php
  resources/views/hardware/view.blade.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend, api, translations

#14272 Updated testing helper name
  tests/Feature/Notifications/AccessoryWebhookTest.php
  tests/Feature/Notifications/AssetWebhookTest.php
  tests/Feature/Notifications/ComponentWebhookTest.php
  tests/Feature/Notifications/ConsumableWebhookTest.php
  tests/Feature/Notifications/LicenseWebhookTest.php
  tests/Support/Settings.php
Labels: tests

#14274 Upgrade alpinejs from 3.13.3 to 3.13.5
  package-lock.json
  package.json
Labels: javascript, dependencies

#14275 Upgrade webpack from 5.89.0 to 5.90.0
  package-lock.json
  package.json
Labels: javascript, dependencies

#14268 Fixed the notification listener
  app/Listeners/CheckoutableListener.php
Labels: backend

#14276 Fixed ambiguous query on supplier_id in maintenances
  app/Http/Controllers/Api/AssetMaintenancesController.php
Labels: backend, api

#14172 Resolve Duplicate Activity Logs for Imports
  app/Importer/AccessoryImporter.php
  app/Importer/AssetImporter.php
  app/Importer/ComponentImporter.php
  app/Importer/ConsumableImporter.php
  app/Importer/LicenseImporter.php
  app/Models/Actionlog.php
  app/Models/Loggable.php
  app/Observers/AccessoryObserver.php
  app/Observers/AssetObserver.php
  app/Observers/ComponentObserver.php
  app/Observers/ConsumableObserver.php
  app/Observers/LicenseObserver.php
  sample_csvs/components-sample.csv
Labels: backend, importer

#14197 Fixes #14010 Adds Components and Licenses logs to Assets history view
  app/Http/Controllers/Api/ReportsController.php
Labels: backend, api

#14277 Lower log level to warning on webhook failure
  app/Listeners/CheckoutableListener.php
Labels: backend

#14279 Improved UI for fieldsets
  resources/lang/en-US/general.php
  resources/views/custom_fields/fieldsets/view.blade.php
  resources/views/custom_fields/index.blade.php
Labels: frontend, custom fields, translations

#14278 Allowlist and db prefix for restore
  app/Console/Commands/RestoreFromBackup.php
  composer.json
Labels: backend, dependencies, backups, restore, cli / artisan

#14296 Better handle large downloads on backup API
  app/Http/Controllers/Api/SettingsController.php
Labels: backend, api

#14297 Added `/backups/latest` to API endpoint
  app/Http/Controllers/Api/SettingsController.php
  routes/api.php
Labels: backend, api

#14299 Check that the model exists before trying to access properties
  app/Http/Controllers/ReportsController.php
Labels: backend

#14301 Disallow branding uploads in demo mode
  app/Http/Controllers/SettingsController.php
  resources/views/partials/forms/edit/uploadLogo.blade.php
Labels: frontend, backend

#14302 Clean up the file extension on image file uploads
  app/Http/Requests/ImageUploadRequest.php
Labels: backend

#14304 Added ability to bulk delete locations
  app/Http/Controllers/Api/LocationsController.php
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/AssetModelsController.php
  app/Http/Controllers/LocationsController.php
  app/Http/Transformers/LocationsTransformer.php
  app/Models/Location.php
  app/Presenters/LocationPresenter.php
  app/Providers/SettingsServiceProvider.php
  resources/lang/en-US/general.php
  resources/views/locations/bulk-delete.blade.php
  resources/views/locations/index.blade.php
  resources/views/partials/bootstrap-table.blade.php
  resources/views/partials/locations-bulk-actions.blade.php
  resources/views/partials/models-bulk-actions.blade.php
  resources/views/users/view.blade.php
  routes/web.php
Labels: frontend, backend, api, translations

#14307 Fixed title not appearing in new label engine
  app/View/Label.php
Labels: backend

#14308 Eager load relations to determine deletability on locations
  app/Http/Controllers/LocationsController.php
  app/Models/Location.php
Labels: backend

#14192 Fixed #14183 API /hardware/:id/checkin doesn't return Licenses
  app/Http/Controllers/Api/AssetsController.php
Labels: backend, api

#14316 Added email, phone icons
  app/Http/Controllers/Api/UsersController.php
  app/Presenters/UserPresenter.php
  resources/lang/en-US/general.php
  resources/views/hardware/view.blade.php
  resources/views/partials/bootstrap-table.blade.php
  resources/views/users/view.blade.php
Labels: frontend, backend, api, translations

#14317 Made website searchable on users table
  app/Http/Controllers/Api/UsersController.php
  app/Models/User.php
Labels: backend, api

#14323 Fixes CVE-2024-25117 php-svg-lib lacks path validation on font through SVG inline styles
  composer.lock
Labels: backend, dependencies

#14321 Adding in PDF download to Accesories/Asset/License Histories
  resources/views/accessories/view.blade.php
  resources/views/hardware/view.blade.php
  resources/views/licenses/view.blade.php
Labels: frontend

#14319 Check for activeFile before trying to get header on import
  app/Http/Livewire/Importer.php
Labels: backend, importer, livewire

#14325 Check for valid supplier in license view
  resources/views/licenses/view.blade.php
Labels: frontend

#14327 Nicer UI for history importer
  app/Http/Controllers/Assets/AssetsController.php
  resources/lang/en-US/admin/hardware/general.php
  resources/views/hardware/history.blade.php
Labels: frontend, backend, translations

#14341 Generate unique department names in factory
  database/factories/DepartmentFactory.php
Labels: tests

#14335 Copy encrypted custom fields
  resources/views/hardware/view.blade.php
  resources/views/layouts/default.blade.php
Labels: frontend

#14344 Added created_by to groups table
  app/Http/Controllers/Api/GroupsController.php
  app/Http/Controllers/GroupsController.php
  app/Http/Transformers/GroupsTransformer.php
  app/Models/Group.php
  database/migrations/2024_02_28_080016_add_created_by_to_permission_groups.php
  resources/views/groups/index.blade.php
Labels: frontend, backend, api

#14346 Added `min_amt` functionality to licenses
  app/Helpers/Helper.php
  app/Http/Controllers/Api/LicensesController.php
  app/Http/Controllers/Licenses/LicensesController.php
  app/Http/Transformers/LicensesTransformer.php
  app/Models/License.php
  app/Presenters/LicensePresenter.php
  database/migrations/2024_02_28_093807_add_min_qty_to_licenses.php
  resources/lang/en-US/admin/licenses/general.php
  resources/views/licenses/edit.blade.php
  resources/views/licenses/view.blade.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend, api, translations

#14283 FIXED: Checked in Assets Did Not Show in Custom Report when Selecting a Valid Checked Out Date
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Assets/AssetCheckinController.php
  app/Http/Controllers/ReportsController.php
Labels: backend, api

#14281 Added better label previews with the new label engine
  app/Http/Controllers/LabelsController.php
Labels: backend

#14347 Dynamically show models/assets on requestable page
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Transformers/AssetsTransformer.php
  app/Presenters/AssetPresenter.php
  resources/lang/en-US/general.php
  resources/views/account/requestable-assets.blade.php
Labels: frontend, backend, api, translations
