Repository grokability/snipe-it, pull requests merged in 2024-01, with the labels that each got.

#13964 Tests For API Asset Store + Refactor For Auto Increment & Form Requests
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Assets/AssetsController.php
  app/Http/Requests/StoreAssetRequest.php
  app/Models/Asset.php
  database/factories/AssetFactory.php
  database/migrations/2023_07_13_052204_denormalized_eol_and_add_column_for_explicit_date_to_assets.php
  tests/Feature/Api/Assets/AssetStoreTest.php
  tests/Support/CustomTestMacros.php
  tests/Support/Settings.php
  tests/Unit/AssetModelTest.php
Labels: backend, api, tests

#14092 Syncs readme to DockerHub description
  .github/workflows/dockerhub-description.yml
Labels: config

#14095 Upgrade @fortawesome/fontawesome-free from 6.4.0 to 6.5.0
  package-lock.json
  package.json
Labels: javascript, dependencies

#14096 Upgrade jspdf-autotable from 3.5.31 to 3.8.0
  package.json
Labels: javascript, dependencies

#14101 Fixes creating invalid query with null values
  app/Http/Controllers/Api/AssetsController.php
Labels: backend, api

#14100 fixed `departmentNameLinkFormatter` url
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend

#14090 Run sqlite tests in GitHub action
  .github/workflows/tests-mysql.yml
  .github/workflows/tests-sqlite.yml
Labels: config

#14104 Move Google Login prompt higher, made it bigger
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/mix-manifest.json
  resources/assets/less/overrides.less
  resources/lang/en-US/auth/general.php
  resources/lang/en-US/general.php
  resources/views/auth/login.blade.php
Labels: frontend, css, skins, translations

#14108 Added supplier name as a searchable relation on the asset maintenance report
  app/Models/AssetMaintenance.php
Labels: backend

#14109 Moved contributors to dedicated file
  .all-contributorsrc
  CONTRIBUTORS.md
  README.md
  package-lock.json
  package.json
Labels: javascript, dependencies

#14115 Added license expiration date in "view asset"
  resources/views/hardware/view.blade.php
Labels: frontend

#14087 Fixes CVE-2023-51651 Potential URI resolution path traversal in the AWS SDK for PHP
  composer.lock
Labels: backend, dependencies

#14118 Search on supplier name attached to maintenance
  app/Models/AssetMaintenance.php
Labels: backend

#14121 Fixed multiple click checkouts for consumables, accessories and components
  resources/views/accessories/checkout.blade.php
  resources/views/components/checkout.blade.php
  resources/views/consumables/checkout.blade.php
  resources/views/layouts/default.blade.php
Labels: frontend, consumables

#14114 Fixed [FD-39640]: preserve sort order when generating asset labels
  app/Http/Controllers/Assets/BulkAssetsController.php
  resources/views/partials/asset-bulk-actions.blade.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#14144 Updated URL for apple manufacturer
  resources/lang/en-US/admin/manufacturers/message.php
Labels: translations

#14155 Fix for LDAP syncing with base_dn and location_id and location [FD-39651]
  app/Console/Commands/LdapSync.php
Labels: backend, ldap, cli / artisan

#14132 Improved radio button values in custom report form
  app/Http/Controllers/ReportsController.php
  resources/views/reports/custom.blade.php
Labels: frontend, backend

#14131 Adds translations for Label example
  app/Http/Controllers/LabelsController.php
  resources/lang/en-US/admin/companies/table.php
  resources/lang/en-US/admin/hardware/form.php
  resources/lang/en-US/admin/hardware/table.php
  resources/lang/en-US/admin/labels/table.php
  resources/lang/en-US/admin/locations/table.php
  resources/views/partials/label2-field-definitions.blade.php
Labels: frontend, backend, translations

#14158 Moved URL string to general
  resources/lang/en-US/admin/manufacturers/table.php
  resources/lang/en-US/admin/suppliers/table.php
  resources/lang/en-US/general.php
  resources/views/manufacturers/edit.blade.php
  resources/views/partials/label2-field-definitions.blade.php
  resources/views/reports/custom.blade.php
  resources/views/suppliers/edit.blade.php
  resources/views/suppliers/index.blade.php
Labels: frontend, translations

#14102 Fixed license seats id turning to zero when sorting by department
  app/Models/LicenseSeat.php
Labels: backend

#14159 Fixed english and attribute placeholder
  resources/lang/en-US/validation.php
Labels: translations

#14051 Email in License Seat Table
  app/Http/Transformers/LicenseSeatsTransformer.php
  app/Presenters/LicensePresenter.php
Labels: backend

#13924 Set qty mutators
  app/Models/Accessory.php
  app/Models/Component.php
  app/Models/Consumable.php
Labels: backend

#14058 Fixed Ldap sync test table and table data from overflowing
  resources/views/settings/ldap.blade.php
Labels: frontend, ldap

#14163 Added overflow scroll to ldap test table
  resources/views/settings/ldap.blade.php
Labels: frontend, ldap

#14162 Fixed #14114 - correctly sort related fields for labels
  app/Http/Controllers/Assets/BulkAssetsController.php
  resources/views/partials/asset-bulk-actions.blade.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#14164 Avoid unnecessarily hydrating models on asset show page
  app/Http/Controllers/AssetModelsController.php
  resources/views/models/view.blade.php
Labels: frontend, backend

#14153 Added support for Microsoft Teams Notifications
  app/Http/Livewire/SlackSettingsForm.php
  app/Listeners/CheckoutableListener.php
  app/Notifications/CheckinAccessoryNotification.php
  app/Notifications/CheckinAssetNotification.php
  app/Notifications/CheckinLicenseSeatNotification.php
  app/Notifications/CheckoutAccessoryNotification.php
  app/Notifications/CheckoutAssetNotification.php
  app/Notifications/CheckoutConsumableNotification.php
  app/Notifications/CheckoutLicenseSeatNotification.php
  composer.json
  composer.lock
  resources/lang/en-US/admin/settings/general.php
  resources/lang/en-US/mail.php
  resources/views/livewire/slack-settings-form.blade.php
Labels: frontend, backend, dependencies, livewire, notifications, translations

#14170 Enforce SAML assertion ID uniqueness and notValidOnOrAfter attribute [FD-37019]
  app/Console/Commands/SamlClearExpiredNonces.php
  app/Console/Kernel.php
  app/Http/Controllers/Auth/LoginController.php
  app/Models/SamlNonce.php
  app/Services/Saml.php
  database/migrations/2024_01_24_145544_create_saml_nonce_table.php
Labels: backend, saml, cli / artisan

#14171 Removed attribute assigning blank EOL as 0
  app/Models/AssetModel.php
  tests/Unit/AssetModelTest.php
Labels: backend, tests

#14175 Fixed #14173: Use new SnipeTranslator to handle pluralized localizations
  app/Providers/SnipeTranslationServiceProvider.php
  app/Services/SnipeTranslator.php
  config/app.php
Labels: backend

#14181 Fixed accessory checkout via API not sending notification and not adhering to qty limit
  app/Http/Controllers/Api/AccessoriesController.php
  database/factories/AccessoryFactory.php
  database/factories/CategoryFactory.php
  tests/Feature/Api/Accessories/AccessoryCheckoutTest.php
  tests/Feature/Checkouts/AccessoryCheckoutTest.php
Labels: backend, api, tests
