Repository grokability/snipe-it, pull requests merged in 2024-05, with the labels that each got.

#14655 Refactored due/overdue for audit, added due/overdue for checkin API endpoint and GUI
  app/Console/Commands/SendExpectedCheckinAlerts.php
  app/Console/Commands/SendUpcomingAuditReport.php
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Assets/AssetsController.php
  app/Http/Middleware/AssetCountForSidebar.php
  app/Models/Asset.php
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/mix-manifest.json
  resources/assets/less/mixins.less
  resources/assets/less/overrides.less
  resources/lang/en-US/general.php
  resources/views/hardware/audit-due.blade.php
  resources/views/hardware/audit-overdue.blade.php
  resources/views/hardware/checkin-due.blade.php
  resources/views/hardware/view.blade.php
  resources/views/layouts/default.blade.php
  resources/views/notifications/markdown/report-expected-checkins.blade.php
  routes/api.php
  routes/web/hardware.php
  tests/Feature/Api/Assets/AssetIndexTest.php
Labels: frontend, backend, css, api, skins, cli / artisan, translations, tests

#14391 Added Brother 18mm label type
  app/Models/Labels/Tapes/Brother/TZe_18mm.php
  app/Models/Labels/Tapes/Brother/TZe_18mm_A.php
Labels: backend, labels

#14679 Improve RTL support
  resources/views/layouts/default.blade.php
Labels: frontend

#14661 Upgrade tecnickcom/tcpdf from version 6.7.4 to 6.7.5 to address the security vulnerability CVE-2024-22640
  composer.lock
Labels: backend, dependencies

#14686 [Snyk] Upgrade alpinejs from 3.13.5 to 3.13.8 #14646
  package-lock.json
  package.json
Labels: javascript, dependencies

#14687 Upgrade fontawesome from 6.5.1 to 6.5.2
  package-lock.json
  package.json
  public/css/dist/all.css
  public/css/webfonts/fa-brands-400.ttf
  public/css/webfonts/fa-brands-400.woff2
  public/css/webfonts/fa-regular-400.ttf
  public/css/webfonts/fa-regular-400.woff2
  public/css/webfonts/fa-solid-900.ttf
  public/css/webfonts/fa-solid-900.woff2
  public/css/webfonts/fa-v4compatibility.ttf
  public/css/webfonts/fa-v4compatibility.woff2
  public/mix-manifest.json
Labels: frontend, javascript, css, dependencies, skins

#14688 [Snyk] Upgrade tableexport.jquery.plugin from 1.28.0 to 1.30.0 #14656
  package-lock.json
  package.json
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
Labels: frontend, javascript, dependencies, skins

#14690 Load settings in `SendUpcomingAuditReport` command
  app/Console/Commands/SendUpcomingAuditReport.php
Labels: backend, cli / artisan

#14693 Fixes #14692 - set default variables for sidebar totals
  app/Http/Middleware/AssetCountForSidebar.php
Labels: backend

#14702 Fixes #14701 - wrong total asset count
  app/Http/Middleware/AssetCountForSidebar.php
Labels: backend

#14697 Fixed UI where delete button was not disabled even if the user couldn't be deleted
  app/Http/Controllers/Api/UsersController.php
  app/Http/Transformers/UsersTransformer.php
  app/Models/User.php
  app/Presenters/UserPresenter.php
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/mix-manifest.json
  resources/assets/less/overrides.less
  resources/lang/en-US/admin/users/table.php
  resources/views/users/view.blade.php
  tests/Feature/Api/Users/UsersDeleteTest.php
Labels: frontend, backend, css, api, skins, translations, tests

#14711 Fix memory-hog query in AssetCountForSidebar middleware
  app/Http/Middleware/AssetCountForSidebar.php
Labels: backend

#14707 Bulk Edit Tests and Tweaks
  app/Http/Controllers/Assets/BulkAssetsController.php
  database/factories/AssetFactory.php
  database/factories/AssetModelFactory.php
  database/factories/CustomFieldsetFactory.php
  resources/views/hardware/bulk.blade.php
  tests/Feature/Assets/AssetsBulkEditTest.php
Labels: frontend, backend, custom fields, tests

#14700 Updated alpine to the latest version (3.13.10)
  package-lock.json
  package.json
  resources/views/partials/label2-field-definitions.blade.php
Labels: frontend, javascript, dependencies

#14451 Adds a note text area to asset acceptances/declines
  app/Http/Controllers/Account/AcceptanceController.php
  app/Listeners/LogListener.php
  app/Models/CheckoutAcceptance.php
  app/Notifications/AcceptanceAssetAcceptedNotification.php
  app/Notifications/AcceptanceAssetDeclinedNotification.php
  database/migrations/2024_03_18_164714_add_note_to_checkout_acceptance_table.php
  resources/lang/en-US/admin/settings/general.php
  resources/lang/en-US/general.php
  resources/views/account/accept/create.blade.php
  resources/views/notifications/markdown/asset-acceptance.blade.php
Labels: frontend, backend, notifications, translations

#14728 Only attempt to decrypt custom fields in activity log if the value is not empty
  app/Http/Transformers/ActionlogsTransformer.php
Labels: backend

#14719 Added next audit date to assets form
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Assets/AssetsController.php
  app/Models/Asset.php
  resources/lang/en-US/admin/hardware/message.php
  resources/lang/en-US/general.php
  resources/views/hardware/audit.blade.php
  resources/views/hardware/bulk.blade.php
  resources/views/hardware/edit.blade.php
  resources/views/hardware/quickscan.blade.php
  resources/views/hardware/view.blade.php
  resources/views/partials/forms/edit/image-upload.blade.php
  tests/Feature/Assets/AssetsBulkEditTest.php
Labels: frontend, backend, api, translations, tests

#14729 Sets purchase date as date (versus datetime) in labels
  app/Models/Labels/FieldOption.php
Labels: backend

#14731 Fixed #14664 - allow additional urls in env for CSP
  .env.example
  app/Http/Middleware/SecurityHeaders.php
  config/app.php
Labels: backend

#14736 Small translation additions
  app/Http/Controllers/ProfileController.php
  resources/lang/en-US/account/general.php
  resources/lang/en-US/table.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend, translations

#14741 removed extra div tags
  resources/views/settings/index.blade.php
Labels: frontend

#14745 Refactor group syncing on user edit API endpoint
  app/Http/Controllers/Api/UsersController.php
  resources/views/groups/view.blade.php
  tests/Feature/Api/Users/UpdateUserApiTest.php
Labels: frontend, backend, api, tests

#14752 Nicer handling of erroring when filename+log do not match
  app/Http/Controllers/Users/UserFilesController.php
Labels: backend

#14762 Fixed test by removing non-existent trait
  .github/workflows/tests-sqlite.yml
  tests/Feature/Settings/BrandingSettingsTest.php
Labels: config, tests

#14767 Improved translations
  resources/lang/en-US/general.php
  resources/views/hardware/checkin.blade.php
  resources/views/layouts/default.blade.php
  resources/views/partials/bootstrap-table.blade.php
  resources/views/reports/custom.blade.php
Labels: frontend, translations

#14766 Changed icon, added translation
  resources/views/custom_fields/fieldsets/view.blade.php
Labels: frontend, custom fields, translations

#14755 Added tests around asset checkout
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Requests/AssetCheckoutRequest.php
  database/factories/LicenseSeatFactory.php
  database/factories/StatuslabelFactory.php
  tests/Feature/Api/Assets/AssetCheckoutTest.php
  tests/Feature/Checkouts/AssetCheckoutTest.php
  tests/Unit/Listeners/LogListenerTest.php
Labels: backend, api, tests

#14773 Pass accessory's currency if set by location
  resources/views/accessories/edit.blade.php
Labels: frontend

#14775 Fixed #14771: improvements to groups API
  app/Helpers/Helper.php
  app/Http/Controllers/Api/GroupsController.php
  app/Models/Group.php
  tests/Feature/Api/Groups/GroupStoreTest.php
Labels: backend, api, tests

#14777 Reports controller query optimizations
  app/Http/Controllers/Api/ReportsController.php
  app/Http/Transformers/ActionlogsTransformer.php
  app/Models/Asset.php
Labels: backend, api

#14779 Fixed Array to string conversion exception in group create api endpoint
  app/Http/Controllers/Api/GroupsController.php
  tests/Feature/Api/Groups/GroupStoreTest.php
Labels: backend, api, tests

#14780 Fixed sqlite tests in GitHub Actions
  .github/workflows/tests-sqlite.yml
Labels: config

#14782 Reduce IDE errors in App\Http\Controllers\SettingsController
  app/Http/Controllers/SettingsController.php
Labels: backend

#14778 Allows Snipe-ITv7 to install on PHPv8.1-8.3
  composer.json
  composer.lock
Labels: backend, dependencies

#14783 Fixed deprecation warning on category test
  tests/Unit/CategoryTest.php
Labels: tests

#14349 Update mailer configurations for Symfony mailer
  .env.docker
  .env.dusk.example
  .env.example
  .env.testing-ci
  .env.tests
  .env.unit-tests
  app.json
  config/mail.php
  docker/docker-secrets.env
  docker/docker.env
  phpunit.xml
  snipeit.sh
Labels: docker

#14754 Removed extra div from User Details.
  resources/views/users/view.blade.php
Labels: frontend

#14786 #14743 - Upgrade bootstrap-table from 1.22.3 to 1.22.5
  package-lock.json
  package.json
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/js/build/app.js.LICENSE.txt
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
Labels: frontend, javascript, css, dependencies, skins

#14787 Fixes path for redirect response
  app/Http/Controllers/Accessories/AccessoriesController.php
  app/Http/Controllers/Accessories/AccessoryCheckinController.php
  app/Http/Controllers/Accessories/AccessoryCheckoutController.php
  app/Http/Controllers/Account/AcceptanceController.php
  app/Http/Controllers/Api/AccessoriesController.php
  app/Http/Controllers/Api/CustomFieldsController.php
  app/Http/Controllers/Api/CustomFieldsetsController.php
  app/Http/Controllers/AssetModelsController.php
  app/Http/Controllers/AssetModelsFilesController.php
  app/Http/Controllers/Assets/AssetCheckinController.php
  app/Http/Controllers/Assets/AssetCheckoutController.php
  app/Http/Controllers/Assets/AssetFilesController.php
  app/Http/Controllers/Assets/AssetsController.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/SamlController.php
  app/Http/Controllers/BulkAssetModelsController.php
  app/Http/Controllers/CustomFieldsetsController.php
  app/Http/Controllers/Kits/CheckoutKitController.php
  app/Http/Controllers/Kits/PredefinedKitsController.php
  app/Http/Controllers/ManufacturersController.php
  app/Http/Controllers/ProfileController.php
  app/Http/Controllers/SettingsController.php
  app/Http/Controllers/ViewAssetsController.php
Labels: backend, custom fields, api, saml

#14788 Updated jquery-UI
  package-lock.json
  package.json
Labels: javascript, dependencies

#13062 Bulk Consumable Checkout
  app/Http/Controllers/Consumables/ConsumableCheckoutController.php
  resources/views/consumables/checkout.blade.php
Labels: frontend, backend, consumables

#14795 Upgraded papaparse
  package-lock.json
  package.json
Labels: javascript, dependencies

#14796 Upgraded axios
  package-lock.json
  package.json
Labels: javascript, dependencies

#14614 ADDED: Export User Permissions (Superuser & Admin)
  app/Http/Controllers/Users/UsersController.php
  resources/lang/am-ET/general.php
Labels: backend, translations

#14799 Removed unused Livewire component
  app/Http/Livewire/LoginForm.php
  resources/views/livewire/login-form.blade.php
Labels: frontend, backend, livewire

#14797 Added test for setup page
  tests/Feature/Settings/ShowSetUpPageTest.php
Labels: tests

#14808 Small UI tweaks and redirects when asset model is invalid
  app/Http/Controllers/Assets/AssetCheckinController.php
  app/Http/Controllers/Assets/AssetCheckoutController.php
  resources/lang/en-US/admin/hardware/general.php
  resources/views/hardware/audit.blade.php
  resources/views/hardware/checkin.blade.php
  resources/views/hardware/checkout.blade.php
  resources/views/hardware/view.blade.php
  resources/views/notifications.blade.php
  resources/views/partials/forms/redirect_submit_options.blade.php
  tests/Feature/Checkins/AssetCheckinTest.php
  tests/Feature/Checkouts/AssetCheckoutTest.php
Labels: frontend, backend, translations, tests
