Repository grokability/snipe-it, pull requests merged in 2024-08, with the labels that each got.

#15211 Fixed #15205 - adds copy to asset tag
  resources/views/hardware/view.blade.php
Labels: frontend

#15217 Feature: Extend search capabilities to other assets attributes
  app/Http/Controllers/Assets/AssetsController.php
  resources/views/hardware/index.blade.php
Labels: frontend, backend

#15229 Disallowed checking out components to different companies and fixed number remaining counts
  app/Http/Controllers/Components/ComponentCheckoutController.php
  app/Models/Component.php
  tests/Feature/Checkouts/Ui/ComponentsCheckoutTest.php
  tests/Unit/ComponentTest.php
Labels: backend, tests

#15241 Partial revert for checkout accessories to non user
  app/Http/Controllers/CheckInOutRequest.php
  resources/views/accessories/checkout.blade.php
Labels: frontend, backend

#15242 Fixed shortcuts to be optional now
  app/Http/Controllers/SettingsController.php
  database/migrations/2024_08_06_175114_add_shortcuts_enabled_to_settings_table.php
  resources/lang/en-US/admin/settings/general.php
  resources/views/accessories/index.blade.php
  resources/views/components/index.blade.php
  resources/views/consumables/index.blade.php
  resources/views/hardware/index.blade.php
  resources/views/layouts/default.blade.php
  resources/views/partials/asset-bulk-actions.blade.php
  resources/views/partials/forms/edit/submit.blade.php
  resources/views/settings/general.blade.php
  resources/views/users/index.blade.php
Labels: frontend, backend, consumables, translations

#15244 Fixes #10560 - optional ability to play sound on audit
  app/Http/Controllers/ProfileController.php
  database/migrations/2024_08_07_204014_add_play_sounds_to_profile.php
  public/sounds/error.mp3
  public/sounds/success.mp3
  resources/lang/en-US/account/general.php
  resources/views/account/profile.blade.php
  resources/views/hardware/quickscan.blade.php
Labels: frontend, backend, translations

#15245 Fixed Issue with Acceptances Being Created
  app/Listeners/CheckoutableListener.php
Labels: backend

#15232 Updated PHPUnit to v10
  .gitignore
  composer.json
  composer.lock
  phpunit.xml
  tests/Feature/Checkouts/Api/AssetCheckoutTest.php
  tests/Feature/Checkouts/Ui/AssetCheckoutTest.php
  tests/Feature/Notifications/Email/EmailNotificationsUponCheckinTest.php
  tests/Feature/Notifications/Webhooks/SlackNotificationsUponCheckinTest.php
  tests/Feature/Notifications/Webhooks/SlackNotificationsUponCheckoutTest.php
  tests/Feature/Settings/ShowSetUpPageTest.php
  tests/Unit/CompanyScopingTest.php
  tests/Unit/LdapTest.php
Labels: backend, ldap, dependencies, tests

#15221 Fixed accessories and consumables not being logged correctly during bulk check-in
  app/Http/Controllers/Users/BulkUsersController.php
  tests/Feature/Users/Ui/BulkActions/BulkDeleteUsersTest.php
Labels: backend, tests

#15261 [Snyk] Upgrade @fortawesome/fontawesome-free from 6.5.2 to 6.6.0
  package-lock.json
  package.json
  public/css/build/AdminLTE.css
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/css/dist/signature-pad.min.css
  public/css/dist/skins/_all-skins.css
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/css/dist/skins/skin-black.css
  public/css/dist/skins/skin-black.min.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-blue.css
  public/css/dist/skins/skin-blue.min.css
  public/css/dist/skins/skin-contrast.css
  public/css/dist/skins/skin-contrast.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-green.css
  public/css/dist/skins/skin-green.min.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-orange.css
  public/css/dist/skins/skin-orange.min.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-purple.css
  public/css/dist/skins/skin-purple.min.css
  public/css/dist/skins/skin-red-dark.css
  public/css/dist/skins/skin-red-dark.min.css
  public/css/dist/skins/skin-red.css
  public/css/dist/skins/skin-red.min.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/css/dist/skins/skin-yellow.css
  public/css/dist/skins/skin-yellow.min.css
  public/css/webfonts/fa-brands-400.ttf
  public/css/webfonts/fa-brands-400.woff2
  public/css/webfonts/fa-regular-400.ttf
  public/css/webfonts/fa-regular-400.woff2
  public/css/webfonts/fa-solid-900.ttf
  public/css/webfonts/fa-solid-900.woff2
  public/css/webfonts/fa-v4compatibility.ttf
  public/css/webfonts/fa-v4compatibility.woff2
  public/js/build/app.js
  public/js/build/vendor.js
  public/js/dist/all.js
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
Labels: frontend, javascript, css, dependencies, skins

#15262 Upgrade jquery-validation from 1.20.1 to 1.21.0
  package-lock.json
  package.json
  public/css/dist/skins/_all-skins.min.css
  public/js/build/vendor.js
  public/js/dist/all.js
  public/mix-manifest.json
Labels: frontend, javascript, css, dependencies, skins

#15263 Fixed #15248 Removed pound symbol from order number on asset view
  resources/views/hardware/view.blade.php
Labels: frontend

#15264 Fixed #15252 - admin ordering on activity report
  app/Http/Controllers/Api/ReportsController.php
  app/Models/Actionlog.php
  app/Models/Asset.php
  resources/views/reports/activity.blade.php
  tests/Feature/Assets/Api/StoreAssetTest.php
  tests/Feature/Assets/Ui/BulkEditAssetsTest.php
  tests/Feature/Reporting/ActivityReportTest.php
Labels: frontend, backend, api, tests

#15100 Added Depreciation Percentage as an option
  app/Http/Controllers/Api/DepreciationsController.php
  app/Http/Controllers/DepreciationsController.php
  app/Http/Transformers/DepreciationsTransformer.php
  app/Models/Depreciable.php
  database/migrations/2024_07_16_184145_add_deprecitation_type_to_depreciations_table.php
  resources/lang/en-US/validation.php
  resources/views/depreciations/edit.blade.php
  tests/Unit/DepreciationTest.php
Labels: frontend, backend, api, translations, tests

#15269 Fixes ##15236 - smaller email logo
  resources/views/vendor/mail/html/message.blade.php
Labels: frontend

#15266 Checkout-to fixer
  app/Console/Commands/FixupAssignedToWithoutAssignedType.php
  tests/Feature/Console/FixupAssignedToAssignedTypeTest.php
Labels: backend, cli / artisan, tests

#15272 Added reporting-only access for selectlists
  app/Providers/AuthServiceProvider.php
Labels: backend

#15275 Added tooltips to top nav shortcuts
  resources/views/layouts/default.blade.php
Labels: frontend

#15198 Add MayContainCustomFields Trait to Asset Update Request
  app/Http/Requests/Traits/MayContainCustomFields.php
  app/Http/Requests/UpdateAssetRequest.php
  tests/Feature/Assets/Api/UpdateAssetTest.php
Labels: backend, custom fields, tests

#15278 Fixed #14821 - Hide UI elements from print view on assets
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/mix-manifest.json
  resources/assets/less/overrides.less
  resources/views/hardware/view.blade.php
  resources/views/partials/more-info.blade.php
Labels: frontend, css, skins

#15277 Fixed: [sc-26355] Attempt to de-escalate SAML login and logout errors
  app/Http/Controllers/Auth/SamlController.php
  app/Services/Saml.php
Labels: backend, saml

#15279 Fix: add missing admin/hardware/table.name key
  resources/views/hardware/bulk-delete.blade.php
Labels: frontend, translations

#15280 Fixed select2 “x” color on multi-select and border color
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/mix-manifest.json
  resources/assets/less/overrides.less
Labels: frontend, css, skins

#15192 Added status labels to confirmation emails
  app/Http/Controllers/Account/AcceptanceController.php
  app/Notifications/AcceptanceAssetAcceptedNotification.php
  app/Notifications/AcceptanceAssetDeclinedNotification.php
  app/Notifications/CheckinAssetNotification.php
  app/Notifications/CheckoutAssetNotification.php
  resources/views/notifications/markdown/asset-acceptance.blade.php
  resources/views/notifications/markdown/checkin-asset.blade.php
  resources/views/notifications/markdown/checkout-asset.blade.php
Labels: frontend, backend, notifications

#15291 Added asset name to bulk asset edit
  app/Http/Controllers/Assets/BulkAssetsController.php
  resources/views/hardware/bulk.blade.php
  tests/Feature/Assets/Ui/BulkEditAssetsTest.php
Labels: frontend, backend, tests

#15292 Updated phpinsights
  composer.json
  composer.lock
Labels: backend, dependencies

#15303 Fixed #15301 - Added optional status to quickscan checkin
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Assets/AssetsController.php
  resources/lang/en-US/general.php
  resources/views/hardware/quickscan-checkin.blade.php
  resources/views/hardware/quickscan.blade.php
Labels: frontend, backend, api, translations

#15304 Added confetti option
  app/Http/Controllers/ProfileController.php
  database/migrations/2024_08_15_111816_add_confetti_to_users.php
  package-lock.json
  package.json
  public/js/build/app.js
  public/js/dist/all.js
  public/mix-manifest.json
  resources/lang/en-US/account/general.php
  resources/views/account/profile.blade.php
  resources/views/notifications.blade.php
  resources/views/partials/confetti-js.blade.php
  webpack.mix.js
Labels: frontend, backend, javascript, dependencies, skins, translations

#15314 Added #15312: Add checkin due in days setting
  app/Http/Controllers/SettingsController.php
  app/Models/Asset.php
  resources/lang/en-US/admin/settings/general.php
  resources/views/hardware/checkin-due.blade.php
  resources/views/settings/alerts.blade.php
Labels: frontend, backend, translations

#15282 Added support for Docker secrets in Standard and alpine image.
  docker/entrypoint_alpine.sh
  docker/startup.sh
Labels: docker

#15206 Fixed dashboard box overflow
  resources/assets/less/overrides.less
  resources/views/dashboard.blade.php
  resources/views/settings/index.blade.php
Labels: frontend, css, skins

#15318 Corrected some translations
  app/Http/Controllers/Api/PredefinedKitsController.php
  app/Http/Controllers/Kits/CheckoutKitController.php
  app/Http/Kernel.php
  app/Http/Transformers/AssetsTransformer.php
  resources/lang/en-US/admin/kits/general.php
  resources/lang/en-US/general.php
  resources/views/account/view-assets.blade.php
  resources/views/categories/view.blade.php
  resources/views/hardware/checkin.blade.php
  resources/views/hardware/checkout.blade.php
  resources/views/settings/logins.blade.php
  resources/views/users/print.blade.php
Labels: frontend, backend, api, translations

#15324 Prevent passing an array as login
  app/Http/Controllers/Auth/LoginController.php
  resources/views/auth/login.blade.php
Labels: frontend, backend

#15336 Fixed `)` being added to expected asset checkin report email header
  resources/views/vendor/mail/html/message.blade.php
Labels: frontend

#15112 Improved handling attempted access of deleted files in importer
  app/Livewire/Importer.php
  database/factories/UserFactory.php
  resources/lang/en-US/admin/hardware/message.php
  resources/views/livewire/importer.blade.php
  tests/Feature/Livewire/ImporterTest.php
Labels: frontend, backend, livewire, translations, tests

#15342 [Snyk] Upgrade bootstrap-table from 1.23.0 to 1.23.2
  package-lock.json
  package.json
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/js/dist/bootstrap-table-en-US.min.js
  public/js/dist/bootstrap-table-locale-all.min.js
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
Labels: frontend, javascript, css, dependencies, skins

#15345 Added TrimStrings middleware
  app/Http/Kernel.php
Labels: backend

#15350 Fixed icon not rotated and simplified component
  resources/views/blade/icon.blade.php
Labels: frontend

#15356 Fixed #15341 - validate parent ID
  app/Models/Location.php
  tests/Feature/Locations/Ui/CreateLocationsTest.php
  tests/Feature/Locations/Ui/UpdateLocationsTest.php
Labels: backend, tests

#15357 Fixed #15330 - Cleaned up category title
  resources/lang/en-US/general.php
  resources/views/categories/view.blade.php
Labels: frontend, translations

#15358 Renamed docker startup scripts coherently.
  Dockerfile.alpine
  Dockerfile.fpm-alpine
  docker/startup_alpine.sh
  docker/startup_alpine_fpm.sh
Labels: docker

#15362 Added #9413: AssetModel files endpoints to API
  app/Http/Controllers/Api/AssetModelFilesController.php
  resources/lang/en-GB/admin/models/message.php
  routes/api.php
  tests/Feature/AssetModels/Api/AssetModelFilesTest.php
Labels: backend, api, translations, tests

#15367 Fixed #15344 - make select2 for countries freeform-ish
  resources/lang/en-US/general.php
  resources/lang/en-US/localizations.php
  resources/macros/macros.php
  resources/views/partials/forms/edit/address.blade.php
  resources/views/users/edit.blade.php
  resources/views/users/view.blade.php
Labels: frontend, translations

#15360 More print fixes for asset view
  resources/views/hardware/view.blade.php
Labels: frontend

#15352 Fixed Mobile misalignment of info on Assets and Users view pages
  resources/assets/less/overrides.less
  resources/views/hardware/view.blade.php
  resources/views/users/view.blade.php
Labels: frontend, css, skins

#15296 Expose the 'sanitize' system for backup restores to the web GUI
  .env.example
  app/Http/Controllers/SettingsController.php
  config/backup.php
  resources/assets/js/snipeit.js
  resources/lang/en-US/admin/settings/general.php
  resources/views/settings/backups.blade.php
Labels: frontend, backend, javascript, skins, backups, translations

#15369 Fixed checkbox layout on modal from #15296
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/js/build/app.js
  public/js/dist/all.js
  public/mix-manifest.json
  resources/assets/less/overrides.less
  resources/views/settings/backups.blade.php
Labels: frontend, javascript, css, skins, backups

#15156 Re-add stalebot-esque github Action
  .github/stale.yml
  .github/workflows/stale.yml
Labels: config

#15065 Adds `snipeit:remove-explicit-eols` command
  app/Console/Commands/RemoveExplicitEols.php
Labels: backend, cli / artisan

#14667 Adds location select to the create new user via asset checkout
  resources/views/modals/user.blade.php
Labels: frontend

#15373 Fixed #15366 use the non-admin edit encrypted custom fields permissions
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/Assets/AssetsController.php
Labels: backend, api

#15379 fixed #15374: load TrustProxies middleware in Kernel.php
  app/Http/Kernel.php
Labels: backend

#15377 Fixed custom field defaults being prematurely updated
  app/Http/Controllers/AssetModelsController.php
  tests/Feature/AssetModels/Ui/UpdateAssetModelsTest.php
Labels: backend, tests

#15380 Added pull-right to angle bracket
  resources/views/layouts/default.blade.php
Labels: frontend

#15375 Fixes the `acceptance-reminder` command
  app/Console/Commands/SendAcceptanceReminder.php
Labels: backend, cli / artisan

#15383 Fixed #15378 - Corrected gate on checkin button on asset view
  resources/views/hardware/view.blade.php
Labels: frontend

#15389 Fixed #15388 - Moved generate label button
  resources/views/hardware/view.blade.php
  resources/views/users/view.blade.php
Labels: frontend

#15396 Added `start_date` and `end_date` to user bulk edit
  app/Http/Controllers/Users/BulkUsersController.php
  resources/lang/en-US/general.php
  resources/views/hardware/bulk.blade.php
  resources/views/users/bulk-edit.blade.php
Labels: frontend, backend, translations

#15401 Opens label new window
  resources/views/hardware/view.blade.php
Labels: frontend

#15404 Set image to null if model is deleted
  app/Http/Controllers/AssetModelsController.php
Labels: backend

#15408 Check that the user exists before trying to print
  app/Http/Controllers/Users/UsersController.php
Labels: backend

#15409 Corrected language string
  resources/lang/en-US/admin/locations/message.php
Labels: translations

#15410 Updated jquery UI
  package-lock.json
  package.json
  public/js/build/app.js
  public/js/build/vendor.js
  public/js/dist/all.js
  public/mix-manifest.json
Labels: frontend, javascript, dependencies, skins

#15411 Upgraded webpack
  package-lock.json
  package.json
Labels: javascript, dependencies

#15284 [Multi-Company] Fixes Users Being Moved With Items Still Assigned
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/Users/UsersController.php
  app/Http/Requests/SaveUserRequest.php
  resources/lang/en-US/admin/users/message.php
  resources/views/users/edit.blade.php
  routes/api.php
  routes/web/users.php
  tests/Feature/Users/Api/UpdateUserTest.php
  tests/Feature/Users/Ui/UpdateUserTest.php
Labels: frontend, backend, api, translations, tests

#15412 Fix [FD-43836] PATCH of purchase_cost for assets for comma as decimal separator
  app/Http/Requests/UpdateAssetRequest.php
  app/Models/SnipeModel.php
  tests/Feature/Assets/Api/UpdateAssetTest.php
Labels: backend, tests

#15414 Use the null-safe property accessor for new-user creation
  app/Http/Requests/SaveUserRequest.php
Labels: backend

#15418 Fixed #15416 - Added multiple selects for custom report
  app/Models/Asset.php
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/mix-manifest.json
  resources/assets/less/overrides.less
  resources/lang/en-US/localizations.php
  resources/macros/macros.php
  resources/views/partials/forms/edit/category-select.blade.php
  resources/views/partials/forms/edit/company-select.blade.php
  resources/views/partials/forms/edit/department-select.blade.php
  resources/views/partials/forms/edit/location-select.blade.php
  resources/views/partials/forms/edit/manufacturer-select.blade.php
  resources/views/partials/forms/edit/model-select.blade.php
  resources/views/partials/forms/edit/status-select.blade.php
  resources/views/partials/forms/edit/supplier-select.blade.php
  resources/views/reports/custom.blade.php
  resources/views/users/edit.blade.php
Labels: frontend, backend, css, skins, translations

#15415 Validation rules to prevent switching user companies if items are assigned to them
  app/Http/Requests/SaveUserRequest.php
  app/Rules/UserCannotSwitchCompaniesIfItemsAssigned.php
Labels: backend
