Repository grokability/snipe-it, pull requests merged in 2024-06, with the labels that each got.

#14809 Added a few more tests
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/Users/UsersController.php
  resources/lang/en-US/admin/users/message.php
  tests/Feature/Api/Users/DeleteUsersTest.php
  tests/Feature/Api/Users/UsersDeleteTest.php
  tests/Feature/Users/DeleteUsersTest.php
Labels: backend, api, translations, tests

#14817 Fixes #14815 - Fixed translation string
  app/Http/Controllers/Api/LocationsController.php
  resources/lang/en-US/admin/locations/message.php
Labels: backend, api, translations

#14758 add logo support for Brother TZe24mm labels
  app/Models/Labels/Tapes/Brother/TZe_24mm_B.php
  app/Models/Labels/Tapes/Brother/TZe_24mm_C.php
Labels: backend

#14827 fix(ActionlogController): correct signature image for s3 bucket
  app/Http/Controllers/ActionlogController.php
Labels: backend

#14824 Fixed select 2 Behavior
  resources/views/partials/forms/redirect_submit_options.blade.php
Labels: frontend

#14807 Added test for .env visibility for setup page
  app/Http/Controllers/SettingsController.php
  tests/Feature/Settings/ShowSetUpPageTest.php
Labels: backend, tests

#14828 fix(ActionlogController): add missin class Illuminate\Support\Facades…
  app/Http/Controllers/ActionlogController.php
Labels: backend

#14832 Fixed #14812 - added consumables to individual inventory report
  app/Console/Commands/SendCurrentInventoryToUsers.php
  app/Notifications/CurrentInventory.php
  resources/views/notifications/markdown/user-inventory.blade.php
Labels: frontend, backend, cli / artisan, notifications

#14842 Fixed label preview window position
  resources/views/partials/label2-preview.blade.php
  resources/views/settings/labels.blade.php
Labels: frontend

#14830 Better validation for relations on delete
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/Users/UsersController.php
  app/Http/Requests/DeleteUserRequest.php
  tests/Feature/Users/Ui/DeleteUserTest.php
Labels: backend, api, tests

#14847 Optimization for listings of large numbers of users
  app/Http/Controllers/Api/UsersController.php
Labels: backend, api

#14843 Added GitHub workflow for tests in Postgres
  .github/workflows/tests-postgres.yml
Labels: config

#14834 Added test for app url config
  app/Http/Controllers/SettingsController.php
  tests/Feature/Settings/ShowSetUpPageTest.php
Labels: backend, tests

#14801 Allow CompanyableTrait trait on users
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/Users/UsersController.php
  app/Models/Company.php
  app/Models/User.php
  resources/views/users/print.blade.php
  tests/Feature/Users/Api/DeleteUserTest.php
  tests/Feature/Users/Api/ViewUserTest.php
  tests/Feature/Users/Ui/DeleteUserTest.php
  tests/Feature/Users/Ui/ViewUserTest.php
Labels: frontend, backend, api, tests

#14800 Importer tweaks
  app/Http/Livewire/Importer.php
  app/Importer/AssetImporter.php
  app/Importer/Importer.php
  app/Importer/ItemImporter.php
  app/Models/Asset.php
  resources/views/hardware/view.blade.php
  resources/views/livewire/importer.blade.php
  tests/Feature/Assets/Api/StoreAssetTest.php
Labels: frontend, backend, importer, livewire, tests

#14871 Moved `AssetFilesTest`
  tests/Feature/Assets/Api/AssetFilesTest.php
Labels: tests

#14876 Fixed small footer issues
  resources/views/dashboard.blade.php
  resources/views/settings/backups.blade.php
  resources/views/settings/general.blade.php
Labels: frontend, backups

#14877 Updated config
  config/backup.php
Labels: backups

#14879 Fixed weird layout in admin oauth [sc-25673]
  resources/lang/en-US/admin/settings/general.php
  resources/views/livewire/oauth-clients.blade.php
  resources/views/models/bulk-delete.blade.php
Labels: frontend, livewire, translations

#14884 Fixed missing `}`
  app/Http/Controllers/ActionlogController.php
Labels: backend

#14885 Added more tests around Asset Model
  tests/Feature/AssetModels/Ui/AssetModelIndexTest.php
  tests/Feature/AssetModels/Ui/AssetModelStoreTest.php
  tests/Feature/AssetModels/Ui/AssetModelsTest.php
Labels: tests

#14887 Fixed namespace for ViewUserTest
  tests/Feature/Users/Ui/ViewUserTest.php
Labels: tests

#14886 Bumped debugbar from v3.13.0 to v3.13.5 to fix issue with session messages
  composer.json
  composer.lock
Labels: backend, dependencies

#14894 Fixed #14882 - Properly scope archived based on settings
  app/Http/Controllers/AssetModelsController.php
  resources/views/models/view.blade.php
Labels: frontend, backend

#14900 Fixed unable to install on PHP 8.1
  composer.lock
Labels: backend, dependencies

#14896 Possible fix for proxy/reverse proxy
  app/Providers/AppServiceProvider.php
Labels: backend

#14908 Fixes/importer audit date
  app/Importer/AssetImporter.php
  app/Models/Asset.php
Labels: backend, importer

#14920 Fixed backup notification translations
  composer.json
  composer.lock
  config/app.php
  config/backup.php
  resources/lang/vendor/backup/ar/notifications.php
  resources/lang/vendor/backup/bg/notifications.php
  resources/lang/vendor/backup/bn/notifications.php
  resources/lang/vendor/backup/cs/notifications.php
  resources/lang/vendor/backup/da/notifications.php
  resources/lang/vendor/backup/de/notifications.php
  resources/lang/vendor/backup/en/notifications.php
  resources/lang/vendor/backup/es/notifications.php
  resources/lang/vendor/backup/fa/notifications.php
  resources/lang/vendor/backup/fi/notifications.php
  resources/lang/vendor/backup/fr/notifications.php
  resources/lang/vendor/backup/he/notifications.php
  resources/lang/vendor/backup/hi/notifications.php
  resources/lang/vendor/backup/hr/notifications.php
  resources/lang/vendor/backup/id/notifications.php
  resources/lang/vendor/backup/it/notifications.php
  resources/lang/vendor/backup/ja/notifications.php
  resources/lang/vendor/backup/ko/notifications.php
  resources/lang/vendor/backup/nl/notifications.php
  resources/lang/vendor/backup/no/notifications.php
  resources/lang/vendor/backup/pl/notifications.php
  resources/lang/vendor/backup/pt-BR/notifications.php
  resources/lang/vendor/backup/pt/notifications.php
  resources/lang/vendor/backup/ro/notifications.php
  resources/lang/vendor/backup/ru/notifications.php
  resources/lang/vendor/backup/tr/notifications.php
  resources/lang/vendor/backup/uk/notifications.php
  resources/lang/vendor/backup/zh-CN/notifications.php
  resources/lang/vendor/backup/zh-TW/notifications.php
Labels: backend, dependencies, backups, translations

#14921 Added lastname.firstname as email format
  app/Models/User.php
  resources/lang/en-US/general.php
  resources/macros/macros.php
Labels: backend, translations

#14912 Add storage path permissions test
  app/Http/Controllers/SettingsController.php
  tests/Feature/Settings/ShowSetUpPageTest.php
Labels: backend, tests

#14791 Added some style changes in label field selector for the `DefaultLabel` template
  resources/views/partials/label2-field-definitions.blade.php
  resources/views/settings/labels.blade.php
Labels: frontend

#14922 Fixed incorrect translation path for edit profile confirmation message
  app/Http/Controllers/ProfileController.php
  resources/lang/en-US/account/general.php
Labels: backend, translations

#14932 Fixed small deprecation warnings for PHP8.2
  app/Models/Asset.php
  app/Models/Depreciable.php
Labels: backend

#14924 Possible fix for #14915 - error on import when status label is not provided and no deployable statuses can be found
  app/Importer/AssetImporter.php
Labels: backend, importer

#14934 Added php 8.3 test
  .github/workflows/tests-mysql.yml
Labels: config

#14937 Fixed #14935 - improvements and more tests around user deletion
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/Users/UsersController.php
  app/Http/Requests/DeleteUserRequest.php
  database/factories/UserFactory.php
  tests/Feature/Users/Api/DeleteUserTest.php
  tests/Feature/Users/Api/RestoreUserTest.php
  tests/Feature/Users/Api/ViewUserTest.php
  tests/Feature/Users/Ui/DeleteUserTest.php
Labels: backend, api, restore, tests

#14941 Updated PHPunit
  composer.json
  composer.lock
Labels: backend, dependencies

#14949 Check that there is a depreciation date before formatting
  app/Http/Controllers/ReportsController.php
Labels: backend

#14925 Additional translation strings
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Middleware/CheckForTwoFactor.php
  resources/lang/en-US/auth/general.php
  resources/lang/en-US/auth/message.php
  resources/lang/en-US/general.php
  resources/views/account/requestable-assets.blade.php
  resources/views/layouts/default.blade.php
Labels: frontend, backend, translations

#14951 Added ability to disallow profile editing
  app/Http/Controllers/ProfileController.php
  app/Http/Controllers/SettingsController.php
  app/Models/User.php
  app/Providers/AuthServiceProvider.php
  database/migrations/2024_06_24_130348_add_profile_edit_to_settings.php
  resources/lang/en-US/admin/settings/general.php
  resources/views/layouts/default.blade.php
  resources/views/settings/general.blade.php
Labels: frontend, backend, translations

#14963 Added avif to translation string
  resources/lang/en-US/general.php
Labels: translations

#14971 Fixes #14968 - translate forbidden page
  resources/lang/en-US/general.php
  resources/views/errors/403.blade.php
Labels: frontend, translations

#14966 Fixed importer table background color
  resources/assets/less/skins/skin-black-dark.less
  resources/assets/less/skins/skin-blue-dark.less
  resources/assets/less/skins/skin-green-dark.less
  resources/assets/less/skins/skin-orange-dark.less
  resources/assets/less/skins/skin-purple-dark.less
  resources/assets/less/skins/skin-red-dark.less
  resources/assets/less/skins/skin-yellow-dark.less
Labels: frontend, css, skins

#14974 Fixed #14895 and #14919 - set SAML baseurl to a sensible default for docker users and users behind a reverse proxy
  app/Services/Saml.php
Labels: backend, saml

#14942 First start at switching to regular html labels
  resources/views/accessories/checkin.blade.php
  resources/views/account/profile.blade.php
  resources/views/hardware/audit.blade.php
  resources/views/hardware/bulk-checkout.blade.php
  resources/views/hardware/checkin.blade.php
  resources/views/hardware/checkout.blade.php
  resources/views/kits/checkout.blade.php
  resources/views/setup/user.blade.php
Labels: frontend

#14831 Updated Livewire to v3
  app/Livewire/CategoryEditForm.php
  app/Livewire/CustomFieldSetDefaultValuesForModel.php
  app/Livewire/Importer.php
  app/Livewire/OauthClients.php
  app/Livewire/PersonalAccessTokens.php
  app/Livewire/SlackSettingsForm.php
  composer.json
  composer.lock
  config/livewire.php
  package-lock.json
  package.json
  public/vendor/livewire/livewire.esm.js
  public/vendor/livewire/livewire.js
  public/vendor/livewire/livewire.min.js
  public/vendor/livewire/livewire.min.js.map
  public/vendor/livewire/manifest.json
  resources/assets/js/snipeit.js
  resources/views/layouts/basic.blade.php
  resources/views/layouts/default.blade.php
  resources/views/livewire/category-edit-form.blade.php
  resources/views/livewire/custom-field-set-default-values-for-model.blade.php
  resources/views/livewire/importer.blade.php
  resources/views/livewire/oauth-clients.blade.php
  resources/views/livewire/personal-access-tokens.blade.php
  resources/views/livewire/slack-settings-form.blade.php
  resources/views/settings/labels.blade.php
  resources/views/users/print.blade.php
  routes/web.php
  tests/Feature/Livewire/CategoryEditFormTest.php
  webpack.mix.js
Labels: frontend, backend, javascript, custom fields, dependencies, skins, livewire, tests

#14982 Check that the user exists before trying to fill the request
  app/Http/Controllers/Api/UsersController.php
  tests/Feature/Users/Api/UpdateUserTest.php
Labels: backend, api, tests

#14981 Fixed #14976, #14975, #14973 - Translation strings aren't always working
  app/Services/SnipeTranslator.php
  config/app.php
  resources/lang/vendor/backup/ar/notifications.php
  resources/lang/vendor/backup/bg/notifications.php
  resources/lang/vendor/backup/bn/notifications.php
  resources/lang/vendor/backup/cs/notifications.php
  resources/lang/vendor/backup/da/notifications.php
  resources/lang/vendor/backup/de/notifications.php
  resources/lang/vendor/backup/en/notifications.php
  resources/lang/vendor/backup/es/notifications.php
  resources/lang/vendor/backup/fa/notifications.php
  resources/lang/vendor/backup/fi/notifications.php
  resources/lang/vendor/backup/fr/notifications.php
  resources/lang/vendor/backup/he/notifications.php
  resources/lang/vendor/backup/hi/notifications.php
  resources/lang/vendor/backup/hr/notifications.php
  resources/lang/vendor/backup/id/notifications.php
  resources/lang/vendor/backup/it/notifications.php
  resources/lang/vendor/backup/ja/notifications.php
  resources/lang/vendor/backup/ko/notifications.php
  resources/lang/vendor/backup/nl/notifications.php
  resources/lang/vendor/backup/no/notifications.php
  resources/lang/vendor/backup/pl/notifications.php
  resources/lang/vendor/backup/pt-BR/notifications.php
  resources/lang/vendor/backup/pt/notifications.php
  resources/lang/vendor/backup/ro/notifications.php
  resources/lang/vendor/backup/ru/notifications.php
  resources/lang/vendor/backup/tr/notifications.php
  resources/lang/vendor/backup/uk/notifications.php
  resources/lang/vendor/backup/zh-CN/notifications.php
  resources/lang/vendor/backup/zh-TW/notifications.php
  tests/Unit/SnipeTranslatorTest.php
Labels: backend, backups, translations
