Repository grokability/snipe-it, pull requests merged in 2024-04, with the labels that each got.

#14520 fixes z-index of table load
  resources/assets/less/overrides.less
Labels: frontend, css, skins

#14551 Fixed ambiguous id clause in custom report
  app/Http/Controllers/ReportsController.php
Labels: backend

#14552 Redirect on checkin if the asset is already checked in
  app/Http/Controllers/Assets/AssetCheckinController.php
Labels: backend

#14547 Fixed alignment of dropdown menu for user in nav bar
  resources/assets/less/overrides.less
Labels: frontend, css, skins

#14529 Hide/Show encrypted values in hardware list
  resources/views/hardware/view.blade.php
  resources/views/layouts/default.blade.php
Labels: frontend

#14559 Fixed ldap location syncing incorrect locations for users.
  app/Console/Commands/LdapSync.php
Labels: backend, ldap, cli / artisan

#14557 Added audit dates to label options
  resources/views/partials/label2-field-definitions.blade.php
Labels: frontend

#14582 Reduce Extra Space in Header Dropdown
  resources/views/layouts/default.blade.php
Labels: frontend

#14558 Fixed: Header Dropdown Menus had no hover coloring in dark themes
  resources/assets/less/skins/skin-black-dark.less
  resources/assets/less/skins/skin-blue-dark.less
  resources/assets/less/skins/skin-green-dark.less
  resources/assets/less/skins/skin-orange-dark.less
  resources/assets/less/skins/skin-purple-dark.less
  resources/assets/less/skins/skin-red-dark.less
  resources/assets/less/skins/skin-yellow-dark.less
Labels: frontend, css, skins

#14577 Upgraded Signature-pad.js && Fixed Resizing Canvas on mobile
  package-lock.json
  package.json
  resources/views/account/accept/create.blade.php
Labels: frontend, javascript, dependencies

#14581 Fixed assigned to field in new label engine
  app/Models/Labels/FieldOption.php
  tests/Unit/Models/Labels/FieldOptionTest.php
Labels: backend, tests

#13880 Fixed department validation to allow updates
  app/Providers/ValidationServiceProvider.php
Labels: backend

#14591 First fix for user FMCS scoping
  app/Http/Controllers/Api/UsersController.php
  app/Http/Controllers/Users/UsersController.php
  app/Models/Company.php
  app/Models/CompanyableTrait.php
  app/Policies/SnipePermissionsPolicy.php
  app/Providers/AuthServiceProvider.php
  resources/lang/en-US/admin/licenses/message.php
  resources/lang/en-US/general.php
  tests/Feature/Api/Users/UpdateUserApiTest.php
Labels: backend, api, translations, tests

#14613 Added test cases around modifying user groups via api
  tests/Feature/Api/Users/UpdateUserApiTest.php
Labels: tests

#14511 Fixed #14508: Added PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT options to database.php …
  .env.docker
  .env.dusk.example
  .env.example
  config/database.php
Labels: docker

#14622 Reeduced z-index of bs table override
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/mix-manifest.json
  resources/assets/less/overrides.less
Labels: frontend, css, skins

#14630 Removed escaping on notes for file uploads
  app/Http/Controllers/AssetModelsFilesController.php
  app/Http/Controllers/Assets/AssetFilesController.php
Labels: backend

#14632 Added "select" option to top of data sources in new label engine
  resources/lang/en-US/general.php
  resources/views/partials/label2-field-definitions.blade.php
Labels: frontend, translations

#14616 REMOVED: Dark Theme Button Text Coloring
  resources/assets/less/skins/skin-black-dark.less
  resources/assets/less/skins/skin-blue-dark.less
  resources/assets/less/skins/skin-green-dark.less
  resources/assets/less/skins/skin-orange-dark.less
  resources/assets/less/skins/skin-purple-dark.less
  resources/assets/less/skins/skin-red-dark.less
  resources/assets/less/skins/skin-yellow-dark.less
Labels: frontend, css, skins

#14602 Re-enabled updating encrypted custom fields via API [sc-41465]
  app/Http/Controllers/Api/AssetsController.php
  database/factories/AssetFactory.php
  database/factories/AssetModelFactory.php
  database/factories/CustomFieldsetFactory.php
  resources/lang/en-US/admin/hardware/message.php
  tests/Feature/Api/Assets/AssetStoreTest.php
  tests/Feature/Api/Assets/AssetUpdateTest.php
  tests/Support/CanSkipTests.php
  tests/Support/CustomTestMacros.php
  tests/TestCase.php
Labels: backend, custom fields, api, translations, tests

#14608 Left Sidebar Was Not Respecting Theme
  resources/assets/less/mixins.less
Labels: frontend, css, skins

#14499 Removed encrypted fields from label options
  app/Http/Controllers/LabelsController.php
  app/Http/Controllers/SettingsController.php
  resources/views/partials/label2-field-definitions.blade.php
Labels: frontend, backend, labels

#14587 Added a License Export function and button
  app/Http/Controllers/Licenses/LicensesController.php
  app/Models/License.php
  resources/lang/en-US/admin/licenses/table.php
  resources/lang/en-US/general.php
  resources/views/licenses/index.blade.php
  routes/web/licenses.php
Labels: frontend, backend, translations

#14651 Fixed `purchase_cost` not being allowed to be a string when creating asset via api
  app/Http/Requests/StoreAssetRequest.php
  tests/Feature/Api/Assets/AssetStoreTest.php
  tests/Unit/Helpers/HelperTest.php
Labels: backend, tests
