Repository grokability/snipe-it, pull requests merged in 2024-03, with the labels that each got.

#14354 Use SVG cleaner on favicons
  app/Http/Controllers/SettingsController.php
Labels: backend

#14357 Removed unsafe-inline and unsafe-eval
  app/Http/Middleware/SecurityHeaders.php
Labels: backend

#14362 Fixes inconsistencies with generating labels
  app/View/Label.php
Labels: backend

#14375 Fixed Labels: bulk actions are handled before sorting
  app/Http/Controllers/Assets/BulkAssetsController.php
Labels: backend

#14378 Upgrade jspdf-autotable from 3.8.1 to 3.8.2 #14365
  package-lock.json
  package.json
Labels: javascript, dependencies

#14380 Fixed 1dbarcodes to populate based on settings
  app/View/Label.php
Labels: backend

#14371 Adds User email check when sending Asset acceptance reminder
  app/Http/Controllers/ReportsController.php
  resources/lang/en-US/general.php
Labels: backend, translations

#14370 Fixes CVE-2024-27354 and CVE-2024-27355 in phpseclib/phpseclib
  composer.lock
Labels: backend, dependencies

#14379 Fix #13515: Cannot restore backup
  config/version.php
  docker/startup.sh
Labels: docker

#14385 Added console command to encrypt previously unencrypted fields
  app/Console/Commands/ToggleCustomfieldEncryption.php
Labels: backend, cli / artisan

#14388 Fixed attempting to run bulk actions on an empty asset collection
  app/Http/Controllers/Assets/BulkAssetsController.php
  resources/lang/en-US/admin/hardware/message.php
Labels: backend, translations

#14389 old engine works as intended
  app/View/Label.php
Labels: backend

#14392 Removed unneeded validation message
  app/Http/Livewire/SlackSettingsForm.php
Labels: backend, livewire

#14393 Guard against checking require acceptance on non-existent relationship in accessory model
  app/Models/Accessory.php
Labels: backend

#14395 [Snyk] Upgrade webpack from 5.90.1 to 5.90.2
  package-lock.json
  package.json
Labels: javascript, dependencies

#14394 Ensure Chat and Teams endpoints are not blank before attempting to send webhook on checkout and check in
  app/Notifications/CheckinAccessoryNotification.php
  app/Notifications/CheckinAssetNotification.php
  app/Notifications/CheckinLicenseSeatNotification.php
  app/Notifications/CheckoutAccessoryNotification.php
  app/Notifications/CheckoutAssetNotification.php
  app/Notifications/CheckoutConsumableNotification.php
Labels: backend, notifications

#14404 Fixed uninitialized offset in labels in new label engine
  app/Models/Labels/DefaultLabel.php
Labels: backend, breaking

#14407 Added created_at to license pivot
  app/Models/User.php
  resources/views/users/print.blade.php
Labels: frontend, backend

#14430 Fixed requestable search API
  app/Http/Controllers/Api/AssetsController.php
Labels: backend, api

#14427 Removes the unused `mediconesystems/livewire-datatables` package
  composer.json
  composer.lock
Labels: backend, dependencies

#14415 Fixed z-index of date-picker
  resources/assets/less/overrides.less
Labels: frontend, css, skins

#14437 Removed dead test code
  tests/Feature/Api/Users/UpdateUserApiTest.php
  tests/Unit/AssetTest.php
  tests/Unit/CategoryTest.php
  tests/Unit/ImporterTest.php
  tests/Unit/PermissionsTest.php
Labels: tests

#14406 Hide/Show ecnrypted values when click on the lock icon
  resources/views/hardware/view.blade.php
  resources/views/layouts/default.blade.php
Labels: frontend

#14436 Organized notification test cases
  tests/Feature/Notifications/AccessoryWebhookTest.php
  tests/Feature/Notifications/AssetWebhookTest.php
  tests/Feature/Notifications/ComponentWebhookTest.php
  tests/Feature/Notifications/ConsumableWebhookTest.php
  tests/Feature/Notifications/Email/EmailNotificationsUponCheckinTest.php
  tests/Feature/Notifications/LicenseWebhookTest.php
  tests/Feature/Notifications/Webhooks/SlackNotificationsUponCheckinTest.php
  tests/Feature/Notifications/Webhooks/SlackNotificationsUponCheckoutTest.php
  tests/Support/AssertsAgainstSlackNotifications.php
  tests/Support/Settings.php
  tests/TestCase.php
Labels: tests

#14445 Make sure the category is still valid before displaying on view assets
  resources/views/account/view-assets.blade.php
Labels: frontend

#14447 Add additional options to print all assigned view
  resources/lang/en-US/general.php
  resources/views/users/print.blade.php
Labels: frontend, translations

#14457 Fixed Bulk delete locations bug
  app/Http/Controllers/Api/LocationsController.php
  app/Http/Controllers/LocationsController.php
  app/Models/Location.php
Labels: backend, api

#14461 [Snyk] Upgrade bootstrap-table from 1.22.2 to 1.22.3 #14455
  package-lock.json
  package.json
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
Labels: frontend, javascript, css, dependencies, skins

#14462 Wider country dropdown
  resources/macros/macros.php
  resources/views/partials/forms/edit/address.blade.php
  resources/views/partials/forms/edit/user-select.blade.php
  resources/views/users/edit.blade.php
Labels: frontend

#14465 Added #14460 add avif format
  app/Helpers/Helper.php
  app/Http/Requests/ImageUploadRequest.php
  app/Http/Requests/UploadFileRequest.php
  resources/views/partials/forms/edit/image-upload.blade.php
Labels: frontend, backend

#14468 Added default location to print all assigned
  resources/views/users/print.blade.php
Labels: frontend

#14464 Added "toggle all" to column selector
  app/Presenters/AccessoryPresenter.php
  app/Presenters/AssetMaintenancesPresenter.php
  app/Presenters/AssetModelPresenter.php
  app/Presenters/AssetPresenter.php
  app/Presenters/CategoryPresenter.php
  app/Presenters/CompanyPresenter.php
  app/Presenters/ComponentPresenter.php
  app/Presenters/ConsumablePresenter.php
  app/Presenters/DepreciationPresenter.php
  app/Presenters/DepreciationReportPresenter.php
  app/Presenters/LicensePresenter.php
  app/Presenters/LocationPresenter.php
  app/Presenters/ManufacturerPresenter.php
  app/Presenters/UserPresenter.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#14438 Removed the need to add `InteractsWithSettings` to each test case
  tests/Feature/Api/Accessories/AccessoryCheckoutTest.php
  tests/Feature/Api/Assets/AssetCheckinTest.php
  tests/Feature/Api/Assets/AssetIndexTest.php
  tests/Feature/Api/Assets/AssetStoreTest.php
  tests/Feature/Api/Assets/AssetsForSelectListTest.php
  tests/Feature/Api/Assets/RequestableAssetsTest.php
  tests/Feature/Api/Components/ComponentIndexTest.php
  tests/Feature/Api/Consumables/ConsumableCheckoutTest.php
  tests/Feature/Api/Consumables/ConsumablesIndexTest.php
  tests/Feature/Api/Departments/DepartmentIndexTest.php
  tests/Feature/Api/Groups/GroupStoreTest.php
  tests/Feature/Api/Licenses/LicensesIndexTest.php
  tests/Feature/Api/Locations/LocationsForSelectListTest.php
  tests/Feature/Api/Users/UpdateUserApiTest.php
  tests/Feature/Api/Users/UsersForSelectListTest.php
  tests/Feature/Api/Users/UsersSearchTest.php
  tests/Feature/Api/Users/UsersUpdateTest.php
  tests/Feature/Checkins/AccessoryCheckinTest.php
  tests/Feature/Checkins/AssetCheckinTest.php
  tests/Feature/CheckoutAcceptances/AccessoryAcceptanceTest.php
  tests/Feature/Checkouts/AccessoryCheckoutTest.php
  tests/Feature/Checkouts/ConsumableCheckoutTest.php
  tests/Feature/Checkouts/LicenseCheckoutTest.php
  tests/Feature/DashboardTest.php
  tests/Feature/Notifications/Email/EmailNotificationsUponCheckinTest.php
  tests/Feature/Notifications/Webhooks/SlackNotificationsUponCheckinTest.php
  tests/Feature/Notifications/Webhooks/SlackNotificationsUponCheckoutTest.php
  tests/Feature/Reports/CustomReportTest.php
  tests/Feature/Users/UpdateUserTest.php
  tests/Support/InitializesSettings.php
  tests/TestCase.php
  tests/Unit/AssetMaintenanceTest.php
  tests/Unit/AssetModelTest.php
  tests/Unit/AssetTest.php
  tests/Unit/CategoryTest.php
  tests/Unit/CompanyScopingTest.php
  tests/Unit/ComponentTest.php
  tests/Unit/DepreciationTest.php
  tests/Unit/LdapTest.php
  tests/Unit/Models/Company/GetIdForCurrentUserTest.php
  tests/Unit/NotificationTest.php
  tests/Unit/SnipeModelTest.php
Labels: consumables, tests

#14421 Adds a minimal amount of validation around asset_tags in AssetsController
  app/Http/Controllers/Assets/AssetsController.php
Labels: backend

#14469 Added 2FA reset log entry
  app/Http/Controllers/Api/UsersController.php
  app/Presenters/ActionlogPresenter.php
  resources/lang/en-US/admin/settings/general.php
  resources/lang/en-US/general.php
  resources/views/users/edit.blade.php
  resources/views/users/view.blade.php
Labels: frontend, backend, api, translations

#14089 Use `htmlentities()` instead of `htmlspecialcharacters()` on Custom Field Listbox Values
  app/Http/Controllers/CustomFieldsController.php
  resources/views/models/custom_fields_form.blade.php
  resources/views/models/custom_fields_form_bulk_edit.blade.php
Labels: frontend, backend, custom fields

#14472 Added validation for last_audit_date and next_audit_date
  app/Http/Controllers/Api/AssetsController.php
  app/Models/Asset.php
Labels: backend, api

#14485 Created Dymo LabelWriter Label 2112283
  app/Models/Labels/Tapes/Dymo/Label_Writer_2112283.php
Labels: backend

#14486 Fixes `last_audit_date` not being stored via API correctly
  app/Http/Requests/StoreAssetRequest.php
  tests/Feature/Api/Assets/AssetStoreTest.php
Labels: backend, tests

#14488 Handle badly formatted `last_audit_date` in `StoreAssetRequest`
  app/Http/Requests/StoreAssetRequest.php
  tests/Feature/Api/Assets/AssetStoreTest.php
Labels: backend, tests

#14490 Fixed #14482 - bad method call model restore from view
  resources/views/hardware/view.blade.php
  resources/views/models/view.blade.php
Labels: frontend

#14492 Fixed #14483 - adds deeplinking to search/sort/pagination
  .env.example
  config/session.php
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
  resources/views/partials/bootstrap-table.blade.php
  webpack.mix.js
Labels: frontend, javascript, skins

#14494 Added supplier details to license view
  resources/views/licenses/view.blade.php
Labels: frontend

#14498 Fixed #14495 - Allow user_id to be passed to limit to only specific admins
  app/Http/Controllers/Api/ReportsController.php
Labels: backend, api

#14369 Add new validator for custom field checkboxes and fix asset model default updates
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Controllers/AssetModelsController.php
  app/Models/CustomFieldset.php
  app/Providers/ValidationServiceProvider.php
  resources/lang/en-US/validation.php
  resources/views/custom_fields/fields/edit.blade.php
Labels: frontend, backend, custom fields, api, translations, tests

#14502 Added validation around `pwd_secure_complexity`
  app/Http/Controllers/SettingsController.php
  resources/lang/en-US/validation.php
  resources/views/settings/security.blade.php
Labels: frontend, backend, translations

#14509 Added ability to filter in user's assigned assets by category ID and model ID
  app/Http/Controllers/Api/UsersController.php
Labels: backend, api

#14510 [Snyk] Upgrade alpinejs from 3.13.5 to 3.13.6
  package-lock.json
  package.json
  public/js/dist/all-defer.js
  public/mix-manifest.json
Labels: frontend, javascript, dependencies, skins

#14262 Last Checkin Date added to Hardware View and Index
  app/Http/Controllers/ReportsController.php
  app/Http/Transformers/AssetsTransformer.php
  app/Presenters/AssetPresenter.php
  resources/views/hardware/view.blade.php
Labels: frontend, backend, api

#14500 Added signature to user print report for Accessories and Consumables
  resources/views/users/print.blade.php
Labels: frontend

#14515 Fixes #14289: /reports/activity API endpoint returns too many results due to orwhere
  app/Http/Controllers/Api/ReportsController.php
Labels: backend, api

#14516 Fixed sorting on last checkin assets api
  app/Http/Controllers/Api/AssetsController.php
  app/Models/Asset.php
Labels: backend, api

#14518 Downgrade alpine to 3.13.5
  package-lock.json
  package.json
  public/js/dist/all-defer.js
  public/mix-manifest.json
Labels: frontend, javascript, dependencies, skins
