Repository grokability/snipe-it, pull requests merged in 2025-02, with the labels that each got.

#16166 Removes default ternary check in Label view
  app/View/Label.php
Labels: backend

#16175 Added a warning for webhook `channel_not_found`.
  app/Listeners/CheckoutableListener.php
  resources/lang/en-US/admin/settings/message.php
Labels: backend, translations

#16168 Added ternary check that asset has `asset status` before checking archived
  resources/views/locations/print.blade.php
Labels: frontend

#16197 Replace calls to Form::label in QuickStart
  resources/views/setup/user.blade.php
Labels: frontend

#16196 Replace calls to Form::label pt6
  resources/views/settings/google.blade.php
  resources/views/settings/localization.blade.php
  resources/views/settings/purge-form.blade.php
  resources/views/settings/saml.blade.php
  resources/views/settings/security.blade.php
  resources/views/statuslabels/edit.blade.php
  resources/views/suppliers/edit.blade.php
Labels: frontend, saml

#16190 Replace calls to Form::label pt1
  resources/views/hardware/quickscan-checkin.blade.php
  resources/views/hardware/quickscan.blade.php
  resources/views/livewire/slack-settings-form.blade.php
  resources/views/partials/forms/edit/accessory-select.blade.php
  resources/views/partials/forms/edit/address.blade.php
Labels: frontend, livewire

#16194 Replace calls to Form::label pt4
  resources/views/partials/forms/checkout-selector.blade.php
  resources/views/partials/forms/edit/supplier-select.blade.php
  resources/views/partials/forms/edit/user-select.blade.php
  resources/views/settings/alerts.blade.php
Labels: frontend

#16192 Replace calls to Form::label pt2
  resources/views/partials/forms/edit/asset-select.blade.php
  resources/views/partials/forms/edit/category-select.blade.php
  resources/views/partials/forms/edit/company.blade.php
  resources/views/partials/forms/edit/consumable-select.blade.php
  resources/views/partials/forms/edit/datepicker.blade.php
  resources/views/partials/forms/edit/department-select.blade.php
  resources/views/partials/forms/edit/fax.blade.php
Labels: frontend

#16193 Replace calls to Form::label pt3
  resources/views/partials/forms/edit/kit-select.blade.php
  resources/views/partials/forms/edit/license-select.blade.php
  resources/views/partials/forms/edit/location-profile-select.blade.php
  resources/views/partials/forms/edit/location-select.blade.php
  resources/views/partials/forms/edit/manufacturer-select.blade.php
  resources/views/partials/forms/edit/model-select.blade.php
  resources/views/partials/forms/edit/phone.blade.php
  resources/views/partials/forms/edit/status-select.blade.php
Labels: frontend

#16180 Replaced calls to Form::radio helper on bulk asset model edit page
  resources/views/models/bulk-edit.blade.php
Labels: frontend

#16179 Replaced calls to Form::radio helper on bulk hardware edit page
  resources/views/hardware/bulk.blade.php
Labels: frontend

#16167 Adds qr code type check in getQRCode method
  app/Http/Controllers/Assets/AssetsController.php
Labels: backend

#16178 Replaced calls to Form::radio helper on group create and edit pages
  resources/views/groups/edit.blade.php
Labels: frontend

#16176 Replaced some calls to the Form::radio helper
  resources/views/reports/custom.blade.php
  resources/views/users/bulk-edit.blade.php
Labels: frontend

#16207 Upgraded papaparse to 5.5.1
  package-lock.json
  package.json
Labels: javascript, dependencies

#16209 Fixed #16208 - don't call preg_split() with a null
  app/Http/Requests/SettingsSamlRequest.php
  app/Models/CustomField.php
  app/Services/Saml.php
Labels: backend, saml

#16213 Replace calls to Form::checkbox pt1
  resources/views/account/profile.blade.php
  resources/views/custom_fields/fieldsets/view.blade.php
  resources/views/hardware/bulk.blade.php
Labels: frontend, custom fields

#16212 adds ternaries on check in/out hardware notifications
  app/Notifications/CheckinAssetNotification.php
Labels: backend, notifications

#16075 Convert Form::textarea to blade component
  config/version.php
  public/css/build/AdminLTE.css
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/css/dist/signature-pad.min.css
  public/css/dist/skins/_all-skins.css
  public/css/dist/skins/_all-skins.min.css
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/css/dist/skins/skin-black.css
  public/css/dist/skins/skin-black.min.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-blue.css
  public/css/dist/skins/skin-blue.min.css
  public/css/dist/skins/skin-contrast.css
  public/css/dist/skins/skin-contrast.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-green.css
  public/css/dist/skins/skin-green.min.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-orange.css
  public/css/dist/skins/skin-orange.min.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-purple.css
  public/css/dist/skins/skin-purple.min.css
  public/css/dist/skins/skin-red-dark.css
  public/css/dist/skins/skin-red-dark.min.css
  public/css/dist/skins/skin-red.css
  public/css/dist/skins/skin-red.min.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/css/dist/skins/skin-yellow.css
  public/css/dist/skins/skin-yellow.min.css
  public/js/build/app.js
  public/js/build/vendor.js
  public/js/dist/all.js
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
  resources/views/blade/input/textarea.blade.php
  resources/views/custom_fields/fields/edit.blade.php
  resources/views/livewire/category-edit-form.blade.php
  resources/views/modals/upload-file.blade.php
  resources/views/settings/branding.blade.php
  resources/views/settings/general.blade.php
  resources/views/settings/ldap.blade.php
  resources/views/settings/saml.blade.php
Labels: frontend, custom fields, ldap, saml, livewire

#16232 Expiration notifcation switched to use Mailable
  app/Console/Commands/SendExpirationAlerts.php
  app/Mail/ExpiringAssetsMail.php
  app/Mail/ExpiringLicenseMail.php
  tests/Feature/Notifications/Email/ExpiringAlertsNotificationTest.php
  tests/Support/Settings.php
Labels: backend, cli / artisan, tests

#16250 Instead of saving TLS cache-files on save, cache them when used
  app/Http/Controllers/SettingsController.php
  app/Models/Setting.php
  tests/Unit/LdapTest.php
Labels: backend, ldap, tests

#16082 Replace calls to Form::text
  resources/views/custom_fields/fields/edit.blade.php
  resources/views/custom_fields/fieldsets/view.blade.php
  resources/views/partials/forms/edit/address.blade.php
  resources/views/partials/forms/edit/phone.blade.php
  resources/views/settings/alerts.blade.php
  resources/views/settings/asset_tags.blade.php
  resources/views/settings/branding.blade.php
  resources/views/settings/general.blade.php
  resources/views/settings/google.blade.php
  resources/views/settings/labels.blade.php
  resources/views/settings/ldap.blade.php
  resources/views/settings/localization.blade.php
  resources/views/settings/purge-form.blade.php
  resources/views/settings/saml.blade.php
  resources/views/settings/security.blade.php
  resources/views/setup/user.blade.php
  resources/views/statuslabels/edit.blade.php
  resources/views/suppliers/edit.blade.php
Labels: frontend, custom fields, ldap, saml

#16268 Fixed #16259 - mismatch in asset count if archived assets are hidden
  app/Http/Controllers/Api/CompaniesController.php
Labels: backend, api

#16269 Scope API results by location ID
  app/Http/Controllers/Api/LocationsController.php
Labels: backend, api

#16270 Updated LDAP sync text
  resources/lang/en-US/admin/settings/general.php
Labels: translations

#16188 Adds translations to LDAP and Label settings pages
  resources/lang/en-US/admin/settings/general.php
  resources/lang/en-US/general.php
  resources/views/partials/label2-field-definitions.blade.php
  resources/views/partials/label2-preview.blade.php
  resources/views/settings/ldap.blade.php
Labels: frontend, ldap, translations

#16225 Removed cols property from textarea component
  resources/views/blade/input/textarea.blade.php
Labels: frontend

#16235 Replace Form::open and Form::close pt1
  resources/views/account/change-password.blade.php
  resources/views/account/profile.blade.php
  resources/views/custom_fields/fields/edit.blade.php
  resources/views/custom_fields/fieldsets/view.blade.php
  resources/views/custom_fields/index.blade.php
  resources/views/depreciations/view.blade.php
  routes/web.php
Labels: frontend, custom fields

#16242 Replace Form::open and Form::close pt2
  resources/views/hardware/audit.blade.php
  resources/views/hardware/quickscan-checkin.blade.php
  resources/views/hardware/quickscan.blade.php
  resources/views/hardware/requested.blade.php
Labels: frontend

#16243 Replace Form::open and Form::close pt3
  resources/views/hardware/view.blade.php
  resources/views/modals/upload-file.blade.php
  resources/views/models/index.blade.php
  resources/views/models/view.blade.php
  resources/views/partials/asset-bulk-actions.blade.php
  resources/views/partials/locations-bulk-actions.blade.php
  resources/views/partials/models-bulk-actions.blade.php
Labels: frontend

#16244 Replace Form::open and Form::close pt4
  resources/views/partials/users-bulk-actions.blade.php
  resources/views/reports/activity.blade.php
  resources/views/reports/custom.blade.php
  resources/views/reports/unaccepted_assets.blade.php
  resources/views/settings/alerts.blade.php
  routes/web.php
Labels: frontend

#16246 Replace Form::open and Form::close pt6
  resources/views/settings/ldap.blade.php
  resources/views/settings/localization.blade.php
  resources/views/settings/purge-form.blade.php
  resources/views/settings/saml.blade.php
  resources/views/settings/security.blade.php
  resources/views/statuslabels/view.blade.php
  resources/views/users/index.blade.php
Labels: frontend, ldap, saml

#16040 Adds a null check to label templates, adds return types for validation methods
  app/Http/Controllers/SettingsController.php
  app/Http/Requests/StoreLabelSettings.php
  app/Models/Labels/Label.php
  app/View/Label.php
  resources/lang/en-US/admin/settings/message.php
  resources/views/settings/labels.blade.php
Labels: frontend, backend, translations

#16245 Replace Form::open and Form::close pt5
  resources/views/settings/asset_tags.blade.php
  resources/views/settings/backups.blade.php
  resources/views/settings/branding.blade.php
  resources/views/settings/general.blade.php
  resources/views/settings/google.blade.php
  resources/views/settings/labels.blade.php
Labels: frontend, backups

#16278 Added better error handling around rendering barcodes
  app/Http/Controllers/Assets/AssetsController.php
Labels: backend

#16290 Removed php 8.1, added 8.4
  .github/workflows/tests-mysql.yml
  .github/workflows/tests-postgres.yml
  .github/workflows/tests-sqlite.yml
Labels: config

#16292 Added ability to send user inventory via bulk UI
  app/Http/Controllers/Users/BulkUsersController.php
  resources/lang/en-US/admin/users/general.php
  resources/views/partials/users-bulk-actions.blade.php
Labels: frontend, backend, translations

#16291 Fix tests and fix migrations to always explicitly include nullable()
  database/migrations/2015_02_07_013537_add_soft_deleted_to_log.php
  database/migrations/2015_02_12_024100_change_license_notes_type.php
  database/migrations/2015_09_22_003413_migrate_mac_address.php
  database/migrations/2016_03_02_220517_update_ldap_filter_to_longer_field.php
  database/migrations/2016_08_30_084634_make_purchase_cost_nullable.php
  database/migrations/2016_11_16_172119_increase_purchase_cost_size.php
  database/migrations/2017_01_25_063357_fix_utf8_custom_field_column_names.php
  database/migrations/2017_08_03_160105_set_asset_archived_to_zero_default.php
  database/migrations/2019_02_20_234421_make_serial_nullable.php
  database/migrations/2019_12_04_223111_passport_upgrade.php
  database/migrations/2023_08_01_174150_change_webhook_settings_variable_type.php
  database/migrations/2025_01_06_210534_change_report_templates_options_to_column_text_field.php
  database/migrations/2025_01_07_172419_fix_label_types_on_settings_table.php
  tests/Feature/Settings/ShowSetUpPageTest.php
Labels: ldap, tests

#16294 Don’t delete avatar file on soft-delete
  app/Http/Controllers/Users/UsersController.php
Labels: backend

#16293 Updated default Dockerfile to handle newer PHP versions
  Dockerfile
Labels: docker

#16285 Re-added ability to add notes to assets
  app/Events/NoteAdded.php
  app/Http/Controllers/Api/NotesController.php
  app/Http/Controllers/NotesController.php
  app/Listeners/LogListener.php
  resources/assets/js/snipeit_modals.js
  resources/views/hardware/view.blade.php
  resources/views/modals/add-note.blade.php
  routes/api.php
  routes/web.php
  tests/Feature/Notes/AssetNotesTest.php
  tests/Feature/Notes/CreateNotesTest.php
  tests/Unit/Listeners/LogListenerTest.php
Labels: frontend, backend, javascript, api, skins, tests

#16277 Fixes deletion of assigned assets through bulk delete
  app/Http/Controllers/Assets/BulkAssetsController.php
  resources/lang/en-US/admin/hardware/message.php
  tests/Feature/Assets/Ui/BulkDeleteAssetsTest.php
Labels: backend, translations, tests

#16295 Fixed #16282 - adds accessories tab to assets
  app/Http/Controllers/Api/AssetsController.php
  app/Http/Transformers/AssetsTransformer.php
  app/Http/Transformers/LocationsTransformer.php
  app/Models/AccessoryCheckout.php
  app/Models/Asset.php
  app/Presenters/AssetPresenter.php
  resources/views/hardware/view.blade.php
  resources/views/locations/view.blade.php
Labels: frontend, backend, api

#16287 Fixes: [sc-28423] Better tooltips on lists, Bootstrap style
  app/Presenters/AssetPresenter.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend

#16297 Fixed #6188 - Added custom fields to checkin/checkout screens
  app/Http/Controllers/Assets/AssetCheckinController.php
  app/Http/Controllers/Assets/AssetCheckoutController.php
  app/Http/Controllers/CustomFieldsController.php
  app/Models/Asset.php
  app/Models/Loggable.php
  database/migrations/2025_02_22_144518_add_checkin_checkout_to_customfields.php
  resources/lang/en-US/admin/custom_fields/general.php
  resources/views/custom_fields/fields/edit.blade.php
  resources/views/hardware/checkin.blade.php
  resources/views/hardware/checkout.blade.php
  resources/views/layouts/default.blade.php
  resources/views/models/custom_fields_form.blade.php
  resources/views/partials/more-info.blade.php
  routes/web/hardware.php
  tests/Feature/Checkins/Ui/AssetCheckinTest.php
Labels: frontend, backend, custom fields, translations, tests

#16298 Add tooltips to custom fields display, especially for icons
  resources/lang/en-US/admin/custom_fields/general.php
  resources/views/custom_fields/index.blade.php
Labels: frontend, custom fields, translations

#16299 Added checkin/checkout indicators on custom field table
  resources/views/custom_fields/index.blade.php
Labels: frontend, custom fields

#16303 Added tooltip for currency in table
  app/Presenters/LocationPresenter.php
  resources/lang/en-US/general.php
Labels: backend, translations

#16304 Updated less and papaparse
  package-lock.json
  package.json
  public/css/build/AdminLTE.css
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/css/dist/bootstrap-table.css
  public/css/dist/signature-pad.min.css
  public/css/dist/skins/_all-skins.css
  public/css/dist/skins/_all-skins.min.css
  public/css/dist/skins/skin-black-dark.css
  public/css/dist/skins/skin-black-dark.min.css
  public/css/dist/skins/skin-black.css
  public/css/dist/skins/skin-black.min.css
  public/css/dist/skins/skin-blue-dark.css
  public/css/dist/skins/skin-blue-dark.min.css
  public/css/dist/skins/skin-blue.css
  public/css/dist/skins/skin-blue.min.css
  public/css/dist/skins/skin-contrast.css
  public/css/dist/skins/skin-contrast.min.css
  public/css/dist/skins/skin-green-dark.css
  public/css/dist/skins/skin-green-dark.min.css
  public/css/dist/skins/skin-green.css
  public/css/dist/skins/skin-green.min.css
  public/css/dist/skins/skin-orange-dark.css
  public/css/dist/skins/skin-orange-dark.min.css
  public/css/dist/skins/skin-orange.css
  public/css/dist/skins/skin-orange.min.css
  public/css/dist/skins/skin-purple-dark.css
  public/css/dist/skins/skin-purple-dark.min.css
  public/css/dist/skins/skin-purple.css
  public/css/dist/skins/skin-purple.min.css
  public/css/dist/skins/skin-red-dark.css
  public/css/dist/skins/skin-red-dark.min.css
  public/css/dist/skins/skin-red.css
  public/css/dist/skins/skin-red.min.css
  public/css/dist/skins/skin-yellow-dark.css
  public/css/dist/skins/skin-yellow-dark.min.css
  public/css/dist/skins/skin-yellow.css
  public/css/dist/skins/skin-yellow.min.css
  public/js/build/app.js
  public/js/build/vendor.js
  public/js/dist/all.js
  public/js/dist/bootstrap-table.js
  public/mix-manifest.json
Labels: frontend, javascript, css, dependencies, skins

#16305 Fixed #16262 - Check for quantity before allowing component deletion
  app/Http/Controllers/Api/ComponentsController.php
  app/Http/Controllers/Components/ComponentsController.php
  app/Http/Transformers/ComponentsTransformer.php
  app/Models/Component.php
  resources/lang/en-US/admin/components/message.php
  tests/Feature/Components/Api/DeleteComponentTest.php
  tests/Feature/Components/Ui/DeleteComponentTest.php
Labels: backend, api, translations, tests

#16312 Small cleanups before release
  app/Exceptions/Handler.php
  app/Http/Controllers/AssetModelsController.php
  app/Http/Controllers/AssetModelsFilesController.php
  app/Http/Controllers/Users/UserFilesController.php
  app/Http/Transformers/ActionlogsTransformer.php
  app/Providers/BreadcrumbsServiceProvider.php
  resources/lang/en-US/admin/models/general.php
  resources/lang/en-US/general.php
  resources/views/layouts/default.blade.php
  resources/views/models/view.blade.php
  resources/views/users/view.blade.php
  routes/web/models.php
  routes/web/users.php
  tests/Feature/Users/Ui/CloneUserTest.php
  tests/Feature/Users/Ui/DeleteUserTest.php
Labels: frontend, backend, translations, tests

#16106 Fixed asset show page erroring when asset not associated with model
  resources/views/hardware/view.blade.php
  tests/Feature/Assets/Ui/ShowAssetTest.php
Labels: frontend, tests

#16320 Fixed: fix 500 on edit locations page by referencing current location
  app/Http/Controllers/LocationsController.php
Labels: backend

#16062 Removed references to mcrypt
  Dockerfile
  app/Console/Commands/RecryptFromMcrypt.php
  app/LegacyEncrypter/BaseEncrypter.php
  app/LegacyEncrypter/McryptEncrypter.php
  snipeit.sh
Labels: backend, docker, cli / artisan

#16322 Fixed edit routes in tests
  tests/Feature/Licenses/Ui/UpdateLicenseTest.php
  tests/Feature/Locations/Ui/UpdateLocationsTest.php
Labels: tests

#16321 Changed Parameter Name for RMB
  resources/views/notifications/markdown/report-expected-checkins.blade.php
Labels: frontend

#16325 Remove remaining hardware references in favor of new RMB
  app/Http/Controllers/Assets/AssetFilesController.php
  app/View/Label.php
  resources/views/notifications/markdown/report-expected-checkins.blade.php
  routes/web/hardware.php
Labels: frontend, backend

#16335 Added label test
  tests/Feature/Assets/Ui/AssetLabelTest.php
Labels: tests

#16337 Fixed #16173: `useraccountcontrol` was not included in the ldap query attributes
  app/Console/Commands/LdapSync.php
Labels: backend, ldap, cli / artisan

#16345 Fixed renaming custom fields
  app/Models/CustomField.php
Labels: backend

#16346 Replace calls to Form::checkbox pt3
  resources/views/partials/forms/edit/image-upload.blade.php
  resources/views/partials/forms/edit/uploadLogo.blade.php
  resources/views/settings/alerts.blade.php
  resources/views/settings/asset_tags.blade.php
  resources/views/settings/google.blade.php
  resources/views/users/edit.blade.php
Labels: frontend

#16348 Replace calls to Form::checkbox pt5
  resources/views/settings/ldap.blade.php
  resources/views/settings/saml.blade.php
Labels: frontend, ldap, saml

#16347 Replace calls to Form::checkbox pt4
  resources/views/settings/security.blade.php
  resources/views/users/bulk-edit.blade.php
Labels: frontend

#16356 Added name, model_number and notes for strict search
  app/Http/Controllers/Api/AssetModelsController.php
Labels: backend, api

#16363 Added `--no-interaction` to additional passport commands
  .github/workflows/tests-mysql.yml
  .github/workflows/tests-postgres.yml
  app/Http/Controllers/DashboardController.php
  upgrade.php
Labels: backend, config

#16361 Fixed acceptance reminder command lag on users with no associated email
  app/Console/Commands/SendAcceptanceReminder.php
  tests/Feature/Console/SendAcceptanceReminderTest.php
Labels: frontend, backend, javascript, dependencies, skins, cli / artisan, tests

#16365 Replace calls to Form::checkbox pt6
  resources/views/reports/custom.blade.php
Labels: frontend

#16156 Added "Reminder" to subject line of follow up asset checkout emails
  app/Http/Controllers/ReportsController.php
  app/Mail/CheckoutAssetMail.php
  database/factories/CheckoutAcceptanceFactory.php
  tests/Feature/Notifications/Email/AssetAcceptanceReminderTest.php
  tests/Unit/NotificationTest.php
Labels: backend, translations, tests

#16375 Fixed #16371 - incorrect count and missing name in acceptance reminder email
  app/Console/Commands/SendAcceptanceReminder.php
  app/Mail/UnacceptedAssetReminderMail.php
Labels: backend, cli / artisan

#16367 Replace calls to Form::checkbox pt8
  resources/views/settings/labels.blade.php
Labels: frontend

#16366 Replace calls to Form::checkbox pt7
  resources/views/settings/branding.blade.php
  resources/views/settings/general.blade.php
Labels: frontend

#16376 Add some safeties around the charset-detection and transliteration
  app/Http/Controllers/Api/ImportController.php
  resources/lang/en-US/admin/hardware/message.php
  tests/Feature/Importing/Ui/ImportTest.php
Labels: backend, api, translations, tests

#16378 Wrap long text in PDF export in tables
  app/Presenters/AssetMaintenancesPresenter.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend
