Repository grokability/snipe-it, pull requests merged in 2025-01, with the labels that each got.

#16024 Fixed #15977 - Set order by on companies
  app/Http/Controllers/Api/DepartmentsController.php
  app/Models/Department.php
Labels: backend, api

#16031 Pull `backup:clean` settings into config
  .env.example
  config/backup.php
Labels: backups

#16034 Fixes the mail locale check
  app/Listeners/CheckoutableListener.php
Labels: backend

#16035 Fixed acceptance reminder email formatting
  app/Http/Controllers/ReportsController.php
Labels: backend

#16033 Fixed default values for label types in the DB
  app/View/Label.php
  database/migrations/2025_01_07_172419_fix_label_types_on_settings_table.php
  resources/lang/en-US/admin/settings/general.php
  resources/views/settings/labels.blade.php
Labels: frontend, backend, translations

#16047 Check for blank OR null on asset tag/serial formatter
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend

#16009 Fixes : Following docs on running the project in production mode with docker defaulting to v6.1.4
  .env.docker
  docker-compose.yml
Labels: docker

#16051 Update related asset when checkout acceptance created via factory
  database/factories/CheckoutAcceptanceFactory.php
Labels: tests

#16050 Adds try/catch around notification failing with an inactive webhook for better user experience
  app/Listeners/CheckoutableListener.php
  resources/lang/en-US/admin/settings/message.php
Labels: backend, translations

#16018 Added: TZe_24mm_D.php modified TZe_24mm_A that includes 1D code
  app/Models/Labels/Tapes/Brother/TZe_24mm_D.php
Labels: backend

#16053 Fixed #16054: fix incorrect compose service name in the APP_KEY generation command of the Docker env file
  .env.docker
Labels: docker

#15747 Added #15107: Customizable 2D Barcode Content for Asset Labels
  app/View/Label.php
  resources/lang/en-US/admin/settings/general.php
  resources/views/settings/labels.blade.php
Labels: frontend, backend, translations

#16061 Moved keywords in language file
  resources/lang/en-US/admin/settings/general.php
  resources/views/settings/index.blade.php
Labels: frontend, translations

#16046 Conditionally update assets when user's location moves via LDAP
  app/Console/Commands/LdapSync.php
Labels: backend, ldap, cli / artisan

#15981 Fixed: Asset Count on Users Index Page Counting Soft Deleted Items
  app/Http/Controllers/Api/UsersController.php
Labels: backend, api

#16011 Docker Improvement: Change the logging channel to storage/logs/laravel.log file
  .env.dev.docker
  docker/startup_alpine.sh
Labels: docker

#16010 Fixes : debug mode disabled and composer dev dependencies not installed in dev container
  .env.dev.docker
  Dockerfile.alpine
Labels: docker

#16036 Fixed unaccepted assets report memory exhaustion bug, Optimized query
  app/Http/Controllers/ReportsController.php
  app/Models/CheckoutAcceptance.php
  app/Observers/AssetObserver.php
Labels: backend

#16081 Fixed zerofill_count field being ignored during set up
  app/Http/Controllers/SettingsController.php
Labels: backend

#16089 Fixes #15017 - card view for mobile
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/mix-manifest.json
  resources/assets/less/overrides.less
Labels: frontend, css, skins

#16091 Better hide reset password functionality for LDAP users
  app/Http/Controllers/Auth/ResetPasswordController.php
  app/Http/Controllers/ProfileController.php
  app/Http/Controllers/Users/BulkUsersController.php
  resources/lang/en-US/general.php
  resources/views/account/view-assets.blade.php
  resources/views/layouts/default.blade.php
  resources/views/users/bulk-edit.blade.php
Labels: frontend, backend, translations

#16096 Automatically detect character encoding of CSV import files
  app/Http/Controllers/Api/ImportController.php
  composer.json
  composer.lock
  tests/Feature/Importing/Ui/ImportTest.php
  tests/Support/Importing/FileBuilder.php
Labels: backend, api, dependencies, tests

#16090 Fixed #16000 - add S3 support for eula PDF downloads
  app/Http/Controllers/ActionlogController.php
Labels: backend

#16099 Fixed #16097 - added location ID to location importer
  app/Importer/Importer.php
  app/Importer/ItemImporter.php
  app/Importer/LocationImporter.php
  app/Livewire/Importer.php
Labels: backend, importer

#16101 Use transformer for model files
  app/Http/Controllers/Api/AssetModelFilesController.php
  app/Http/Transformers/AssetModelsTransformer.php
  tests/Feature/AssetModels/Api/AssetModelFilesTest.php
Labels: backend, api, tests

#16102 Added serial as relation search
  app/Models/Actionlog.php
Labels: backend

#16105 Added fragment to uploads for redirect
  app/Http/Controllers/Accessories/AccessoriesFilesController.php
  app/Http/Controllers/AssetModelsFilesController.php
  app/Http/Controllers/Assets/AssetFilesController.php
  app/Http/Controllers/Components/ComponentsFilesController.php
  app/Http/Controllers/Consumables/ConsumablesFilesController.php
  app/Http/Controllers/Users/UserFilesController.php
  app/Http/Requests/UploadFileRequest.php
  resources/views/models/view.blade.php
Labels: frontend, backend, consumables

#16108 Migrate Form::submit helper
  resources/views/account/requestable-assets.blade.php
Labels: frontend

#16107 Replace calls to Form::password
  resources/views/settings/ldap.blade.php
  resources/views/setup/user.blade.php
Labels: frontend, ldap

#16118 Prevent undefined array key in asset observer
  app/Observers/AssetObserver.php
Labels: backend

#16140 Replace calls to Form::hidden
  resources/views/settings/backups.blade.php
  resources/views/settings/labels.blade.php
Labels: frontend, backups

#16148 Add Nullsafe
  app/Listeners/CheckoutableListener.php
Labels: backend
