Repository grokability/snipe-it, pull requests merged in 2025-03, with the labels that each got.

#16379 Feature/settings ldap invert active flag
  app/Console/Commands/LdapSync.php
  app/Http/Controllers/SettingsController.php
  database/migrations/2025_02_26_153413_add_ldap_invert_active_flag_to_setting_table.php
  resources/lang/en-US/admin/settings/general.php
  resources/views/settings/ldap.blade.php
Labels: frontend, backend, ldap, cli / artisan, translations

#16381 Replace calls to Form::checkbox pt9
  app/Livewire/CategoryEditForm.php
  resources/views/categories/edit.blade.php
  resources/views/livewire/category-edit-form.blade.php
  tests/Feature/Livewire/CategoryEditFormTest.php
Labels: frontend, backend, livewire, tests

#16396 Replace calls to Form::checkbox pt10
  resources/views/livewire/custom-field-set-default-values-for-model.blade.php
Labels: frontend, livewire

#16398 Avoid using authenticated user's email address in email partial
  resources/views/partials/forms/edit/email.blade.php
Labels: frontend

#16251 refactors audit notification to mail, adds test, adds alerts check to scheduler
  app/Console/Commands/SendUpcomingAuditReport.php
  app/Console/Kernel.php
  app/Mail/SendUpcomingAuditMail.php
  tests/Feature/Notifications/Email/ExpiringAlertsNotificationTest.php
  tests/Support/Settings.php
Labels: backend, cli / artisan, tests

#16403 Fixed #16402 - localize "each" string in components tab on asset view
  resources/lang/en-US/general.php
  resources/views/hardware/view.blade.php
Labels: frontend, translations

#16409 Fixed #16386 - some fields not populating with user data on edit
  app/Http/Controllers/Users/UsersController.php
Labels: backend

#16410 Fixed #16407 - weird layout on components for non super user
  resources/views/components/view.blade.php
Labels: frontend

#16412 Fixed regression from #16150
  resources/views/settings/branding.blade.php
Labels: frontend

#16415 Nicer model name formatting on RMB model not found
  app/Exceptions/Handler.php
Labels: backend

#16416 fix Expiring alert tests
  app/Console/Commands/SendExpirationAlerts.php
  app/Models/Asset.php
  tests/Feature/Notifications/Email/ExpiringAlertsNotificationTest.php
Labels: backend, cli / artisan, tests

#16414 Adds audit notification for MS Teams
  app/Models/Loggable.php
  app/Notifications/AuditNotification.php
Labels: backend, notifications

#16413 Changed `visited-link` and `link` colors in default theme to be more accessible
  resources/assets/less/skins/skin-blue.less
Labels: frontend, css, skins

#16418 Stop reporting report template events to activity log
  app/Models/ReportTemplate.php
  database/migrations/2025_03_04_231256_purge_action_logs_of_report_template_activity.php
  tests/Unit/ActionLogTransformer/ReportTemplateActionLogTransformerTest.php
  tests/Unit/Models/ReportTemplates/ReportTemplateActivityLoggingTest.php
Labels: backend, tests

#16420 Fixed custom report template route
  resources/views/reports/custom.blade.php
  routes/web.php
Labels: frontend

#16421 Replace calls to Form::label pt8
  resources/lang/en-US/admin/settings/general.php
  resources/views/partials/forms/edit/company-select.blade.php
  resources/views/settings/labels.blade.php
  resources/views/settings/ldap.blade.php
Labels: frontend, ldap, translations

#16427 Fixes user create modal - check if $item is set
  resources/views/partials/forms/edit/email.blade.php
Labels: frontend

#16429 Updated HTML label colors in blue skin
  public/css/dist/skins/_all-skins.css
  public/css/dist/skins/_all-skins.min.css
  public/css/dist/skins/skin-blue.css
  public/css/dist/skins/skin-blue.min.css
  public/mix-manifest.json
  resources/assets/less/skins/skin-blue.less
Labels: frontend, css, skins

#16432 Added validation around user store endpoint
  app/Http/Requests/SaveUserRequest.php
  tests/Feature/Users/Api/StoreUsersTest.php
Labels: backend, tests

#16436 Fixed linking in saved report template dropdown
  resources/views/reports/custom.blade.php
Labels: frontend

#16441 Added modal tests
  tests/Feature/Modals/Ui/ShowModalsTest.php
Labels: tests

#16065 Convert Form::select to blade component
  resources/views/blade/input/select.blade.php
  resources/views/categories/edit.blade.php
  resources/views/custom_fields/fields/edit.blade.php
  resources/views/custom_fields/fieldsets/view.blade.php
  resources/views/hardware/bulk.blade.php
  resources/views/hardware/checkin.blade.php
  resources/views/hardware/checkout.blade.php
  resources/views/hardware/quickscan-checkin.blade.php
  resources/views/livewire/custom-field-set-default-values-for-model.blade.php
  resources/views/livewire/importer.blade.php
  resources/views/livewire/slack-settings-form.blade.php
  resources/views/modals/partials/fieldset-select.blade.php
  resources/views/modals/statuslabel.blade.php
  resources/views/models/bulk-edit.blade.php
  resources/views/models/custom_fields_form.blade.php
  resources/views/models/custom_fields_form_bulk_edit.blade.php
  resources/views/partials/forms/edit/category.blade.php
  resources/views/partials/forms/edit/company.blade.php
  resources/views/partials/forms/edit/depreciation.blade.php
  resources/views/partials/forms/edit/location.blade.php
  resources/views/partials/forms/edit/maintenance_type.blade.php
  resources/views/partials/forms/edit/manufacturer.blade.php
  resources/views/partials/forms/edit/status.blade.php
  resources/views/partials/forms/edit/supplier.blade.php
  resources/views/settings/branding.blade.php
  resources/views/settings/general.blade.php
  resources/views/settings/labels.blade.php
  resources/views/statuslabels/edit.blade.php
  resources/views/users/confirm-bulk-delete.blade.php
Labels: frontend, custom fields, livewire

#16473 Replaced call to Form::close()
  resources/views/depreciations/view.blade.php
Labels: frontend

#16488 Properly handle route model bound LicenseSeat not being found
  app/Exceptions/Handler.php
  database/factories/UserFactory.php
  tests/Feature/Redirects/ModelNotFoundRedirectTest.php
Labels: backend, tests

#16445 Fixes CVE-2025-27515: Laravel has a File Validation Bypass
  composer.lock
Labels: backend, dependencies

#16443 FEAT: Add Label 5520 with 1D barcode - remove 2D barcode
  app/Models/Labels/Sheets/Avery/_5520_B.php
Labels: backend

#16489 Fixed timestamp in action log for bulk accessory check in
  app/Http/Controllers/Users/BulkUsersController.php
Labels: backend

#16491 Fixed new user modal pre-populating with first name and last name of acting user
  app/Http/Controllers/ModalController.php
  resources/views/modals/user.blade.php
  resources/views/partials/forms/edit/name-first.blade.php
  resources/views/partials/forms/edit/name-last.blade.php
  tests/Feature/Modals/Ui/ShowModalsTest.php
  tests/Feature/Users/Ui/CreateUserTest.php
Labels: frontend, backend, tests

#16495 Added highlight to items when the remaining is less than the min_amt
  app/Http/Transformers/AccessoriesTransformer.php
  app/Http/Transformers/AssetModelsTransformer.php
  app/Http/Transformers/LicensesTransformer.php
  app/Presenters/AccessoryPresenter.php
  app/Presenters/AssetModelPresenter.php
  app/Presenters/ComponentPresenter.php
  app/Presenters/ConsumablePresenter.php
  app/Presenters/LicensePresenter.php
  public/css/build/app.css
  public/css/build/overrides.css
  public/css/dist/all.css
  public/js/build/app.js
  public/js/dist/all.js
  public/mix-manifest.json
  resources/assets/less/overrides.less
  resources/views/accessories/index.blade.php
  resources/views/components/index.blade.php
  resources/views/consumables/index.blade.php
  resources/views/dashboard.blade.php
  resources/views/licenses/index.blade.php
  resources/views/models/index.blade.php
  resources/views/partials/bootstrap-table.blade.php
Labels: frontend, backend, javascript, css, consumables, skins

#16497 Fixed various carbon displays
  app/Http/Controllers/AssetMaintenancesController.php
  app/Http/Controllers/Assets/AssetsController.php
  app/Http/Controllers/ReportsController.php
  app/Http/Transformers/AssetsTransformer.php
  app/Models/Actionlog.php
  app/Observers/AssetObserver.php
  resources/views/hardware/view.blade.php
  resources/views/notifications/markdown/upcoming-audits.blade.php
  tests/Feature/AssetMaintenances/Ui/CreateAssetMaintenanceTest.php
  tests/Feature/AssetMaintenances/Ui/EditAssetMaintenanceTest.php
  tests/Feature/Assets/Ui/EditAssetTest.php
  tests/Feature/Checkins/Api/AssetCheckinTest.php
  tests/Feature/Checkins/Ui/AssetCheckinTest.php
  tests/Feature/Checkouts/Api/AssetCheckoutTest.php
  tests/Feature/Checkouts/Ui/AssetCheckoutTest.php
Labels: frontend, backend, tests

#16498 Merge develop into master
  app/Http/Controllers/AssetMaintenancesController.php
  app/Http/Controllers/Assets/AssetsController.php
  app/Http/Controllers/ReportsController.php
  app/Http/Transformers/AssetsTransformer.php
  app/Models/Actionlog.php
  app/Observers/AssetObserver.php
  resources/views/hardware/view.blade.php
  resources/views/notifications/markdown/upcoming-audits.blade.php
  tests/Feature/AssetMaintenances/Ui/CreateAssetMaintenanceTest.php
  tests/Feature/AssetMaintenances/Ui/EditAssetMaintenanceTest.php
  tests/Feature/Assets/Ui/EditAssetTest.php
  tests/Feature/Checkins/Api/AssetCheckinTest.php
  tests/Feature/Checkins/Ui/AssetCheckinTest.php
  tests/Feature/Checkouts/Api/AssetCheckoutTest.php
  tests/Feature/Checkouts/Ui/AssetCheckoutTest.php
Labels: frontend, backend, tests

#16486 Fixed location being automatically populated on asset checkin screen
  resources/views/blade/input/location-select.blade.php
  resources/views/hardware/checkin.blade.php
Labels: frontend

#16519 Fixed issue with bad email addresses in expiration alerts and upcoming audits
  app/Console/Commands/SendExpirationAlerts.php
  app/Console/Commands/SendUpcomingAuditReport.php
Labels: backend, cli / artisan

#16526 Merge #16486 and #16519 into master
  app/Console/Commands/SendExpirationAlerts.php
  app/Console/Commands/SendUpcomingAuditReport.php
  resources/views/blade/input/location-select.blade.php
  resources/views/hardware/checkin.blade.php
Labels: frontend, backend, cli / artisan

#16545 changes translation from Admin Settings to Created By on the Activity Report
  resources/views/reports/activity.blade.php
Labels: frontend

#16577 Added tests around login attempt logging
  tests/Feature/Authentication/LoginTest.php
Labels: tests

#16520 Remove unneeded eager loading for user show page
  app/Http/Controllers/Users/UsersController.php
Labels: backend

#16546 Fixed potential bad method call and premature email sending in bulk asset checkout
  app/Http/Controllers/Assets/BulkAssetsController.php
  tests/Feature/Checkouts/Ui/BulkAssetCheckoutTest.php
Labels: backend, tests

#16540 Early return null from location transformer for missing accessory
  app/Http/Transformers/LocationsTransformer.php
Labels: backend

#16536 Moving warranty/depreciation to be with the other cost/eol values
  app/Http/Controllers/ReportsController.php
  resources/views/reports/custom.blade.php
Labels: frontend, backend

#16559 Fix Form save error when using old label engine
  app/Http/Requests/StoreLabelSettings.php
Labels: backend

#16595 Fix whitespace encrypted custom fields display [FD-46570]
  resources/views/hardware/view.blade.php
Labels: frontend

#16594 Fixes [FD-47675 ] Fix consumable model number copy-to-clipboard button
  resources/views/consumables/view.blade.php
Labels: frontend, consumables
